### ISSUE TITLE
Error when generating a PDF from Blowfish-themed site

### ISSUE THREAD

**Issue by eread** [nunocoracao/blowfish#1014]
When generating a PDF using Paged.js (https://pagedjs.org) from a page (https://eread.gitlab.io/eread/about-me/) on a Blowfish-themed site, I get the following error:

```shell
DOMException: Failed to execute 'querySelectorAll' on 'DocumentFragment': '[class~=not-prose] *))::before' is not a valid selector.
```

The problem started with Blowfish v2.42.0 (which was tagged but not released - https://github.com/nunocoracao/blowfish/compare/v2.41.1...v2.42.0) and persists with Blowfish v2.43.0.

The PDF of the should be successfully generated, as it is with Blowfish v2.41.1 and earlier. See: https://eread.gitlab.io/eread/about-me/about-evan-read.pdf.

**Comment by eread** [comment]
Hi @nunocoracao 👋🏻 

I've been using Blowfish for my site (https://eread.gitlab.io/eread/) and really like it!

Something I've been doing is generating a PDF from the "About me" page (https://eread.gitlab.io/eread/about-me/). This has been working fine (for example: https://eread.gitlab.io/eread/about-me/about-evan-read.pdf) until the last release (or last two tags).

I'm imaging it's something to do with a Blowfish dependency, rather than Blowfish itself, but I thought I'd raise an issue here first. It doesn't seem to be a problem with the Hugo version or other dependency. I've moved all my project's dependencies forward as far as I can - I only need to keep Blowfish pinned back.

It's probably not trivial for you to reproduce, but if you can give me some troubleshooting ideas, I can try them out locally.

Thanks!

**Comment by eread** [comment]
@nunocoracao I assume it's these commits:

- https://github.com/nunocoracao/blowfish/commit/870d126a8f4fb6311b0ee22f45e99bf0f4061317
- https://github.com/nunocoracao/blowfish/commit/4a660645d42089b098623c89f63ee18c67c9bedd
- https://github.com/nunocoracao/blowfish/commit/e434fe9c9918c85b6689527e04382e47eb17ce30
- https://github.com/nunocoracao/blowfish/commit/b5471d52ae2000c65d7ad232a61024a9ad20946d
- https://github.com/nunocoracao/blowfish/commit/4baf448a5e5f32c1da64df27b095d21a94b6a247

**Comment by eread** [comment]
@nunocoracao Maybe a full dependency update for Blowfish would fix things for me?

**Comment by eread** [comment]
> @nunocoracao Maybe a full dependency update for Blowfish would fix things for me?

Actually, the issue I've raised here is the same as: https://github.com/tailwindlabs/tailwindcss-typography/issues/320.

**Comment by eread** [comment]
> @nunocoracao Maybe a full dependency update for Blowfish would fix things for me?

I can confirm that pinning `"@tailwindcss/typography": "0.5.9",` fixes the problem for me.

**Comment by eread** [comment]
I'm closing this one because I found an alternative PDF generator: https://github.com/condorheroblog/html-export-pdf-cli.

This works fine with the current versions of Blowfish.

**Comment by nunocoracao** [comment]
Sorry for the late response @eread thanks

**Comment by eread** [comment]
> Sorry for the late response @eread thanks

All good, thanks for all your work @nunocoracao.
