### ISSUE TITLE
Example of blowfish theme project

### ISSUE THREAD

**Issue by jawaylog** [nunocoracao/blowfish#103]
What I want to ask is, after downloading the theme, the theme contains many document tutorials, and I want to delete them all, that is, the articles of docs and samples. After all, building a real website means that these document tutorials are useless. However, I found that deleting the articles of docs and samples would cause errors. So, what I want to ask is, can't the document tutorials in this be deleted? If it can be deleted, which document articles should be kept？
![1665757507359](https://user-images.githubusercontent.com/87666210/195872532-d5247031-4884-4c49-bbec-9b8988d1a82f.jpg)
![1665757694335](https://user-images.githubusercontent.com/87666210/195872551-0f0982e6-f40d-415c-9675-ff6a4ab5765c.jpg)
![1665757824778](https://user-images.githubusercontent.com/87666210/195872560-1289eec3-23a4-4873-a30d-efcc8d6ca05b.png)

**Comment by nunocoracao** [comment]
Hello @jawaylog, let me see if I can help. You are 100% right, everything in the exampleSite folder can be deleted. 
Can you clarify how did you install the theme so that I can try to reproduce the error?

**Comment by jawaylog** [comment]
Hello @nunocoracao , the installation method I use is git, and then I copy and replace the files in the exampleSite directory in the theme to hugo root directory, so that the website can run. But in hugo's root directory, delete some articles of docs and samples in the content or delete the docs and samples folder. The mistake I mentioned above will happen. In the end, my approach is to delete the Tags folder and users.md, and the website can run.

**Comment by nunocoracao** [comment]
ah got it, you are using the configs from exampleSite as your starting point and cleaning everything, is that it? Check the docs for the menu configuration and taxonomies for what needs to be changed. The exampleSite uses almost all feaures available in Blowfish so it's hard to clean up. Will close this issue now.
