### ISSUE TITLE
Display thumbnail on article page

### ISSUE THREAD

**Issue by chrisbanes** [nunocoracao/blowfish#104]
The [thumbnail](https://nunocoracao.github.io/blowfish/docs/thumbnails/#thumbnails) support is really nice, but as I migrate from an existing site, I'd love for this image to be automatically displayed within the header for the article itself.

At the moment it only seems to displayed on article lists.

**Comment by nunocoracao** [comment]
Hello @chrisbanes thanks for the suggestion. That is already possible by placing either a markdown tag or a img html tag in the article. Because it is already possible I am wondering whether it should be an automatic behavior. Specially because then we would need a way of turning it off. Maybe with a new article config?

**Comment by chrisbanes** [comment]
Yep, I could add an image to the content itself, but that wouldn't support things like a 'full bleed' image, which are common on most blogs these days.

Agreed about the config param!

**Comment by nunocoracao** [comment]
Do you have any examples of how you would like this to be implemented?

**Comment by chrisbanes** [comment]
Medium does this, as does Ghost. My current blog (which I'm migrating away from) is a Ghost + Gatsby site and also has this:

https://chris.banes.dev

**Comment by nunocoracao** [comment]
@chrisbanes thanks

I think it should be implemented as an additional configuration which might be on by default. Something in global and per article as the for other elements e.g. taxonomies. Do you think that would work?

**Comment by chrisbanes** [comment]
Yep! Alternatively it could be a different layout. Either works for me.

**Comment by nunocoracao** [comment]
the config option it's easier to implement and maintain let's go with that
