### ISSUE TITLE
Doesn't the theme support other languages? Setting ko causes a sitemap error.

### ISSUE THREAD

**Issue by laterre39** [nunocoracao/blowfish#1045]
**Describe the bug**
Doesn't the theme support other languages? Setting ko causes a sitemap error.

**To Reproduce**
Set ko in config and an error occurs at build time.

**Expected behavior**
The build had to work normally without any problems. In other themes, the settings worked normally.

**Screenshots**
<img width="1376" alt="스크린샷 2023-11-04 오후 5 09 21" src="https://github.com/nunocoracao/blowfish/assets/32818386/9726ca68-4afd-4659-8f06-ff625997c5ca">

**Desktop (please complete the following information):**
 - @netlify/build 29.24.3

**Comment by nunocoracao** [comment]
That seems to be using an old version of Hugo, have you tried updating?

**Comment by laterre39** [comment]
Oh... I solved it by checking and updating.

I should have searched more. Thank you.
