### ISSUE TITLE
The informations of front matter went wrong on my GitHub page.

### ISSUE THREAD

**Issue by daVimci** [nunocoracao/blowfish#1047]
**Describe the bug**
I am the begginer using the Hugo to construct the personal website. Recently, when I push my config to the GitHub page, the date in my page can't show correctly.

**Screenshots**
![image](https://github.com/nunocoracao/blowfish/assets/87670378/6c348bb7-d5a7-4960-8839-9191bc832628)

The image above shows perfectly when I use the localhost. However, There's something error when I deploy it on the Github page which is depicted below.

![image](https://github.com/nunocoracao/blowfish/assets/87670378/269f1483-67d4-44ea-b464-07a74f1c963b)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Browser: Firefox

**Comment by nunocoracao** [comment]
Hello @daVimci which version of Hugo and Blowfish are you using?

**Comment by ragibson** [comment]
Fixed upstream in https://github.com/jpanther/congo/issues/689 / https://github.com/jpanther/congo/commit/c87c9adecea4133b646dea43c2aa75b0b04d5074 -- apparently due to a change in Hugo v0.120.0.

The specific change required is mentioned in [Hugo's release notes for that version](https://github.com/gohugoio/hugo/releases/tag/v0.120.0).

**Comment by ragibson** [comment]
Even on a fresh project from the sample template, it all seems to work on my end with
```bash
$ hugo version
hugo v0.120.4
$ git submodule status
 784e161371331789ff9d5d54a1322c424b956862 themes/blowfish (v2.44.0)
```
![image](https://github.com/nunocoracao/blowfish/assets/14023456/442b38b7-07c3-4207-af9d-937ab6b20e26)

**Comment by benjamin87-design** [comment]
hmm, guess i have to build it step by step again to find the error

**Comment by benjamin87-design** [comment]
Your are right, i just rebuild it and all are fine now

**Comment by daVimci** [comment]
@ragibson After I update the version of Blowfish to V2.44.0 and Hugo to V0.120.4 and all are good now!
