### ISSUE TITLE
Support customization of Open Graph Metadata

### ISSUE THREAD

**Issue by c-elliott96** [nunocoracao/blowfish#1052]
**Is your feature request related to a problem? Please describe.**
Not a problem; desired functionality.

**Describe the solution you'd like**
Ability to customize applicable Open Graph Metadata, namely to enable nice link sharing in Apple iMessages (e.g. to add an image to a link). See [documentation](https://developer.apple.com/library/archive/technotes/tn2444/_index.html).

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by c-elliott96** [comment]
That seems to track with how you've set up customization thus far, although I do not have the knowledge to consider pitfalls of that approach, if any. Thanks for being active and taking user feedback.

**Comment by nunocoracao** [comment]
I mean OG tags are already working. Try it out with one of Blowfish's page - or my personal homepage. So I was assuming that you want article level control over OG tags. Did I get it right?

**Comment by arunoruto** [comment]
> So I was assuming that you want article level control over OG tags. Did I get it right?

If this is what you, @c-elliott96, want, you can look up the documentation of hugo on open graph [here](https://gohugo.io/templates/internal/#open-graph). They describe how to change the open graph data for each file in your content directory.

**Comment by c-elliott96** [comment]
Ah, shame on me for not realizing that before creating an issue! Thank you both, @nunocoracao and @arunoruto for your help. Closing, as it looks like my request already exists.
