### ISSUE TITLE
🐛 HTML metadata of blog post not being evaluated with Github CI

### ISSUE THREAD

**Issue by OxNinja** [nunocoracao/blowfish#1060]
**Describe the bug**
> HTML metadata of blog post not being evaluated with Github CI

To make things short: I build my site with Github pages + CI/CD from this repo -> http://github.com/OxNinja/blog
On my machine with `hugo serve` I get what I want (see expected behavior), but with the CI I get something bad (see the following screenshot).

<img width="178" alt="image" src="https://github.com/nunocoracao/blowfish/assets/57400445/da679a32-729a-4142-89c6-ac1652d8f5c8">

I have been using Blowfish for about a month now and prior to my last push (last week) I have not encountered this error/bug.

**To Reproduce**
For the moment I did not try to create a new repo with Blowfish + the Github pages CI.
My steps are:
1. commit new changes on local repo
2. push to remote
3. CI rebuilds the website
4. go to my blog
5. see the inline HTML

**Expected behavior**
On a local hugo build I get this:

<img width="179" alt="image" src="https://github.com/nunocoracao/blowfish/assets/57400445/d89a289b-eea3-4209-b598-41e4c939c1d3">

**Desktop:**
 - OS: Archlinux, Android, Windows
 - Browser: Firefox
 - Version: 118.0.2, 119.1.1

**Hugo & Blowfish versions**
On my local machine: `hugo v0.119.0+extended`
The Github CI uses `peaceiris/actions-hugo@v2`

I am using the latest Blowfish version with `git submodule update --init --recursive`

**Comment by ennnbeee** [comment]
Also getting this same issue building locally with latest version of the theme.
Version `hugo v0.120.4-f11bca5fec2ebb3a02727fb2a5cfb08da96fd9df+extended windows/amd64 BuildDate=2023-11-08T11:18:07Z VendorInfo=gohugoio`

**Comment by nunocoracao** [comment]
Hello @ennnbeee @OxNinja, could you please follow these instructions and let me know if the you still have issues?

1. Update local Hugo to the latest version and update the theme
2. regarding CI add the version parameter to it example below for GitHUb Actions

```
name: Hugo setup
        uses: peaceiris/actions-hugo@v2.6.0
        with: 
          hugo-version: 0.120.4
          extended: true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
```

**Comment by ennnbeee** [comment]
> Hello @ennnbeee @OxNinja, could you please follow these instructions and let me know if the you still have issues?
> 
> 1. Update local Hugo to the latest version and update the theme
> 2. regarding CI add the version parameter to it example below for GitHUb Actions
> 
> ```
> name: Hugo setup
>         uses: peaceiris/actions-hugo@v2.6.0
>         with: 
>           hugo-version: 0.120.4
>           extended: true
>         env:
>           ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
> ```

I cleared out the theme as a submodule and re-added it to my repo, now working locally.

**Comment by OxNinja** [comment]
Thank you for the response, I changed the `actions-hugo`'s version and added the `ACTIONS_ALLOW_UNSECURE_COMMANDS` variable (on this commit: https://github.com/OxNinja/blog/commit/08e9abd078e46a1d922a942d13fee7ddb9d1dc2d) but I still have this issue.
Maybe I should change my `actions/checkout` version as well

**Comment by OxNinja** [comment]
Latest vesion (https://github.com/nunocoracao/blowfish/releases/tag/v2.49.1) seems to have fixed this bug
