### ISSUE TITLE
💖 Handle Enter key in search

### ISSUE THREAD

**Issue by JVimes** [nunocoracao/blowfish#1104]
**Is your feature request related to a problem? Please describe.**

I instinctually hit  Enter after typing search query, and I think a lot of people do. But this makes the results disappear.

**Describe the solution you'd like**

When Enter is pressed in the search box, keep search results open and, if there are results, then move keyboard focus to the results list.

**Describe alternatives you've considered**

Using a search results page instead of modal list.

**Comment by nunocoracao** [comment]
@JVimes done :)
Thanks for the suggestion - let me know if this works

**Comment by JVimes** [comment]
Works beautifully, thank you! I can event hit Enter twice quickly, if I know the result ahead of time.

**Comment by runofftheearth** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> I instinctually hit Enter after typing search query, and I think a lot of people do. But this makes the results disappear.
> 
> **Describe the solution you'd like**
> 
> When Enter is pressed in the search box, keep search results open and, if there are results, then move keyboard focus to the results list.
> 
> **Describe alternatives you've considered**
> 
> Using a search results page instead of modal list.



> **Is your feature request related to a problem? Please describe.**
> 
> I instinctually hit Enter after typing search query, and I think a lot of people do. But this makes the results disappear.
> 
> **Describe the solution you'd like**
> 
> When Enter is pressed in the search box, keep search results open and, if there are results, then move keyboard focus to the results list.
> 
> **Describe alternatives you've considered**
> 
> Using a search results page instead of modal list.

我也遇到了同样的问题，经过排查，是因为我GitHub pages绑定了域名，与配置文件里baseURL =“GitHub用户名.github.io”处域名不一致导致的。将两处的域名保持一致后，博客的搜索功能就可以正常已使用了。
