### ISSUE TITLE
🐛 Some Figure Shortcode Attributes Have No Effect

### ISSUE THREAD

**Issue by gibru** [nunocoracao/blowfish#1112]
**Describe the bug**

When using the figure short code according to the example found in the documentation, multiple attributes have no effect, namely:

1. href="https://mylink.com" (with nozoom=true): the image doesn't contain the link
2. class: using custom.css with a class (.myclass) doesn't seem to have an affect when defined in shortcut (class="myclass"). This works with normal html/css (e.g. <span class="myclass">)
3.  defaut=true doesn't seem to have any effect at all

What works: src, caption, nozoom and alt

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox, Chrome, Brave

**Hugo & Blowfish versions**
hugo v0.120.1 /  blowfish 2.47.2

**Comment by qalldredge** [comment]
I see that the link works but even with nozoom=true it still zooms. It makes it awkward because the image will zoom and then the link is followed.

**Comment by gibru** [comment]
Yes, that is less than ideal. Without having to completely disable zoom, a workaround is to just use standard html and add the nozoom class to your img tag:

```
<a href="https://yourlink">
   <img class="nozoom" src="image source" ...>
</a>
```

**Comment by qalldredge** [comment]
Thank you. That works as a workaround.

**Comment by nunocoracao** [comment]
Sorry @gibru @qalldredge I'll take a look at this one. I probably messed something up in one of the last releases.

**Comment by keesfluitman** [comment]
could it be that custom class in the shortcode has no effect yet? nozoom works. but class=customClass has no effect.
