### ISSUE TITLE
✨ External Markdown Importer Shortcode

### ISSUE THREAD

**Issue by arunoruto** [nunocoracao/blowfish#1115]
**Is your feature request related to a problem? Please describe.**
It is sometimes cumbersome to update things in multiple places. So I would recommend somehow importing the README.md from github (sometimes it is  displayed on the profile).

**Describe the solution you'd like**
When a keyword is provided, like github_username, the content of the README.md file will be imported into the `about me` page. A potential solution is described below.

**Describe alternatives you've considered**
Copy and paste the text whenever it is changed or link to the page. Both methods are not that elegant sadly...

**Additional context**
I am new to hugo, so I am not sure if this is the best solution to this "problem". The README.md file is available at `https://raw.githubusercontent.com/<username>/<username>/main/README.md`. So I am fetching this using the following code snippet:
```hugo
{{ with .Site.Params.DataImports.github }}
    {{ with resources.GetRemote (printf "https://raw.githubusercontent.com/%s/%s/main/README.md" . .) }}
        {{ with .Err }}
            {{ errorf "%s" . }}
        {{ else }}
            {{ .Content | markdownify }}
        {{ end }}
    {{ else }}
        {{ errorf "Unable to get remote resource from %q" . }}
    {{ end }}
{{ end }}
```
I am currently building my website using Blowfish and testing this solution. [Here](https://github.com/arunoruto/blowfish/blob/main/layouts/_default/about-git.html#L81C1-L81C1) is the place where I inserted it into my layout. I took the [single.html](https://github.com/nunocoracao/blowfish/blob/main/layouts/_default/single.html) layout and modified it.

I would be happy about any feedback!

**Comment by nunocoracao** [comment]
@arunoruto I think it would be better to implement this as a shortcode - reusable - and it doesn't need to be hardcoded readme.md from github could work for any external .md files

**Comment by nunocoracao** [comment]
@arunoruto sorry for not waiting - implemented this for the next release

**Comment by arunoruto** [comment]
Awesome! Thanks for the quick feedback :D
Until it's merged into the next release, I will have a copy of the shortcode in my repo.
