### ISSUE TITLE
🐛 Shortcodes Gallery : Images are not correctly displayed

### ISSUE THREAD

**Issue by v20100v** [nunocoracao/blowfish#1125]
**Describe the bug**

When you display only one or more galleries on the page, the images are too small and do not take up the available space.

![image](https://github.com/nunocoracao/blowfish/assets/7567933/78a3eaee-9980-4e3f-a300-38b819f13b3b)

But if we add enough text in the column, then the images are correctly displayed... unless the text takes up too much space and in this case the images are no longer correctly aligned horizontally.

![image](https://github.com/nunocoracao/blowfish/assets/7567933/327e1ba0-3e02-42c0-8f49-6c2d61cc16f9)

**To Reproduce**

1. Create new blowfish project 

2. Create this post
```html
---
title: "Hugo theme Blowfish - Bug gallery"
date: 2023-12-15
---

### First

{{< gallery >}}
  <img src="amstrad-464/img_1.png" class="grid-w50 md:grid-w33 xl:grid-w25" />
  <img src="amstrad-464/img_2.png" class="grid-w50 md:grid-w33 xl:grid-w25" />
  <img src="amstrad-464/img_3.png" class="grid-w50 md:grid-w33 xl:grid-w25" />
  <img src="amstrad-464/img_4.png" class="grid-w50 md:grid-w33 xl:grid-w25" />
{{< /gallery >}}

### Second

Lorem ipsum.

{{< gallery >}}
<img src="amstrad-464/img_4.png" class="grid-w50" />
<img src="amstrad-464/img_5.png" class="grid-w50" />
{{< /gallery >}}
```

**Expected behavior**

Let the gallery(s) occupy the entire width.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Edge
 - Version : 120.0.2210.61 
 
**Hugo & Blowfish versions**
Which version of Hugo and Blowfish are you using?

- hugo v0.120.4-f11bca5fec2ebb3a02727fb2a5cfb08da96fd9df+extended windows/amd64 BuildDate=2023-11-08T11:18:07Z VendorInfo=gohugoio
- Blowfish : 2.47.2

**Comment by v20100v** [comment]
Looking at the code, I noticed another problem.

When displaying several galleries on the same page, they may share the same ID. This occurs when galleries are included in a `timelineitem`.

```html
---
title: "Hugo theme Blowfish - Bug galleries in timeline"
date: 2023-12-15
---


### Galleries in timeline

{{< timeline >}}

    {{< timelineItem icon="amstrad" header="Amstrad" subheader="CPC-464">}}
        {{< gallery >}}
            <img src="amstrad-464/img_1.png" alt="Amstrad CPC-464" title="Amstrad CPC-464" class="grid-w50" />
            <img src="amstrad-464/img_3.png" alt="Amstrad CPC-464 - Read error a or b ?" title="Read error a or b ?" class="grid-w25" />    
            <img src="amstrad-464/img_2.png" alt="Amstrad CPC-464" title="Amstrad CPC-464" class="grid-w15" />
            <img src="amstrad-464/img_4.png" class="grid-w15" />
            <img src="amstrad-464/img_5.png" alt="Amstrad CPC-464 - The CAT command" title="The CAT command" class="grid-w15" />
        {{< /gallery >}}
    {{< /timelineItem >}}

    {{< timelineItem icon="amstrad" header="Title" subheader="CPC-6128">}}
        {{< gallery >}}
            <img src="amstrad-6128/cauldron-title-green.png" alt="Amstrad Cauldron" title="Amstrad Cauldron" class="grid-w50" /> 
            <img src="amstrad-6128/cauldron-green.png" alt="Amstrad Cauldron" title="Amstrad Cauldron" class="grid-w50" />
        {{< /gallery >}}

        <p class="mb-6">
            Lorem ipsum...
        </p>

        {{< gallery >}}
            <img src="amstrad-6128/cauldron-title-color.png" alt="Amstrad Cauldron" title="Amstrad Cauldron" class="grid-w50" />
            <img src="amstrad-6128/cauldron-color.png" alt="Amstrad Cauldron" title="Amstrad Cauldron" class="grid-w50" />
        {{< /gallery >}}
    
        <p class="mb-6">
            Lorem ipsum est maf.
        </p>
    {{< /timelineItem >}}


    {{< timelineItem header="Next" subheader="CPC-464">}}
        {{< gallery >}} 
            <img src="amstrad-464/img_2.png" alt="Amstrad CPC-464" title="Amstrad CPC-464" class="grid-w50" />
            <img src="amstrad-464/img_4.png" class="grid-w50" />
            <img src="amstrad-464/img_5.png" alt="Amstrad CPC-464 - The CAT command" title="The CAT command" class="grid-w50" />
        {{< /gallery >}}
    {{< /timelineItem >}}

{{< /timeline >}}
```

As the compilation (generation of the site) goes too quickly with Hugo, I have the impression that the galleries share the same timestamp and the ordinal no longer works in this context.

You can see in the screenshot below that these two galleries (in different timeline items) have the same id.

![image](https://github.com/nunocoracao/blowfish/assets/7567933/4aadebdb-2ebe-4605-b598-c4bb2795f24a)

**Comment by MaikelChan** [comment]
Turns out that this PR has brought back the issue of overlapping images in the gallery.
