### ISSUE TITLE
Unable to create a multi-language blog

### ISSUE THREAD

**Issue by Thanatermesis** [nunocoracao/blowfish#1139]
I have already a small blog website using DoIt theme, it is set in 2 languages (default: en, extra: es), I tried to move to the blowfish template but it fails when I add the second language.

For this I just copied the config/_default/languages.en.toml to the extra one changing the default values, tried the same with the menus.en.toml file, but it always fail with the error message:

Error: Error building site: render of "sitemap" failed:
```
"/home/thana/tmp/sshfs/mywebsite/themes/blowfish/layouts/_default/sitemap.xml:13:28": execute of template failed: template: _default/sitemap.xml:13:28: executing "_default/sitemap.xml" at <.Language.LanguageCode>: can't evaluate field LanguageCode in type *langs.Language
```

I tried with a new & fresh hugo website without any previous setting, different versions of hugo, etc... it always fail by just adding the extra language

**Comment by nunocoracao** [comment]
Hello @Thanatermesis can you point me to your repo so that I can check the code? Maybe I am able to help or understand what is wrong.

**Comment by Thanatermesis** [comment]
I didn't changed the code, it's the default one and added the extra
language file, it simply fails to build 🤔🤷🏽‍♀️

**Comment by nunocoracao** [comment]
Where can I see the change you made?

**Comment by Thanatermesis** [comment]
I didn't made any change in the code

**Comment by Thanatermesis** [comment]
I have made you a recording of the session from a clean cloned blowfish repo, showing that it works, and then creating the language configuration which is where it fails:  https://asciinema.org/a/629920

**Comment by nunocoracao** [comment]
@Thanatermesis I do not understand the changes you made. Several users are using multi-language setups (e.g. https://niklas-hartmann-dev.de) without issue. I don't mind trying to help but if there is no way for me to check the code I will assume that this is a bad configuration on your side not a bug on the theme.

**Comment by nunocoracao** [comment]
I would upgrade Hugo
Check this example i created with multi-language

https://github.com/nunocoracao/blowfish_lite
https://nunocoracao.github.io/blowfish_lite/

**Comment by Thanatermesis** [comment]
I tried your example site but I have the same issue

Then I tried different versions of blowfish and noticed that it works on version v.2.43.0 but not in v2.43.1, so I used git bisect and found that the issue happened since the commit 10ac37ba29fa55d2b3cc82933c8cfb692c753cf0

**Comment by yct72** [comment]
Same issue here. No modifications, changing English to other language makes it fail.

**Comment by yct72** [comment]
@Thanatermesis @nunocoracao Just solved this by replacing ` .Language.LanguageCode`  with  ` .Language.Params.languageCode`. I'm not sure why others work fine without this, but maybe considering fixing this?
Similar problem [here](https://discourse.gohugo.io/t/missing-languagecode-on-language-objects/22426).

**Comment by Thanatermesis** [comment]
I wonder if this is an issue in Hugo, or in the template, or if people are using older versions of the template 🤔

**Comment by Thanatermesis** [comment]
I can confirm the change by @yct72 makes it working, on the other hand it seems like it needs to be enabled manually the sections wanted from the "menus" configuration (like, posts, categories, etc) as it is shown by default, so without the subfolder (so, "posts" and not "en/posts" which is automatically set)

@nunocoracao are you going to commit this fix? I'm considering to switch my blog from DoIt to Blowfish

**Comment by Anasme** [comment]
why is this closed? I have the same issue from a fresh install in a linux env (with last version of hugo and blowfish theme)

**Comment by abdelhak2406** [comment]
@Anasme  same here
