### ISSUE TITLE
ZenMode doesn't change the width of the article when "showTableOfContents" is set to false

### ISSUE THREAD

**Issue by gibru** [nunocoracao/blowfish#1150]
**Describe the bug**
ZenMode doesn't change the width of the article when "showTableOfContents" is set to false.

**To Reproduce**
1. Set showTabeleOfContents to false in front matter
2. Click on ZenMode
3. Author info disappears, but the width remains unchanged

**Expected behavior**
Article width should expand the same way as it does when showTableOfContents is set to true

And more of a feature request: would also be possible to have a param for ZenMode in the front matter to have it as the default. The new width is really great and for some articles it would make sense to have it as the default.

Finally, can ZenMode right now only be activated/deactivated at the top of the article? I was wondering whether it would be possible to have it activate/deactivate anywhere (like scroll to top) as it would allow to use it without interrupting the reading flow.

**Comment by nunocoracao** [comment]
@gibru yes please :)
Also tag @v20100v in these discussions since he was the original creator of the feature

**Comment by v20100v** [comment]
Hello @gibru,

> So I've played some more with ZenMode and I guess the way it works right now is intentional 

That's right ! That was my first intention, but maybe you have a better idea ? If you want to open a new discussion, it's with pleasure ^^.

**Comment by fairchild26** [comment]
Sorry to bother you @v20100v , I have the same question as the author. The ZenMode is meaningful. I have three articles, two of which can use ZenMode normally, but one of them cannot: enabling ZenMode can hide author information and table of contents, but the article width has not changed.

What I prefer is that a certain article doesn't need a side table of contents at all. I hope it can have a wider display without manually turning on ZenMode.

**Comment by fairchild26** [comment]
Hello @v20100v 
I have found the key to the problem! My article consists of images and text, and I hope the images can be enlarged, but their width follows the length of the sentence. Haha, my sentence is too short, so the pictures have always been small.

**Comment by v20100v** [comment]
Hello @fairchild2026, and thx for your feedback ^^..

You’re right in your analyses. I hadn’t tested this specific case, with a short text and images taking up most of the space.

The idea of being able to hide the side table of contents is indeed interesting, especially via an option in the front matter to enable it by default. Unfortunately, I currently have limited time to devote to improving this mode. If I manage to free up some time, I’ll work on it.
