### ISSUE TITLE
Blowfish not compatible

### ISSUE THREAD

**Issue by WilliamRagstad** [nunocoracao/blowfish#1151]
**Describe the bug**
When I follow the installation steps directly after installing the latest version of Hugo, I get:
```bash
> hugo mod graph
WARN  Module "blowfish" is not compatible with this Hugo version; run "hugo mod graph" for more information.
project blowfish
> hugo version
hugo v0.121.2-6d5b44305eaa9d0a157946492a6f319da38de154+extended windows/amd64 BuildDate=2024-01-05T12:21:15Z VendorInfo=gohugoio
```
And every time I safe any changes I see the following repeatedly:
```bash
Change of config file detected, rebuilding site.
2024-01-07 13:22:15.909 +0100
WARN  Module "blowfish" is not compatible with this Hugo version; run "hugo mod graph" for more information.
```

**To Reproduce**
1. Install Hugo v0.121.2
2. Install Blowfish using git module
3. Start server

**Expected behavior**
No errors from Hugo or Blowfish.

**Desktop (please complete the following information):**
 - OS: Windows
 - Hugo: From `choco install hugo-extended`

**Comment by WilliamRagstad** [comment]
I suppose it is due to the `max` field in `config.toml` which hasn't been adjusted after the latest Hugo update. My fix was simply to set it to `max = "0.121.2"`.

**Comment by nunocoracao** [comment]
Thanks for the PR @WilliamRagstad

**Comment by danielyrovas** [comment]
Why does Hugo work like this? Can blowfish be setup to ignore the minor version, so `max` would be `0.123.*`?

**Comment by nunocoracao** [comment]
@danielyrovas not a great idea - I mean it would be great for me - sometimes things break
