### ISSUE TITLE
Time error

### ISSUE THREAD

**Issue by jiajun-c** [nunocoracao/blowfish#1156]
**Describe the bug**
The time can't be rendered correctly
![image](https://github.com/nunocoracao/blowfish/assets/74438053/c4b8555a-550f-44ae-b4b3-2942a5adf42a)

**Desktop (please complete the following information):**
 - OS: archlinux
 - Browser chrome
 - Version: kernel 6.6

**Hugo & Blowfish versions**
2.49.1

**Comment by daviddias** [comment]
Saw caught this one on a website. You need to update to the latest blowfish as you probably already updated to the latest hugo. Did that and now works well.
