### ISSUE TITLE
GitHub Card renders incorrectly

### ISSUE THREAD

**Issue by StandingPadAnimations** [nunocoracao/blowfish#1165]
**Describe the bug**
The GitHub card shotcode has started to render weirdly when I updated to 2.49.1, and now looks like this:
![image](https://github.com/nunocoracao/blowfish/assets/75058058/548504e2-3876-40c6-b682-64d82767ff57)

**To Reproduce**
1. Use Blowfish 2.49.1
2. Build

**Expected behavior**
It shouldn't rendered incorrectly

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Vivaldi
 - Version: `6.5.3206.50 (Stable channel) stable (64-bit)`

**Hugo & Blowfish versions**
Hugo - 0.121.1
Blowfish - 2.49.1

**Additional context**
I'm using a GitHub Workflow for deployment: https://github.com/StandingPadAnimations/StandingPadAnimations.github.io/blob/main/.github/workflows/hugo.yaml

**Comment by nunocoracao** [comment]
![Screenshot 2024-01-14 at 23 28 16](https://github.com/nunocoracao/blowfish/assets/3803196/2e1ed32d-ff09-43e8-b481-999500aaa96a)
It renders correctly on the live version of the site. I would check any custom CSS or override ou are using.

**Comment by StandingPadAnimations** [comment]
It doesn't seem to be a CSS problem as it only breaks when passing `--minify` to Hugo, which my production build runs
