### ISSUE TITLE
Content Security Policy looks like to break typeit shortcode

### ISSUE THREAD

**Issue by Allaman** [nunocoracao/blowfish#1167]
Hello, firstly, I want to thank you for this great theme! 

**Describe the bug**
Content Security Policy looks like to break typeit shortcode (and more ...?). 

See [my page](https://rootknecht.net). There should be a typeit shortcut right on the homepage (cp. the [source](https://github.com/Allaman/rootknecht.net/blob/main/content/_index.md))

**To Reproduce**
Deploy to a web server (nginx in mycase) with CSP headers enabled, and there will be many errors in the console 
<img width="2302" alt="image" src="https://github.com/nunocoracao/blowfish/assets/12184268/97c4c989-64af-474a-8a01-70d2a8a491ce">

When spinning up locally via `hugo server` everything works as expected.

**Expected behavior**
The page should render the typeit shortcode 

**Desktop (please complete the following information):**
 - OS: latest iOS, macOS 13, Android 12
 - Browser Firefox and Chrome
 - Version both latest

**Hugo & Blowfish versions**
Hugo 1.20.4 and Blowfish v2.49.1

**Additional context**
Probably related to https://github.com/nunocoracao/blowfish/issues/705

**Comment by d4rklynk** [comment]
`default-src 'self' ac.mijope.de; frame-ancestors 'none'; style-src 'self' 'unsafe-inline'`

That's your CSP right ?

The typeit shortcode is inline script. So you have to set script-src to 'unsafe-inline'.
And usually, we set default-src to 'none'

**Comment by d4rklynk** [comment]
And FYI, CSP does not break stuff, it blocks it

**Comment by d4rklynk** [comment]
And for your analytics script (I guess it is) don't put it in the default-src, it is dangerous. Here's a correct version, of your CSP with your analytics:

`default-src 'none'; connect-src 'self' https://ac.mijope.de; img-src 'self'; script-src 'self' 'unsafe-inline' https://ac.mijope.de; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; upgrade-insecure-requests; manifest-src 'self'`

**Comment by Allaman** [comment]
Hello and thanks for your detailed answer!

According to [Mozilla Dev](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_inline_script): 

>  Disallowing inline styles and inline scripts is one of the biggest security wins CSP provides. 

So I doubt that allowing inline scripts is a proper solution. 🤔 

Nevertheless, I tested your suggestion and had [Mozilla Observatory](https://observatory.mozilla.org/) check my homepage with the suggested CSP headers in your last reply with the following result:

<img width="1287" alt="image" src="https://github.com/nunocoracao/blowfish/assets/12184268/d5bc111e-c42e-405f-9a44-b966767dfbf0">

Note that my grading went down from `A+` to `B-`!

Of course, the typeit shortcut isn't _blocked_ anymore, but for the price of less strict CSP headers

**Comment by d4rklynk** [comment]
Yes, well you have two options, either you take another hugo theme that has not inline style or inline script in its code either you rewrite blowfish entirely 😁.

Yes it's not recommended to use inline style or script according to [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html) but I'm not a dev, and I can't rewrite the code, so I use Blowfish, I am thankful to the dev and that's all I do.

WonderMod is a fork of Papermod that does not use inline script or inline style if you're interested https://github.com/Wonderfall/hugo-WonderMod/

**Comment by d4rklynk** [comment]
Edit: add "base-uri 'none'" in your CSP, I removed it for you from my template because default-src should take over, but apparently, mozilal is not happy.

**Comment by d4rklynk** [comment]
Tbf, if you have doubt or problem with CSP or other hardening stuff, just follow my configuration from my websites https://github.com/d4rklynk/simpleprivacy.fr and https://github.com/d4rklynk/samsepi0l.dev. For NGINX, just follow these configurations and you should be fine -> 
- https://github.com/GrapheneOS/grapheneos.org/blob/main/nginx/nginx.conf

or

- https://github.com/GlassROM/nginx-config/blob/master/nginx/nginx.conf

**Comment by Allaman** [comment]
Hello, and again, thanks for your kind answer. 

Yeah, we all do this kind of stuff in our valuable spare time and are not obliged to any stakeholders. I am just curious if the author and/or maintainers are aware of this issue and if they want to address it or not. No matter the answer, it is fine for me, of course.  It is a great theme and I sincerely appreciate the work.

I know wondermod, but to be honest, I don't like it as much as blowfish 🙉 

I will take a look at your configuration and maybe get inspired 😉

**Comment by d4rklynk** [comment]
https://github.com/nunocoracao/blowfish/issues/705

**Comment by d4rklynk** [comment]
You can also make a hash for every script and style, but if he changes some code, you will have to make new hash again.

**Comment by d4rklynk** [comment]
I tried to add hashes, that's the best you could do, but you should not update the theme lol, because it is unmaintainable as hell if you do.

And btw, hashes are not all there, because some of my articles won't laod some stuff like series or alert shortcode etc.

Good luck if you do so -> https://github.com/d4rklynk/samsepi0l.dev/blob/a3980c96fb3687a9d08cbf11cbc2166f36afb56c/static/_headers

**Comment by Allaman** [comment]
I took a look into adding the hashes and this is too much of a pain 😆 

I'll think I will go the easier route and allow inline scripts. I mean, it's a static website, after all and not a WordPress 😜

**Comment by d4rklynk** [comment]
Glad I was able to help you. You can probably close the issue now 👍
