### ISSUE TITLE
"disableImageOptimization = false" and yet, it doesn't seem to get images optimized

### ISSUE THREAD

**Issue by daviddias** [nunocoracao/blowfish#1170]
Perhaps I'm just not understanding what kind of optimization it should do. My expectation is for it to generate different image sizes to load faster in different devices. 

I'm not sure if it is doing that, or something else, or simply nothing. I do know that when I build the website, there are no "optimized" versions created (https://blowfish.page/docs/welcome/#automatic-image-resizing). Any tips for me to debug this? Thanks a lot in advance!

**Comment by knowinginner** [comment]
In your website [https://daviddias.me/posts/_adventurer-explorer/sailor-skipper-captain/](https://daviddias.me/posts/_adventurer-explorer/sailor-skipper-captain/) the image is served as 
`<div class="w-full h-36 md:h-56 lg:h-72 single_hero_basic nozoom" style="background-image:url(/posts/_adventurer-explorer/sailor-skipper-captain/featured_hu88d05a7c8a86566b7beec75e005fcf22_106060_1200x0_resize_q75_box.jpg)"></div>`
which means that it was resized to 1200px and with quality 75%

Author img 
`<img class="!mt-0 !mb-0 h-24 w-24 rounded-full ltr:mr-4 rtl:ml-4 medium-zoom-image" width="96" height="96" alt="David Dias" src="/img/me-square-small_hube146261802103da6b92b7156b2bf5ef_35202_192x192_fill_q75_box_center.jpg">`

was resized with quality of 75%

If you would like to load more rapidly serve img as webp.

Vlad

**Comment by daviddias** [comment]
When I opened this issue, it was actually for http://nuvem.magica.cat. Since then, we got it to work too. Thanks anyways mate! :)
