### ISSUE TITLE
✨ Global site background image

### ISSUE THREAD

**Issue by mirceanton** [nunocoracao/blowfish#1174]
**Is your feature request related to a problem? Please describe.**

Currently, I can only customize the background color for my site by overriding the css.

**Describe the solution you'd like**

I would like the ability to use an SVG file to be rendered as a background on the site, similar to:

![image](https://github.com/nunocoracao/blowfish/assets/28601784/d3c76db9-fb2d-43fe-bc70-1cae673b06b4)

We could use tools like https://pattern.monster/ to generate these pattern files, for example.

**Describe alternatives you've considered**

Alternatively, I could look into overriding the appropriate partial for my site, but I think this feature could be helpful to others as well.

**Additional context**

For reference, this is the site from which I took the screenshot: https://fumio.brightthemes.com/

**Comment by nunocoracao** [comment]
@mirceanton would it work for you if this is just a matter of being able to load a svg file with the current parameters or are you expecting a different behaviour?

**Comment by mirceanton** [comment]
I think that loading an SVG file would be a perfect solution!

That being said, I've just recently move my blog to Jekyll instead of Hugo so I won't be able to test this feature out anymore :(

**Comment by nunocoracao** [comment]
@mirceanton shame shame shame :P
