### ISSUE TITLE
❓ [site.Author] is deprecated

### ISSUE THREAD

**Issue by arunoruto** [nunocoracao/blowfish#1181]
**Describe the bug**
Currently, it isn't a bug, but a warning. In the future, when `site.Author` is dropped, it can lead to failing builds.

**To Reproduce**
Just build your project with Hugo version  `v0.120.0` or higher, and you will get a warning:
`WARN  The author key in site configuration is deprecated. Use params.author.name instead.`

**Expected behavior**
No warning in the console.

**Desktop (please complete the following information):**
 - OS: NixOS 23.11
 - Browser: google-chrome-stable
 - Version: 120.0.6099.216 (Official Build) (64-bit)

**Hugo & Blowfish versions**
hugo v0.120.3+extended and blowfish 2.51.0

**Additional context**
The deprecation notice can be viewed in the [release notes of v0.120.0](https://github.com/gohugoio/hugo/releases/tag/v0.120.0) under **Notes**

**Comment by Ast3risk-ops** [comment]
I also get this.

**Comment by jamesbraza** [comment]
I am not getting this deprecation notice with Hugo 0.121.2. Can one of you share your config files?

I think you configure author per https://blowfish.page/docs/configuration/#author in a `languages.en.toml` config, not in `hugo.toml`.

**Comment by nunocoracao** [comment]
Sorry @arunoruto @Ast3risk-ops I am not getting this warning, can you update to the lastes version and help me understand what needs to change?

**Comment by Ast3risk-ops** [comment]
> Sorry @arunoruto @Ast3risk-ops I am not getting this warning, can you update to the lastes version and help me understand what needs to change?

Yeah I don't get it anymore either.
