### ISSUE TITLE
[Feature] Option to load images from URLs

### ISSUE THREAD

**Issue by aakashnand** [nunocoracao/blowfish#1211]
**Is your feature request related to a problem? Please describe.**
Currently whenever I find documentation around images for this theme. It expects images to be added to the git repository. That is the image should be present in the `assets` folder and for the feature image, it should be present in each blog folder with a name like `feature**`. 

While this is great, I think this is not good as it will bloat the git repository. 

**Describe the solution you'd like**

Every image reference in the theme should have the option to display an image from some external URL or local reference. Giving both options to users will be a better experience and can reduce the repository size. 

**Describe alternatives you've considered**
I am not a Hugo expert but after some digging, I think it can be achieved `resources.GetRemote`using https://gohugo.io/functions/resources/getremote/

Although I have limited knowledge of how to implement this.

**Additional context**

Similar requests and discussions I found on this repo

1. https://github.com/nunocoracao/blowfish/discussions/880
2. https://github.com/nunocoracao/blowfish/discussions/932
3. #980 
4. #736

**Comment by nunocoracao** [comment]
@aakashnand your PR doesn't solve #736 right?

**Comment by aakashnand** [comment]
> @aakashnand your PR doesn't solve #736 right?

No it doesn't but this PR can be a good base for that issue as well. I think for carousel we might need to tweak around short-codes. 

If you want we can tackle that in different PR

**Comment by nunocoracao** [comment]
fixed in https://github.com/nunocoracao/blowfish/pull/1216
