### ISSUE TITLE
❓ Featured images for different languages or in frontmatter

### ISSUE THREAD

**Issue by etoosamoe** [nunocoracao/blowfish#1215]
**Is your feature request related to a problem? Please describe.**
Hi! It works great when you create file index.en.md with post's text - it shows for specified language. But I haven't found any way to use different featured image for different languages.

**Describe the solution you'd like**
By default use `*feature*` image name mask, as usual. If there is `.en.` or `.<langcode>.` in the file name - use it only for specified language. 

**Describe alternatives you've considered**
As alternative you should be able to set featured image path in a frontmatter, e.g. `featured_image: different_image.jpg`

✌️

**Comment by nunocoracao** [comment]
@etoosamoe check the PR tagged in this post. It should solve your issue
