### ISSUE TITLE
Add details to docs on [i18n] Authors bio - link to Hugo docs

### ISSUE THREAD

**Issue by Zer0xxxx** [nunocoracao/blowfish#123]
Firstly, amazing thanks and congrats for making Blowfish so amazing! I'm loving it. ❤️

**Is your feature request related to a problem? Please describe.**
Hello there!
Blowfish's documentation is stunning, it's one of the best documentations I ever seen.
But I think it's whether lacking some informations, whether Blowfish lacks a little feature implementation.

On the Multi-Authors documentation page, there is no mention about the i18n for authors profiles.
https://nunocoracao.github.io/blowfish/docs/multi-author/#create-the-authors-taxonomy

(See the starting by `Lastly, you can add more detail to each author page so that it displays a little bio, links, or whatever information fits your use-case.` paragraph. 😉)

**Describe the solution you'd like**
I would like to have the same i18n behaviour and standards as usual (`_index.fr.md`, `_index.en.md`, maybe?).
*:warning: EDIT: Unless there is already a way to do it with Hugo's built-in standards.*

Warm regards!

**Comment by nunocoracao** [comment]
@Zer0xxxx thanks for the feedback. One question, isn't that already provided as part of Hugo standard behavior? As in, are you suggesting implementing this in the theme, or just mentioning how to do it in the docs?

**Comment by Zer0xxxx** [comment]
@nunocoracao Thank you for your quick answer!
It is effectively two separated things and ideas.

I think it would be a good start to firstly document it (with an hyperlink to the Hugo's official documentation if possible, on-site otherwise). :smile:

I don't think it would be a good idea to disrupt Hugo's standards if it is not required for the i18n implementation here. It would be more like a very bad idea than a killer feature, imo. ^^'

**Comment by nunocoracao** [comment]
@Zer0xxxx agree, need to dig that out first

**Comment by Zer0xxxx** [comment]
'k, I'm idiot.
It's dead simple: `_index.md` => default language
`_index.en.md` => English
Etc.

Useless issue, sorry!

**Comment by nunocoracao** [comment]
closing this because it's part of the Hugo documentation
