### ISSUE TITLE
🐛 Code copy doesn't work with gist

### ISSUE THREAD

**Issue by aakashnand** [nunocoracao/blowfish#1236]
**Describe the bug**
When I enabled `enableCodeCopy = true` in `params.toml`. It shows a copy button in all code blocks. 

Surprisingly the copy button is also displayed in the gist like below:

![image](https://github.com/nunocoracao/blowfish/assets/14219201/ebc4def1-afb9-4830-b56e-6a3044a81397)

but this copy button doesn't work. I tested that the copy button works for code blocks

**To Reproduce**
1. Set `enabledCodeCopy=true` in `params.toml`
2. Add gist shortcode
3. Click `Copy` button in gist

**Expected behavior**
Copy button should also work for gist

**Screenshots**
Attached above

**Hugo & Blowfish versions**
Hugo version:  `v0.122.0`
Blowfish version: `v2.55.0`

**Additional context**
NA

**Comment by nunocoracao** [comment]
@aakashnand you are right, the copy button shouldn't appear in the gist shortcode

**Comment by aakashnand** [comment]
@nunocoracao would it be possible to make it work for gist as well?
