### ISSUE TITLE
Carousel doesn't work for local images

### ISSUE THREAD

**Issue by SmileGuide** [nunocoracao/blowfish#1245]
![image](https://github.com/nunocoracao/blowfish/assets/73018805/17367b42-f059-4668-8681-3dcab3c78c05)

**Describe the bug**
After v2.55.0, external URLs for carousel work but local URLs seem to cause an error.

I use carousel inside my custom shortcode whose inner text needs to be markdownfied, so I remove the extra spaces in my `carousel.html`.

I thought the error was caused by my changes, however, when I reverted back, the same error was still there.

**Comment by nunocoracao** [comment]
I see... sorry. Will have a look ASAP
