### ISSUE TITLE
taxonomies.toml - configs and docs improvements

### ISSUE THREAD

**Issue by Zer0xxxx** [nunocoracao/blowfish#126]
**Describe the bug**
Since the commit https://github.com/nunocoracao/blowfish/commit/dffaab83fd47e1df9c73d787be9353f247d91f90, I have trouble with the `hugo server` command, using _Blowfish_
> hugo server --ignoreCache

> Start building sites … 
hugo v0.104.3-58b824581360148f2d91f5cc83f69bd22c1aa331+extended linux/amd64 BuildDate=2022-10-04T14:25:23Z VendorInfo=snap:0.104.3
ERROR 2022/10/16 18:32:57 render of "term" failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/nunocoracao/blowfish@v1.9.0/layouts/_default/term.html:16:14": execute of template failed: template: _default/term.html:16:14: executing "main" at <.Paginate>: error calling Paginate: cannot convert type page.PagesGroup to Pages
ERROR 2022/10/16 18:32:57 render of "term" failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/nunocoracao/blowfish@v1.9.0/layouts/_default/term.html:16:14": execute of template failed: template: _default/term.html:16:14: executing "main" at <.Paginate>: error calling Paginate: cannot convert type page.PagesGroup to Pages
ERROR 2022/10/16 18:32:57 render of "term" failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/nunocoracao/blowfish@v1.9.0/layouts/_default/term.html:16:14": execute of template failed: template: _default/term.html:16:14: executing "main" at <.Paginate>: error calling Paginate: cannot convert type page.PagesGroup to Pages
Error: Error building site: failed to render pages: render of "term" failed: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/nunocoracao/blowfish@v1.9.0/layouts/_default/term.html:16:14": execute of template failed: template: _default/term.html:16:14: executing "main" at <.Paginate>: error calling Paginate: cannot convert type page.PagesGroup to Pages
Built in 56 ms

**To Reproduce**
I dunno, sorry.
I will try to git checkout and see if it is really related to the mentioned commit.
I can provide you a sample of my Hugo Blog (not pushed on GitHub yet), if you want to review it.

**Desktop (please complete the following information):**
 - OS: Manjaro

**Hugo & Blowfish versions**
- Blowfish: 2.0.0
- Hugo: hugo v0.104.3-58b824581360148f2d91f5cc83f69bd22c1aa331+extended linux/amd64 BuildDate=2022-10-04T14:25:23Z VendorInfo=snap:0.104.3
- Golang: go version go1.19.2 linux/amd64

**Comment by nunocoracao** [comment]
Hey @Zer0xxxx happy to help. I just updated my personal blog to v2 without any issues. If you have a repo send it over so that I can have a look. btw, from the logs seems that you are using v1.9.0 not v2

**Comment by Zer0xxxx** [comment]
You're right. And the issue isn't related to Blowfish 2.0.0
I found what is causing this issue.

In `./config/_default/taxonomies.toml`:
```
# config/_default/taxonomies.toml
#=============================================================================================================================================
# * ... DOCUMENTATION
#---------------------------------------------------------------------------------------------------------------------------------------------
# TAXONOMIES            => https://gohugo.io/content-management/taxonomies/#default-taxonomies
# ARCHIVE               => https://web.archive.org/web/20221003155835/https://gohugo.io/content-management/taxonomies/#default-taxonomies
#-------------------------------------------------------------------------------------------------------------------------------------
# MULTIPLE AUTHORS      => https://nunocoracao.github.io/blowfish/docs/multi-author/
# ARCHIVE               => https://web.archive.org/web/20221016155545/https://nunocoracao.github.io/blowfish/docs/multi-author/
#=====================================================================================================================================

category = "categories"
tag = "tags"
author = "authors"
```

This is the line `author = "authors"` which is causing the issue.
As soon as I remove this line, it compiles and run again.

Do you think it is a bug?
Even if it is documented to append this line in `./config/_default/config.toml`, I found it would be more idiomatic to set this value in `./config/_default/taxonomies.toml`, also because it is a filepath which is documented in the Blowfish's doc.

Now I know how to quickfix it.

Hope this was, somehow, useful.

**Comment by Zer0xxxx** [comment]
Just edited my comment (added two _anchor links_ to help).
Regards.

**Comment by nunocoracao** [comment]
Thanks @Zer0xxxx

**Comment by Zer0xxxx** [comment]
Do you think you can/will make it possible to put this line in the `taxonomies.toml` file without break Hugo's standards, one day?
I would be glad to see a little comment with the commit ID of this bugfix if you do it one of these days. :smile:

**Comment by nunocoracao** [comment]
Not really. That part is Hugo stuff aka low-level from a theme perspective. If you read through Hugo's docs there's way more that you can do with Blowfish that what the theme's docs describe. I've changed the title and I will consider clarifying the docs at least.

**Comment by nunocoracao** [comment]
closing for now
