### ISSUE TITLE
Error when deploying multilingual sites to Netlify

### ISSUE THREAD

**Issue by camartinezbu** [nunocoracao/blowfish#1272]
**Describe the bug**
I'm migrating my personal blog to Hugo and the Blowfish theme, in part because of its multilingual capabilities, as I want to have a version of the site both in english and in spanish. When deploying the site from my repository to Netlify, however, It gives me the following message: 

`Error: error building site: render: render of "sitemap" failed: "/opt/build/repo/themes/blowfish/layouts/_default/sitemap.xml:13:28": execute of template failed: template: _default/sitemap.xml:13:28: executing "_default/sitemap.xml" at <.Language.LanguageCode>: can"t evaluate field LanguageCode in type *langs.Language`

I started investigating and found issue #1139 where the same problem is discussed. As mentioned by the repository's owner in this [comment](https://github.com/nunocoracao/blowfish/issues/1139#issuecomment-1877894938) I checked out the Blowish-lite example site and tried deploying it into Netlify. Here's the [repository](https://github.com/camartinezbu/test_blowfish) from which I created it. I replicated the project structure with a folder with the name of each language containing the corresponding folders and `index.md` files. 

This first implementation failed to deploy, giving me a very similar message as the one mentioned above. I realized that the config files in the Blowfish lite repository and the default theme files are slightly different. This may be due to different Hugo versions, but I left the default theme ones for this first test. 

After that I tried two different variations. First, I changed the config files to resemble more closely the ones in the Blowfish Lite example as you can see in this [commit](https://github.com/camartinezbu/test_blowfish/commit/035f05fe4dbdc6a13622cdf205fff1031cc82986). This also gave me an error in Netlify, with the following logs.

After that, I reverted the config changes and upgraded Hugo's version in the `netlify.toml` file, as suggested by the repository's owner in this [commit](https://github.com/camartinezbu/test_blowfish/commit/81c744a7fdf435da77ae5ffe1b41c2b661389a2b). However, this also gave me an error, with some additional warning messages regarding the compatibility with Hugo's version.

**To Reproduce**
1. Create a site and install Blowfish using  git submodules.
2. Add `netlify.toml` file as described in the theme's documentation.
3. Add multilingual config, menus and content pages.
4. Check error logs in netlify.

**Expected behavior**
I expected the site to build without problems, giving me the option to change language for pages and posts.

**Screenshots**
- Error log with a clean theme configuration:
![image](https://github.com/nunocoracao/blowfish/assets/47795078/056d7f36-9387-4b7f-8dfb-76aa917ff416)

- Error log, changing the config files to resemble the Blowfish Lite example:
![image](https://github.com/nunocoracao/blowfish/assets/47795078/bdb3e5c5-6088-4cbc-8b3e-86b7dd4b063e)

- Error log, when updating hugo's version:
![image](https://github.com/nunocoracao/blowfish/assets/47795078/ce9bfb37-445e-4de9-bfe8-b3afca26cc3d)

**Desktop (please complete the following information):**
 - OS: Netlify is deploying from an linux/amd64 image.
 - Browser: NA

**Hugo & Blowfish versions**
I tried hugo version 0.104 and 0.112 in the `netlify.toml` file as well as the theme's most recent version at the date of this issue.

**Additional context:**
This deployment error in Netlify doesn't occur when there are language, menus and markdown files for just one language. I have succesfully deployed my personal blog in just spanish. But when I add any of the mentioned files in english, the site fails to deploy.

**Comment by nunocoracao** [comment]
Hello @camartinezbu feel free to open a thread in discussions to see if someone can help. This is not a bug in the theme I am afraid. Here is an example of a repo with two languages maybe it could help pinpoint any problems in your configs

https://github.com/nunocoracao/blowfish_lite/
