### ISSUE TITLE
🐛 Clicking on a External URL page from search results navigates to the page and not the external URL.

### ISSUE THREAD

**Issue by qalldredge** [nunocoracao/blowfish#1275]
**Describe the bug**
When a page for an external URL is found in the search results and clicked on, the result is it navigates to the page instead of the external URL.

**To Reproduce**
1. Create an External URL page
2. Use the search to find it.
3. Click on it
4. See that is goes to the page and not the external URL

**Expected behavior**
It should navigate to the external URL the same way it does when clicked on from a list.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 122.0.6261.69 (Official Build) (64-bit)

**Hugo & Blowfish versions**
Which version of Hugo and Blowfish are you using?
Hugo 0.119

**Additional context**

**Comment by nunocoracao** [comment]
Thanks @qalldredge
