### ISSUE TITLE
Site builds with Hugo 122 but not 123 on blowfish v2.59.0

### ISSUE THREAD

**Issue by i0day** [nunocoracao/blowfish#1282]
**Describe the bug**

Site builds with Hugo 122 but not 123 on blowfish v2.59.0

**To Reproduce**

 After updated blowfish to v2.59 and updated hugo to v0.123.6

**Expected behavior**

run hugo should build the site, hugo server should be working

**Error message**
```bash
Start building sites …
hugo v0.123.6-92684f9a26838a46d1a81e3c250fef5207bcb735+extended linux/amd64 BuildDate=2024-02-28T18:29:40Z VendorInfo=gohugoio

Built in 280 ms
Error: error building site: render: failed to render pages: render of "section" failed: "/home/james/quickstart/layouts/_default/list.html:20:7": execute of template failed: template: _default/list.html:20:7: executing "main" – File is nil; wrap it in if or with: {{ with partial "article-meta/list.html" (dict "context" . "scope" "single")>: error calling partial: "/home/james/quickstart/layouts/partials/article-meta/list.html:17:32": execute of template failed: template: partials/article-meta/list.html:17:32: executing "partials/article-meta/list.html" at <partial "meta/views.html" .>: error calling partial: "/home/james/quickstart/layouts/partials/meta/views.html:7:28": execute of template failed: template: partials/meta/views.html:7:28: executing "partials/meta/views.html" at <.File }}{{ .Path }}{{ end }}
```

**Desktop (please complete the following information):**
 - OS: linux
 - Browser : chrome

**Hugo & Blowfish versions**
all blowfish theme version including latest, hugo version 123 or later

**Additional context**
See this bug on hugo page https://github.com/gohugoio/hugo/issues/12176

Whether this is a bug or enhancement is unclear.

Example:

{{ where site.Pages "File.BaseFileName" "p1" }}

With v0.122.0 and earlier:

    WARN .File.BaseFileName on zero object. Wrap it in if or with: {{ with .File }}{{ .BaseFileName }}{{ end }}

With v0.123.0 and later:

    ERROR Rebuild failed: render: failed to render pages: render of "home" failed: "/home/user/project/layouts/_default/home.html:12:5": execute of template failed – Pages "File is nil; wrap it in if or with: {{ with where site.Pages "File }}{{ .where }}{{ end }}

It is obvious to me that site and theme authors have been ignoring the warnings for years, so I am not terribly sympathetic to their current woes. Having said, it may be in our best interest to warn instead of error; I have seen 4 or 5 cases in the last couple of weeks, each one generating noise either here or on the forum.

Note that this issue is about File.Anything, not just File.BaseFileName.

References:

    https://discourse.gohugo.io/t/48497
    https://discourse.gohugo.io/t/48576

**Comment by nunocoracao** [comment]
That file is a override on the theme right?

**Comment by i0day** [comment]
I copied views.html from the most recent theme but views.html from version from 2-3 month ago is having the same code for .File that has not changed

**Comment by i0day** [comment]
I basically just modify the .File.Path according to this https://discourse.gohugo.io/t/path-when-the-page-is-backed-by-a-file-is-deprecated-and-will-be-removed/42239
Here is the modified views.html
```html
<span>
    {{ if eq .Kind "taxonomy"}}
    <span id="views_taxonomy_{{ .Page.Data.Plural }}"
    {{ else if eq .Kind "term"}}
    <span id="views_term_{{ .Page.Data.Term }}"
    {{ else }}
    {{ $path := "" }}
    {{ with .File }}
    {{ $path = .Path }}
    {{ else }}
    {{ $path = .Path }}
    {{ end }}
    <span id="views_{{ $path }}"
    {{ end }}
        class="animate-pulse inline-block text-transparent max-h-3 rounded-full mt-[-2px] align-middle bg-neutral-300 dark:bg-neutral-400" title="views">loading</span>
    <span class="inline-block align-text-bottom">{{ partial "icon.html" "eye" }}</span>
</span>
{{- /* Trim EOF */ -}}
```
Here is the modified likes.html
```html
<span>
    {{ if eq .Kind "taxonomy"}}
    <span id="likes_taxonomy_{{ .Page.Data.Plural }}"
    {{ else if eq .Kind "term"}}
    <span id="likes_term_{{ .Page.Data.Term }}"
    {{ else }}
    {{ $path := "" }}
    {{ with .File }}
    {{ $path = .Path }}
    {{ else }}
    {{ $path = .Path }}
    {{ end }}
    <span id="likes_{{ $path }}"
    {{ end }}
        class="animate-pulse inline-block text-transparent max-h-3 rounded-full mt-[-2px] align-middle bg-neutral-300 dark:bg-neutral-400" title="likes">loading</span>
    <span class="inline-block align-text-bottom">{{ partial "icon.html" "heart" }}</span>
</span>
{{- /* Trim EOF */ -}}
```
