### ISSUE TITLE
🐛 Series does not show any list

### ISSUE THREAD

**Issue by mattklapman** [nunocoracao/blowfish#1283]
The series feature generates properly and shows up in a post, but the drop down no longer works.

see https://blog.jrlabs.io/posts/2024-02-26-pointer-chasing-and-the-boundary-of-a-host/ for an example of the failure.

This is with Blowfish v2.59.0 on Hugo v0.123.6. It was working on earlier releases this month.

**Comment by nunocoracao** [comment]
Thanks for bringing this up @mattklapman is there any way I can check the code for that page? Series seems to be working on Blowfish's website so I wanted to debug locally

**Comment by mattklapman** [comment]
as of today, series is working correctly when hugo is run on a Fedora 39
system. I have not checked if macOS brew version is still broken.

**Comment by ennnbeee** [comment]
Same issue here, series works with a value without spaces, as soon as you put in a space it stops poulating.

**Comment by nunocoracao** [comment]
@ennnbeee please provide the markdown corresponding to both images I am not able to reproduce this bug

**Comment by ennnbeee** [comment]
Not working with spaces in the `series`:

```
---
title: "Risk Based Windows 11 Feature Update Deployment - Device Attributes"
date: 2024-03-07T10:11:03Z
draft: true
description: "Deploying Windows 11 23H2 feature updates using Microsoft Intune using Dynamic Device Groups in Entra ID and Feature Update Readiness reports to tag devices based on risk."
summary: "Having captured the Feature Update Readiness data for Windows 11 23H2, we can now use this risk based data to tag devices with their associated risk, grouping them together to allow for Feature Update profile assignment."
showDate: true
authors:
  - "ennbee"
tags: ["intune", "windows", "updates", "groups", "powershell", "graph"]
series: ["Risk Based Windows 11 Feature Update Deployment"]
series_order: 2
---
```

Working with no spaces in the `series`:

```
---
title: "Risk Based Windows 11 Feature Update Deployment - Device Attributes"
date: 2024-03-07T10:11:03Z
draft: true
description: "Deploying Windows 11 23H2 feature updates using Microsoft Intune using Dynamic Device Groups in Entra ID and Feature Update Readiness reports to tag devices based on risk."
summary: "Having captured the Feature Update Readiness data for Windows 11 23H2, we can now use this risk based data to tag devices with their associated risk, grouping them together to allow for Feature Update profile assignment."
showDate: true
authors:
  - "ennbee"
tags: ["intune", "windows", "updates", "groups", "powershell", "graph"]
series: ["RiskBasedWindows11FeatureUpdateDeployment"]
series_order: 2
---
```

**Comment by ennnbeee** [comment]
Just to add, the same markdown works on a macOS device, just Windows having issues. I wonder if this is down to the the series partials, with them doing a replace with '-' ?

**Comment by nunocoracao** [comment]
Thanks @ennnbeee that comment is gold - meaning I won't be able to reproduce/fix the bug then :D 
I will have a look but probably will need someone with Windows to help me.

**Comment by eplots** [comment]
Can add that on Linux, only one of the series need a '-' to get it all together:

```
series:
  - "Lorem-ipsum"
series_order: 1
```
```
series:
  - "Lorem ipsum"
series_order: 2
```

Gives a result of, on the page with order 1 (showing a '-'):
![image](https://github.com/nunocoracao/blowfish/assets/93516089/72777cf9-3627-4d9d-a97a-42e9b3ae665d)

On the page with order 2, it shows without '-':
![image](https://github.com/nunocoracao/blowfish/assets/93516089/b4d74f5e-e382-478f-893b-a3ee91d3827e)

The series page shows it with a '-'.

**Comment by ennnbeee** [comment]
> Thanks @ennnbeee that comment is gold - meaning I won't be able to reproduce/fix the bug then :D I will have a look but probably will need someone with Windows to help me.

Same issue on macOS annoyingly

I can fix it by changing line 9 in the series.html partial from `{{ $seriesNameURL := strings.Replace $seriesName " " "-" }}` to `{{ $seriesNameURL := $seriesName  }}`.

For some reason the transform to replace spaces with hypens seems to break things.

**Comment by nunocoracao** [comment]
I followed @ennnbeee and it seems to work and avoid whitespace issues across OS. merge incoming
