### ISSUE TITLE
❓ Blowfish.page cripplingly slow on Firefox

### ISSUE THREAD

**Issue by Ast3risk-ops** [nunocoracao/blowfish#1326]
**Describe the bug**

https://blowfish.page, due to the already slow site combined with too much animated content causes the site to be really slow and certain pages to be inaccessible on Firefox.

**To Reproduce**
1. open https://blowfish.page on Firefox 123
2. oh dear lord it's so slow

**Expected behavior**

Responsive site with all pages accessible

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux (tried Mac too)
 - Browser Firefox
 - Version 123

**Hugo & Blowfish versions**
Not important

**Additional context**
The shortcodes page especially will not load at all due to the slowness.

**Comment by nunocoracao** [comment]
Hello @Ast3risk-ops could you please check with other browsers
- Chrome
- Arc
- Safari
- etc

**Comment by nunocoracao** [comment]
> Can confirm, the page's background being ~1 FPS on my laptop, on Firefox Linux 123.0.1.
> 
> It is also slow on Android (Mull browser, fork of a fork of Firefox Android).
> 
> Chrome Android / Chromium Linux does not have such issue.
> 
> Uploading vid.mp4…
> 
> EDIT:
> 
> Here is the video uploaded corretly: https://github.com/nunocoracao/blowfish/assets/68757440/de2e29f4-1e2f-4a69-bf19-76e30554f523

Thanks @Guanran928 I'll leave this open to gather more feedback. At this stage this doesn't seem like a theme problem more a firefox problem on how to render SVGs. Could still implement custom logic for Firefox for the time being but not sure what would be the effort there...

**Comment by Ast3risk-ops** [comment]
> Hello @Ast3risk-ops could you please check with other browsers
> 
>     * Chrome
> 
>     * Arc
> 
>     * Safari
> 
>     * etc
> 
> 
> FYI - this is not a bug, the theme works well depending on the configuration, even on Firefox (try [nunocoracao.github.io/blowfish_lite](https://nunocoracao.github.io/blowfish_lite/)). The fact that the current theme website is slow is just regarding its content and the browsers it's running on (no problems on arc/chrome/safari on my side) not any code optimization that needs to be done.

Checked with ungoogled chromium (which is chrome, arc, etc except safari)

**Comment by SebastianErfort** [comment]
Hi there, I can confirm the animated background takes up a lot of resources. On my ~5y old laptop (i5 CPU, 8GB RAM), running OpenSUSE and Chromium browser (should be close to Chrome in performance), I see 1 core at 80-90%. The moment I hide the background SVG through page source tools (not sure about the terminology, F12 shortcut in most browsers), my CPU and fan relax to normal levels.

**Comment by BabaRagnarok** [comment]
I have the same problem with chrome. Especially pages with more content

**Comment by nunocoracao** [comment]
May I ask you all to test if this is because of the SVGs or something else?

**Comment by nunocoracao** [comment]
@BabaRagnarok @SebastianErfort @Ast3risk-ops @Guanran928 could you please check if the version here
https://blowfish-21fff--preview-1334-sk3p6tik.web.app
is any better?

**Comment by Ast3risk-ops** [comment]
> @BabaRagnarok @SebastianErfort @Ast3risk-ops @Guanran928 could you please check if the version here [blowfish-21fff--preview-1334-sk3p6tik.web.app](https://blowfish-21fff--preview-1334-sk3p6tik.web.app) is any better?

Yes, it's a lot better, the site is much more usable now.

**Comment by BabaRagnarok** [comment]
The problem as far as I'm concerned was on the shortcodes page. Now it's better

**Comment by nunocoracao** [comment]
awesome, will update on the next release
