### ISSUE TITLE
🐛 Tailwind Colors are not updating with colorScheme

### ISSUE THREAD

**Issue by arahmitz** [nunocoracao/blowfish#1329]
**Describe the bug**
When using `colorScheme`, it seems like the Tailwind colors aren't getting updated - every interaction and tailwind-controlled color defaults to default blowfish (blue) colors.

**To Reproduce**
1. Setup a new hugo site with blowfish installed
2. Change `colorScheme` in `config/_default/params.toml` from "blowfish" to any other
3. Build the page

**Expected behavior**
When changing colorScheme, the additional TailwindCSS colors should update all interactions and shortcode-controlled elements to the specific theme - in case of avocado - green, fire - red, princess - pink, etc.

**Screenshots**
![Princess main layout](https://github.com/nunocoracao/blowfish/assets/34507800/daf6a0c5-3fd8-457a-8679-6fc2f538201f "Princess theme with blue controls")

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 122.0.6261.118

**Hugo & Blowfish versions**
Which version of Hugo and Blowfish are you using?
hugo v0.123.8
blowfish 2.61.1

**Comment by nunocoracao** [comment]
Thanks, @arahmitz do you have a before/after picture to show?

**Comment by nunocoracao** [comment]
will have a look thanks this is helpful

**Comment by nunocoracao** [comment]
@arahmitz fixed in https://github.com/nunocoracao/blowfish/releases/tag/v2.61.1
Sorry I introduced the bug in the latest release, damn those dependencies.

**Comment by m27387** [comment]
Hi,

**Describe the bug**
This bug happened to me when I deployed to the GitHub Pages. I am using version 2.65.0 of your masterpiece. I have no trouble when testing locally on my laptop. However, the colorScheme was set back to the default value, blowfish.

**Desktop (please complete the following information):**
- OS: macOS Sonoma 14.4.1
- Browser: Firefox Developer Edition
- Version: 126.0b6

**Hugo & Blowfish versions**
- hugo: v0.125.0+extended darwin/amd64 BuildDate=2024-04-16T15:04:41Z VendorInfo=brew
- blowfish 2.65.0

Currently, I manually copy the partial/head.html file in the theme to my content directory and overwrite the conditional statement to the colorScheme I want. It works💡

Thank you for your codes👏🙏
