### ISSUE TITLE
pagespeed

### ISSUE THREAD

**Issue by 0r1ks** [nunocoracao/blowfish#1332]
**Describe the bug**
How can i upgrade my pagespeed?
![image](https://github.com/nunocoracao/blowfish/assets/99347708/714ea9f1-b15c-43af-b2e4-6fa72a20d2f3)

**To Reproduce**
1. Go to 'https://pagespeed.web.dev/analysis/https-or1k-net/60pcpc39iw?form_factor=mobile'
2. Scroll down to '....'
3. See errors

**Expected behavior**
90-100% pagespeed needed

**Hugo & Blowfish versions**
Latest on 12.March.2024

**Comment by nunocoracao** [comment]
Sorry @0r1ks this is not an issue. Feel free to open a discussion to see if anyone can help. This is not a theme problem and site optimization can vary depending on the content you use. 

Blowfish can provide 100% on all of that... https://pagespeed.web.dev/analysis/https-nunocoracao-github-io-blowfish_lite/tccidjnsmt?form_factor=mobile
