### ISSUE TITLE
thumbnails not rendered when multilingual content in same folder

### ISSUE THREAD

**Issue by undertherain** [nunocoracao/blowfish#1346]
**Describe the bug**

When content in different languages is placed in the same folder, for one of the languages the thumbnails are not rendered.

In Blowfish documentation and samples it is assumed content for different languages is placed in different sub-folders. However, when most of the pages and  posts come translated in several languages, duplicated assets like feature* - files does not make much sense. Hugo itself allows separating languages by filename, say, index.en.md  - and it works fine with blowfish for blog posts which do have all languages. 
However for posts or pages which for various reasons come only in one language - the post in other language is generated, but thumbnails are not. 

**To Reproduce**
Disable contentDir in config, add a blog post for one langauge only, using language code in filename to distinguish between languages.

**Expected behavior**
Well, expect of course to see thumbnails for all languages for which index files exist.

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Browser Firefox
 - Version 124.0

(well files are not in public folder, so it clearly doesn't have to do with FF :)

**Hugo & Blowfish versions**
Hugo v0.124.0 , Blowfish  2.61.1

**Comment by undertherain** [comment]
not 100% sure if it has to do with the theme though, or with Hugo itself...

**Comment by undertherain** [comment]
Yep, it might be a Hugo issue

https://discourse.gohugo.io/t/issue-with-images-in-a-multilingual-multihost-configuration/48501

**Comment by nunocoracao** [comment]
there's a group of us working on translating the site and we kind are doing that with no issues
https://github.com/nunocoracao/blowfish/pull/1324

**Comment by nunocoracao** [comment]
Closing this one. If there is an issue it doesn't seem to be theme related. Also in the above PR there is a working preview of multiple languages with single templates.
