### ISSUE TITLE
Views and likes count always be 0

### ISSUE THREAD

**Issue by yuntan** [nunocoracao/blowfish#1369]
**Describe the bug**
Views and likes count is 0 for all pages, thought the Firebase Database stores actual count.

**To Reproduce**
Enable `article.showViews` and `article.showLikes` in `config/_default/params.toml`.

**Expected behavior**
Views and likes count reflect Firestore Database.

**Screenshots**
| Firestore Database | Rendered page |
| -- | -- |
| ![image](https://github.com/nunocoracao/blowfish/assets/574575/e294db25-b09a-4cac-8edd-f653f6739f0d) | ![image](https://github.com/nunocoracao/blowfish/assets/574575/886efab8-1fee-4fbc-bc96-cbcc3f81b892) |

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Browser: Arc
 - Version: 1.35.0

**Hugo & Blowfish versions**
Hugo: v0.124.1
Blowfish: dev (https://github.com/nunocoracao/blowfish/commit/bafc42f58733466e1874144a8593f5bde208c227)

**Additional context**
In screenshot above, Firebase Database ID and HTML element ID is different.

**Comment by nunocoracao** [comment]
What are your authentication settings and database rules on firebase?

**Comment by yuntan** [comment]
No error found on the browser console.

Firebase console:

![image](https://github.com/nunocoracao/blowfish/assets/574575/d92bf28b-c4da-46b7-a39a-4d90d2abf902)

Login provider: anonymous

![image](https://github.com/nunocoracao/blowfish/assets/574575/b82016c3-5fd3-4bd7-8db1-0efa1ef1c276)

**Comment by nunocoracao** [comment]
That's because of the fix you tried to pull to dev - i imagine you are using that override in your installation right?

AKA you are righting the variable to a place and reading it from another - that's why it's always zero - and why I rejected the PR. Use the main release and it should work.

**Comment by yuntan** [comment]
> That's because of the fix you tried to pull to dev - i imagine you are using that override in your installation right?

Yes.

Thank you for pointing this out.
