### ISSUE TITLE
2.63.0 broke series partial - series.html not found

### ISSUE THREAD

**Issue by arahmitz** [nunocoracao/blowfish#1384]
**Describe the bug**
After updating to 2.63.0, I can't build the page on local host (using `hugo server` command) as the builder shows an error of missing series.html

```
Error: error building site: render: failed to render pages: render of "page" failed: "C:\Users\Adam\documents\adamblogstuff\layouts\_default\single.html:78:11": execute of template failed: template: _default/single.html:78:11: executing "main" at <partial "series.html" .>: error calling partial: partial "series.html" not found
PS C:\Users\Adam\documents\adamblogstuff> hugo server
Watching for changes in C:\Users\Adam\documents\adamblogstuff\{archetypes,assets,content,layouts,static,themes}
Watching for config changes in C:\Users\Adam\documents\adamblogstuff\hugo.toml, C:\Users\Adam\documents\adamblogstuff\config\_default, C:\Users\Adam\documents\adamblogstuff\themes\blowfish\config.toml, C:\Users\Adam\documents\adamblogstuff\themes\blowfish\config\_default
Start building sites …
hugo v0.123.8-5fed9c591b694f314e5939548e11cc3dcb79a79c+extended windows/amd64 BuildDate=2024-03-07T13:14:42Z VendorInfo=gohugoio

ERROR render of "page" failed: "C:\Users\Adam\documents\adamblogstuff\layouts\_default\single.html:78:11": execute of template failed: template: _default/single.html:78:11: executing "main" at <partial "series.html" .>: error calling partial: partial "series.html" not found
Built in 215 ms
Error: error building site: render: failed to render pages: render of "page" failed: "C:\Users\Adam\documents\adamblogstuff\layouts\_default\single.html:78:11": execute of template failed: template: _default/single.html:78:11: executing "main" at <partial "series.html" .>: error calling partial: partial "series.html" not found
```

**To Reproduce**
1. Update project to 2.63.0
2. Build the website using `hugo server`
3. See the error I've posted in code block

**Expected behavior**
Page should work correctly with series working.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 15823.11.0

**Hugo & Blowfish versions**
Hugo: v0.123.8
Blowfish: 2.63.0

**Additional context**
I've noticed that series stopped working pre-update - they were linked correctly in the Front Matter, but weren't linking on the page - you can see that they are blank on https://adammadej.com/posts/20240316-squashstretch/

**Comment by nunocoracao** [comment]
The logs show that you are using custom layouts in your site. Using custom layouts is something that I do not control and can't fix. If you choose to do so and something breaks you need to debug your custom code overriding the theme files. 

Also I deploy 6 websites with each new release and at least half of them have series - nothing is broken that I can reproduce with the information above.

Closing
