### ISSUE TITLE
🐛 problems with building the site

### ISSUE THREAD

**Issue by cauliyang** [nunocoracao/blowfish#1395]
**Describe the bug**
Unable to render the site

**To Reproduce**

update to the latest release
run Hugo server

will get: 
```
ERROR render of "section" failed: "blowfish/layouts/_default/list.html:20:7": execute of template failed: template: _default/list.html:20:7: executing "main" at <partial "article-meta/list.html" (dict "context" . "scope" "single")>: error calling partial: "themes/blowfish/layouts/partials/article-meta/list.html:17:32": execute of template failed: template: partials/article-meta/list.html:17:32: executing "partials/article-meta/list.html" at <partial "meta/views.html" .>: error calling partial: "themes/blowfish/layouts/partials/meta/views.html:7:25": execute of template failed: template: partials/meta/views.html:7:25: executing "partials/meta/views.html" at <.File.Path>: error calling Path: runtime error: invalid memory address or nil pointer dereference
Built in 348 ms
Error: error building site: render: failed to render pages: render of "section" failed: "themes/blowfish/layouts/_default/list.html:20:7": execute of template failed: template: _default/list.html:20:7: executing "main" – File is nil; wrap it in if or with: {{ with partial "article-meta/list.html" (dict "context" . "scope" "single")>: error calling partial: "blowfish/layouts/partials/article-meta/list.html:17:32": execute of template failed: template: partials/article-meta/list.html:17:32: executing "partials/article-meta/list.html" at <partial "meta/views.html" .>: error calling partial: "/blowfish/layouts/partials/meta/views.html:7:25": execute of template failed: template: partials/meta/views.html:7:25: executing "partials/meta/views.html" at <.File }}{{ .Path }}{{ end }
```

**Expected behavior**
It should render site

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: chrome, 

**Hugo & Blowfish versions**
hugo 124 
blowfish 2.63

**Additional context**

I think the issue is the same as the pr https://github.com/nunocoracao/blowfish/pull/1359/files. 

we need to change likes.html  and view.html as well. 
Thanks for your help in advance!

**Comment by nunocoracao** [comment]
@cauliyang as you can imagine I have several sites running with Blowfish using those versions that were not broken - aka the latest and greatest live version is working as well as 5 other sites I manage. 

Can you point me to the repo with your code so that I can try to reproduce this locally? 

Also, are you using any override layouts?

**Comment by cauliyang** [comment]
hi @nunocoracao, I do not have any override layout and use one customized comment layout. I already tried to comment out all its code and build the site, but I still got the error.


I think the code should be changed are https://github.com/nunocoracao/blowfish/blob/92c13bdc8514fa9e8c0238d14e9d2e71a2ebe4a5/layouts/partials/meta/likes.html#L7 

and https://github.com/nunocoracao/blowfish/blob/92c13bdc8514fa9e8c0238d14e9d2e71a2ebe4a5/layouts/partials/meta/views.html#L7

Thanks for your help!

**Comment by nunocoracao** [comment]
@cauliyang I need more details in order to reproduce this. 

> Can you point me to the repo with your code so that I can try to reproduce this locally?

**Comment by BabaRagnarok** [comment]
@cauliyang I had a similar issue yesterday. I solved it by updating the [latest version of Hugo](https://github.com/gohugoio/hugo/releases/tag/v0.124.1)

**Comment by cauliyang** [comment]
hi @BabaRagnarok, thanks for the suggestion! but I already tried the latest version of Hugo.

**Comment by cauliyang** [comment]
@nunocoracao, here is the first time of failing to build a website: https://github.com/cauliyang/cauliyang.github.io/actions/runs/8348613511/job/22850946205 

Finally, I fixed the bug by changing views.html and likes.html:  

```html 
<span>
    {{ if eq .Kind "taxonomy" }}
    <span id="views_taxonomy_{{ .Page.Data.Plural }}">
    {{ else if eq .Kind "term" }}
    <span id="views_term_{{ .Page.Data.Term }}">
    {{ else }}
        {{ $translations := .AllTranslations }}
        {{ with .File }}
            {{ $path := .Path }}
            {{range $translations}}
                {{ $lang := print "."  .Lang  ".md" }}
                {{ $path = replace $path $lang ".md" }}
            {{end}}
            <span id="views_{{ $path }}">
        {{ end }}
    {{ end }}
        class="animate-pulse inline-block text-transparent max-h-3 rounded-full mt-[-2px] align-middle bg-neutral-300 dark:bg-neutral-400" title="views">loading</span>
    <span class="inline-block align-text-bottom">{{ partial "icon.html" "eye" }}</span>
</span>
{{- /* Trim EOF */ -}}
```
and 

```html

<span>
    {{ if eq .Kind "taxonomy" }}
    <span id="likes_taxonomy_{{ .Page.Data.Plural }}">
    {{ else if eq .Kind "term" }}
    <span id="likes_term_{{ .Page.Data.Term }}">
    {{ else }}
        {{ $translations := .AllTranslations }}
        {{ with .File }} <!-- Ensure .File is not nil before accessing its properties -->
            {{ $path := .Path }}
            {{range $translations}}
                {{ $lang := print "."  .Lang  ".md" }}
                {{ $path = replace $path $lang ".md" }}
            {{end}}
            <span id="likes_{{ $path }}">
        {{ end }}
    {{ end }}
        class="animate-pulse inline-block text-transparent max-h-3 rounded-full mt-[-2px] align-middle bg-neutral-300 dark:bg-neutral-400" title="likes">loading</span>
    <span class="inline-block align-text-bottom">{{ partial "icon.html" "heart" }}</span>
</span>
{{- /* Trim EOF */ -}}
```

**Comment by nunocoracao** [comment]
@cauliyang I'll have a look. However, I need to be able to reproduce the bug before accepting a fix for it. Again, I'm deploying multiple sites with Blowfish and didn't run into any problems.

**Comment by cauliyang** [comment]
@nunocoracao, yep, I highly agree with you. Thanks for your help!

**Comment by nunocoracao** [comment]
Hey @cauliyang was not able to reproduce. It seems that your CI error was not on the latest version of Blowfish at the time. Still think the changes make sense so I "stole" them and included them in the dev branch. Will be available in the next release. Thanks

**Comment by cauliyang** [comment]
Hi @nunocoracao, yep the version of Blowfish in the CI error is not the latest. I update the latest version on my local device and try to fix the bug. However,   the bug still exists. I do not know what makes the issue not reproducible. But the issue was gone after I changed that. Thanks for your great help!
