### ISSUE TITLE
🐛 The rendering is misaligned when the shortcode `github` is under the `timelineItem`

### ISSUE THREAD

**Issue by eallion** [nunocoracao/blowfish#1404]
**Describe the bug**

The rendering is misaligned when the shortcode `github` is under the `timelineItem`

```
{{< timeline >}}

{{< timelineItem icon="hugo" header="Blowfish" badge="Apr 10, 2024" >}}
Hugo <code><a href="https://github.com/nunocoracao/blowfish" target="_blank" rel="noopener noreferrer">blowfish</a></code>
{{< github repo="nunocoracao/blowfish" >}}
{{< /timelineItem >}}

{{< /timeline >}}
```

**To Reproduce**
1. Add this:

```
{{< timeline >}}

{{< timelineItem icon="hugo" header="Blowfish" badge="Apr 10, 2024" >}}
Hugo <code><a href="https://github.com/nunocoracao/blowfish" target="_blank" rel="noopener noreferrer">blowfish</a></code>
{{< github repo="nunocoracao/blowfish" >}}
{{< /timelineItem >}}

{{< /timeline >}}
```

**Expected behavior**

**Screenshots**
![Snipaste_2024-04-09_23-54-19](https://github.com/nunocoracao/blowfish/assets/1698841/76fab21d-f259-403d-bde1-a45b2bc74f6a)

**Desktop (please complete the following information):**
 - OS: [Windows11]
 - Browser [Chrome]
 - Version [123.0.6312.106]

**Hugo & Blowfish versions**
All latest

**Additional context**

**Comment by nunocoracao** [comment]
This seems related to https://github.com/nunocoracao/blowfish/issues/864
I wonder if there is something weird happening within those divs. Need to investigate

**Comment by eallion** [comment]
Thanks for you attention.
And markdown cannot be parsed in `timelineItem`.

**Comment by eallion** [comment]
@nunocoracao Hi there, Maybe `flex-start` is not defined.
https://github.com/nunocoracao/blowfish/blob/main/layouts/shortcodes/timelineItem.html#L7

**Comment by eallion** [comment]
Thanks!

**Comment by wermos** [comment]
> And markdown cannot be parsed in `timelineItem`.

Was there a point in time where it used to be parsed? @eallion

From what I can see, it's possible to use `markdownify` to parse Markdown, but then you lose the ability to embed GitHub cards and the like.
