### ISSUE TITLE
Using the latest (v2.64.0) version of the Blowfish theme as a Hugo module provokes an error

### ISSUE THREAD

**Issue by Usual-Coder** [nunocoracao/blowfish#1406]
### Description
Using the Blowfish theme, following Hugo module  [instructions](https://blowfish.page/docs/installation/#install-using-hugo), fails while it was possible to use it without any trouble with previous versions.

### How to reproduce
1. Create a new site with [Hugo](https://gohugo.io/getting-started/quick-start/#create-a-site)
2. _Manually_ set Blowfish as the theme using [hugo module](https://blowfish.page/docs/installation/#install-using-hugo)
3. Start hugo server
4. (Blowfish theme) Module is downloaded but server exists with an error:
 ```shell
(...)
hugo  | go: no module dependencies to download
hugo  | hugo: downloading modules …
hugo  | go: downloading github.com/nunocoracao/blowfish/v2 v2.64.0
hugo  | go: added github.com/nunocoracao/blowfish/v2 v2.64.0
(...)
hugo  |   -v, --verbose                    verbose output
hugo  | 
hugo  | Use "hugo server [command] --help" for more information about a command.
hugo  | 
hugo  | Error: command error: failed to load modules: module "blowfish" not found in "/src/themes/blowfish"; either add it as a Hugo Module or store it in "/src/themes".: module does not exist
hugo exited with code 1
```

> **This bug doesn't affect previous versions**
>  
> Tested from versions 2.61.1 up to v2.63.0

How I checked previous versions being OK:
1. Using the same _containerized_ hugo (using docker) to get a _clean_ environment each time (and minimize the risk of local stuff -cache/whatev- being the source of this issue)
2. Replacing the required version in `go.mod` (**and nothing else** = keeping  "github.com/nunocoracao/blowfish/v2" unchanged in hugo configuration)

### Expected behavior
Create a fully functional Hugo site using Blowfish theme ... like it was possible few weeks ago using the very same instructions 🤷

### Environment
 - OS: Linux
 - Hugo: 0.124.1 (latest)
 - Blowfish theme: v2.64.0 (latest)

### Additional information
For those relying on Hugo modules to use this theme, this issue can make your CI/CD workflows (pushing to GitHub/GitLab Pages) fail with the same error, depending on how you're handling that process.

### Workaround
Pin the version to the previous one: `v2.63.0` ... while this issue is fixed or another version is pushed without provoking the same error 🤷

**Comment by nunocoracao** [comment]
Hey @Usual-Coder thanks for this. I'll have a look. I would advise against pinning the version and instead hold on updating the theme. If this gets solved quickly people will forget to unpin the version.

**Comment by nunocoracao** [comment]
Hello @Usual-Coder - fixed in https://github.com/nunocoracao/blowfish/releases/tag/v2.65.0

**Comment by Usual-Coder** [comment]
Hi @nunocoracao 

When your workflow is automated "_holding without pinning_" may not be easily achieved (or even possible) ... may I suggest to have a little faith in your users' capabilities to take a _workaround_ for what it is (something temporarily useful "_(...)while this issue is fixed or another version is pushed(...)_") = the ones bothering reading the issues will probably keep an eye on the resolution for those affecting them = temporary workarounds having the tendency to become permanent when the resolution is long overdue ... just my 2 cents 🤷😇😅

Anyway, thanks for fixing that so quickly ... the theme/time you've given to the community is greatly appreciated 🙇

**Comment by nunocoracao** [comment]
@Usual-Coder don't agree but appreciate the feedback :) 

I will try to do better...
