### ISSUE TITLE
Error installing using blowfish-tools

### ISSUE THREAD

**Issue by asspye** [nunocoracao/blowfish#1413]
Script error during installation:

Configuring Blowfishfile:///usr/local/lib/node_modules/blowfish-tools/src/flow.js:158
        await utils.run('mkdir -p ' + paths.configs, true);
                                      ^

ReferenceError: paths is not defined
    at Object.configureExisting [as action] (file:///usr/local/lib/node_modules/blowfish-tools/src/flow.js:158:39)

Node.js v20.12.0

macOS Sonoma 14.4 

Homebrew 4.2.17

**Comment by nunocoracao** [comment]
How dis you install/run the command?

**Comment by nunocoracao** [comment]
@asspye any updates?

**Comment by asspye** [comment]
Yep, adding sudo helped
