### ISSUE TITLE
✨ GitHub card auth to increase rate limit

### ISSUE THREAD

**Issue by Usual-Coder** [nunocoracao/blowfish#1417]
### Description
When using the [GitHub card](https://blowfish.page/docs/shortcodes/#github-card) _shortcode_ provided by Blowfish, Hugo fails to start.

### How to reproduce

1. Add a GitHub card _somewhere_ (multiple cards will provoke the error faster 😏)
2. Reload your page many times (aka more than 60 = like how it's done when developing / using livereload)
3. Hugo server will fail and refuse to (re)start
4. You'll get the error:
```shell
ERROR Failed to get JSON resource "https://api.github.com/repos/<NAMESPACE>/<REPO>": failed to retrieve remote file: Forbidden, body: "{\"message\":\"API rate limit exceeded for XXX.XXX.XX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\n"
```
> `NAMESPACE` and `REPO` depending on the repository you're linking
> `XXX.XXX.XX.XXX` being your IP address

### Expected behavior
Avoid Hugo failure ... aka catch that failure in the corresponding partial and provide a _fallback_ solution.

May I suggest an empty _skeleton_ ... while waiting for the API to be reachable again?! 🤷
btw, instead of being _empty_ (that could be misleading 🤔), the _skeleton_ could include a rate _warning_ to be more _useful_

Even better (that last part would obviously be a feature enhancement), provide a configuration param, so we could set a path to a specific secret file (or var ... handling both cases?! 🤔), allowing the use of tokens to avoid reaching the limit so easily 🤷

### Environment

- OS: Linux
- Hugo: 0.124.1 (latest)
- Blowfish theme: v2.65.0 (latest)

### Additional context
On GitHub, the primary [rate limit](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-unauthenticated-users) for unauthenticated requests is 60 requests per hour.

It seems that keeping multiple pages open (which is quite useful when writing with multiple languages and/or when building series, moving parts from one post to another) and **forcing the reload** (to update remote assets/data) will augment the odds of reaching the rate limit 🤔 (benefits of Hugo's caching system being -necessarily- _bypassed_ by the forced reloads)

### Workaround 😇
As proposed in the error log, you can **temporarily** (= until this issue is addressed)  **fix** your Hugo configuration with:
```toml
ignoreLogs = ['error-remote-getjson']
```
> Nothing will be displayed instead of provoking an error

**Comment by nunocoracao** [comment]
How many GitHub partials are you using?

**Comment by Usual-Coder** [comment]
Hi ... I'm just starting to write content = the problem appeared on a page I dedicate to _credits_ = GitHub cards will be reduced around 10, for now 🤷

May I say I don't think the problem is related to the amount of cards (even if it obviously augments the odds of occurrence) but to the edge case of the necessarily **forced reloads, during development**.

Btw, I'm not expecting the kind of traffic that will provoke such an error once "on production" (the website will probably not be hit that much 😏 ... and more importantly the cache would do its job).

While everything here is up to you, **after reflection, being such an edge case, I don't think it's worth the time to fix it _properly_** 🤔 I'd put that way down on your _backlog_ (= fix only if more people complain) + in the meantime **I'd go with a simple warning in your docs and the workaround evoked previously** 🤷

**Comment by nunocoracao** [comment]
Closing after reco from OP
