### ISSUE TITLE
Table of contents taking article space

### ISSUE THREAD

**Issue by NorseDreki** [nunocoracao/blowfish#1423]
**Describe the bug**
Added a sample article of mine and enabled TOC, and the TOC is taking way too much width, stealing from article's width.

**To Reproduce**
1. Go to 'https://www.norsedreki.com/posts/and_dos_binding_adapters/
2. See error

**Expected behavior**
TOC should be way narrower and allow article take its space.

**Screenshots**
<img width="1062" alt="Screenshot 2024-04-17 at 20 50 37" src="https://github.com/nunocoracao/blowfish/assets/4211172/4c389c2f-ca2a-4581-842d-8da234581262">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari, Chrome

**Additional context**
When I disable TOC in `params.toml` article looks just fine.

Also, would anyone point me to a CSS class which controls TOC width please? I'd override it as a temporary workaround.

Thanks!

**Comment by nunocoracao** [comment]
Looks good to me... Try deleting caches
![Screenshot 2024-04-19 at 12 01 22](https://github.com/nunocoracao/blowfish/assets/3803196/52d1bc89-f96c-4bf2-a7d8-c2d3f3ccef93)

**Comment by NorseDreki** [comment]
Deleting caches didn't help, the reason it looks good on your screenshot is because I've pushed a workaround where CSS classes `.min-w-0` and `.max-w-prose` are overridden to push TOC more to the right.

**Comment by nunocoracao** [comment]
Can you share your repo?

**Comment by NorseDreki** [comment]
Here it goes: https://github.com/NorseDreki/norsedreki.com/tree/blowfish_toc_width. In that branch, I've removed overridden CSS classes mentioned above.

If deployed locally, a sample post to troubleshoot TOC width would be: http://localhost:1313/posts/and_dos_binding_adapters/, although I see TOC seems too wide at each post page.
