### ISSUE TITLE
How to access article frontmatter in `extend-head.html`?

### ISSUE THREAD

**Issue by bonniss** [nunocoracao/blowfish#1425]
Given a frontmatter section:

```yaml
title: "This is a slideshow"
slideshow: true
```

How to access those attributes in `extend-head.html` to do some logic like:

```html
<script>
console.info("{{ .Params.title }}")
</script>

{{ if .Params.slideshow }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/impress.js/0.5.3/impress.min.js" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{{ end }}
```

**Comment by nunocoracao** [comment]
Hello @bonniss this a Hugo question, not Blowfish specific.
Please check Hugo's docs - https://gohugo.io/content-management/front-matter/

**Comment by bonniss** [comment]
As only [`.Site` is passed into partial `extend-head`](https://github.com/nunocoracao/blowfish/blob/f06bcb2a557cabf6071a78018304f323c71247cc/layouts/partials/head.html#L121), I believe it's not Hugo specific only.
