### ISSUE TITLE
Shortcodes in shortcode doesn't work properly

### ISSUE THREAD

**Issue by kuroyei** [nunocoracao/blowfish#1427]
For example:
```md
{{< alert >}}
{{< keyword >}} Super skill {{< /keyword >}}
{{< /alert >}}
```
Result:
![image](https://github.com/nunocoracao/blowfish/assets/81549868/b74fd7a4-3b00-425b-9f9f-0b2632cc2570)

**Comment by nunocoracao** [comment]
Hello @kuroyei it's not supposed to work.
