### ISSUE TITLE
`article.heroStyle` does not seem to be applied after upgrade

### ISSUE THREAD

**Issue by code-chimp** [nunocoracao/blowfish#143]
I recently updated from v1.5.0 to v1.9.0 and added the hero options to [my params.toml](https://github.com/code-chimp/code-chimp.github.io/blob/main/config/_default/params.toml) file.  The hero images now appear on my posts, but they seem to only render in "basic" mode regardless of what value I put for **heroStyle**. Is there possibly a different setting that I am missing after the upgrade?

I have the setting currently as "background", but the hero div has the same styles from the `basic.html` partial:
![basic_hero](https://user-images.githubusercontent.com/50490/196522455-853ddd3e-7e2c-4025-9aed-6c41c2bb143f.png)

Thank you for your time and the awesome theme!

**Comment by nunocoracao** [comment]
Hello @code-chimp sorry to hear about this. In v1.9.0 I introduce the simple hero solution for articles, v2.0.0 was the one introduced the background version. As your website is using hugo modules I think I might have messed something up on my side. Let me have a look and thanks for pointing this out.

**Comment by nunocoracao** [comment]
ok @code-chimp I think I've fixed it. I forgot to upgrade the go.mod file to v2. Hence the latest version you got was the one just before v2, which didn't include the background layout. Thanks for pointing that out. 
Fixed and I opened a PR for you with the update
https://github.com/code-chimp/code-chimp.github.io/pull/1
