### ISSUE TITLE
❓ Search question - It doesn't show indexed results.

### ISSUE THREAD

**Issue by zavocc** [nunocoracao/blowfish#1432]
**Describe the bug**
When I use the search feature which is have `enableSearch` set to `true`, it doesn't show up anything as I type despite, I have non-draft/tagged pages which search doesn't pick up anything.

**To Reproduce**
On a blowfish themed site with search enabled from scratch, use the search function to see if it shows up anything. Using hugo modules and couple of blog posts

**Expected behavior**
Shows results as I type.

**Screenshots**
![image](https://github.com/nunocoracao/blowfish/assets/119603393/e8f4dd01-c594-4325-9e8a-53765941bbd9)

**Desktop (please complete the following information):**
 - OS: Windows 11/Android
 - Browser: Edge/Firefox 
 - Version: 124.0.2478.51 (edge)

**Hugo & Blowfish versions**
Hugo version 0.125.1
Latest 2.65.0 blowfish (from hugo module)

**Additional context**
It does show errors in DevTools like
```
ncaught TypeError: Cannot read properties of undefined (reading 'search')
    at executeQuery (main.bundle.min.17ffe617e664d257760ee5f71869a6d9328d3613601c03a2eb7a194bbfb06ddc629a70f7b348e6e9446e81d0789555aebce09d27debd0329fc297601a1ee6a77.js:2:22866)
    at input.onkeyup (main.bundle.min.17ffe617e664d257760ee5f71869a6d9328d3613601c03a2eb7a194bbfb06ddc629a70f7b348e6e9446e81d0789555aebce09d27debd0329fc297601a1ee6a77.js:2:21919)
 ```
Which triggers upon searching
![image](https://github.com/nunocoracao/blowfish/assets/119603393/aa3660ab-de50-40c1-a981-dd1ef1e9aa5b)

Suggesting that the javascript module isn't properly loaded? Am I missing something?

**Comment by nunocoracao** [comment]
@zavocc search is working across multiple websites I manage so this points to a problem in the way you are configuring the website. I would suggest checking the docs for reinstalling, please check if you are introducing any overrides that change the imports, and confirm if you are properly defining the base_url parameter (locally==localhost and remotely==prod url).

**Comment by zavocc** [comment]
I just checked those three and it looks fine, had deployed this on netlify passing the "-b $URL" parameter to deploy it

Search works now upon checking! Just checked on Android chrome or edge browsers, just checking to see if it works on desktop browsers see if it's a quirk.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nunocoracao** [comment]
Awesome closing the issue then
