### ISSUE TITLE
🐛 RSS feed invalid

### ISSUE THREAD

**Issue by joseph-allen** [nunocoracao/blowfish#1433]
**Describe the bug**
Sites RSS links seem to be local, Putting https://landoftherisingmonkey.com/posts/index.xml into an RSS Validator like https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Flandoftherisingmonkey.com%2Fposts%2Findex.xml

Is not valid.

**Expected behavior**
RSS feed for blogs should be valid.

**Comment by nunocoracao** [comment]
Thanks will take a look

**Comment by nunocoracao** [comment]
same as the other one @joseph-allen it seems to be because base URL is not defined... let me know if it's not
