### ISSUE TITLE
🐛 Sitemaps generate with relative URLs in production

### ISSUE THREAD

**Issue by joseph-allen** [nunocoracao/blowfish#1438]
**Describe the bug**
Sitemaps only generate links like 
```
<url>
<loc>/tags/personal/</loc>
<lastmod>2024-04-22T00:00:00+00:00</lastmod>
</url>
```
and do not contain valid links in production, where is this set?

**Comment by joseph-allen** [comment]
You can see mine here
https://landoftherisingmonkey.com/sitemap.xml

**Comment by joseph-allen** [comment]
![Screenshot 2024-04-25 at 10 55 35 pm](https://github.com/nunocoracao/blowfish/assets/7880824/7db0ad83-d584-4087-bb5c-67dd6146cc2a)

**Comment by nunocoracao** [comment]
realted to https://github.com/nunocoracao/blowfish/issues/1438

**Comment by joseph-allen** [comment]
In the interrim, I copied the above and placed it in layouts/_default/sitemap.xml generating the static version.

Then I added my domain before each relative path, and that worked for Google.

This still requires manual updating with each change, but will work until automation is done.

Thanks!

**Comment by joseph-allen** [comment]
I found this is happening in my SEO links too.
This gave me a hunch that my locally served content was being served in production too.
Looking into this, I am using Netlify which by default for a Hugo app simply serves the built public folder.

Re-reading the Hugo docs, I should be running hugo manually to build the production version of public, which I never did. This might all be on me if you aren't able to replicate?

**Comment by nunocoracao** [comment]
@joseph-allen just double checking do you have the baseurl defined?

**Comment by nunocoracao** [comment]
I've just tested this and my sitemaps are being generated correctly I'll assume it's because you haven't set the base url
let me know otherwise

**Comment by joseph-allen** [comment]
In my `/config/_default/hugo.toml`

I had all along.
```
theme = "blowfish"
baseURL = "https://landoftherisingmonkey.com/"
defaultContentLanguage = "en"
```

Running `hugo` correctly builds in `public/sitemap.xml`

```
  <url>
    <loc>https://landoftherisingmonkey.com/posts/</loc>
    <lastmod>2024-05-05T00:00:00+00:00</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.5</priority>
  </url>
```

Deploying that same public on netlify, clearing cache from my browser I get
```
<url>
<loc>/posts/</loc>
<lastmod>2024-05-05T00:00:00+00:00</lastmod>
</url>
```

Looking at Netlify logs, Netlify rebuilds with the `hugo` command. I think that's enough to show that This may be a Netlify problem specifically. The number of pages built is far lower, with some warnings.
```
1:15:19 PM: WARN 2024/05/14 05:15:19 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

To fix, I just took out the build step and have to run the hugo command manually before I release. Though that's not ideal.

I searched specifically for Hugo + Netlify issues and found this thread.
https://discourse.gohugo.io/t/netlify-is-not-deploying-my-site-correctly-with-hugo/41169/8

I added a netlify.toml with the following:
```
[build]
 publish = "public"
 command = "hugo --gc --minify"

[context.production.environment]
 HUGO_VERSION = "0.125.0"
 HUGO_ENV = "production"
 HUGO_ENABLEGITINFO = "false"
```

Which fixed both my sitemap, RSS feed and other issues in production. Thanks @nunocoracao just failing to replicate was enough to single out netlify.
