### ISSUE TITLE
Series doesn't show up in the articles

### ISSUE THREAD

**Issue by michaeldorner** [nunocoracao/blowfish#1439]
**Describe the bug**

Series overview does not show up in the articles of the series as it does in the [related documentation](https://blowfish.page/docs/series/).

**To Reproduce**
I set up the configuration (actually, I used the default configuration)

in `params.toml`
```
[article]
  seriesOpened = true
```

in `params.toml`
```
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
```

for two articles:
```
title: 'Article 1'
series: 
    - "Series of articles"
series_order: 1
```

```
title: 'Article 2'
series: 
    - "Series of articles"
series_order: 2
```

**Expected behavior**
Just as in the documentation, there should be an overview of a list of articles belonging to the series. Unfortunately, nothing shows up (see screenshots).

**Screenshots**
How it should look like:
![Screenshot 2024-04-28 at 12 46 41](https://github.com/nunocoracao/blowfish/assets/1886360/7a86cc7b-2002-42e5-bd7f-16112096df01)

How it actually looks like:
![Screenshot 2024-04-28 at 12 47 07](https://github.com/nunocoracao/blowfish/assets/1886360/227f78dd-28ba-491e-951f-84059fb2ad6b)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: Version 17.4.1

**Hugo & Blowfish versions**

- hugo v0.125.4+extended
- blowfish v2.65.0

**Additional context**

The series is correctly generated (i.e., no errors in the log and `http://localhost:1313/series/series-of-articles` works fine). It seems it is just the boxes. 

I am quite sure the problem sits in front of the computer, but I can't figure out where I went wrong :) What am I missing?

**Comment by karosas** [comment]
+1
Same blowfish/hugo version, but on Windows 10, Chrome 124.0.6367.63

**Comment by michaeldorner** [comment]
Oh that's interesting @karosas. I have it under `/posts`

**Comment by karosas** [comment]
Continuing to screw around (I only started using/exploring this theme few hours ago).

I see that `series` partial template is used only in `/themes/blowfish/layouts/_default/single.html` template, so out of curiosity I added debug tags `<h1> {file name} </h1>` to each of those templates and it seems that while articles on root of content (e.g. `/content/article.md`) use that `single.html` template, nested articles (e.g. `content/nested/article.md`) use `/themes/blowfish/layouts/_default/list.html`? Inserting `{{ partial "series/series.html" . }}` to that template seems to fix the issue.

Whether that's a good fix - I don't know. It feels a bit weird that an article uses a layout called `list` and I'm not sure what that'd affect. Technically that partial should only render if `series` is defined on the page as bare minimum, so it shouldn't really show up in random places?

**Comment by karosas** [comment]
To not touch the theme itself, you can also instead copy `/themes/blowfish/layouts/_default/list.html` to `/layout/_default/list.html` (thus overriding that specific theme layout) and edit it there. So that later it's easier to update the theme without losing your custom modifications

**Comment by karosas** [comment]
Actual solution - if your article is named `_index.md` rename it to `index.md`.

It seems hugo internal logic is to use different template if the file is called `_index.md`. Once I renamed it to `index.md` it seemed to fix everything.

**Comment by nunocoracao** [comment]
@michaeldorner this one sees to be solved and also it doesn't seem like a bug. Closing
