### ISSUE TITLE
Warning about Blowfish being incompatible with latest version(s) of Hugo

### ISSUE THREAD

**Issue by Usual-Coder** [nunocoracao/blowfish#1446]
### Latest version(s) raises a warning
`WARN  Module "github.com/nunocoracao/blowfish/v2" is not compatible with this Hugo version: 0.87.0/0.124.1; run "hugo mod graph" for more information.`

### Reproduce
Call `hugo`

### Expected behavior
Like previously, do not raise a warning 😅

### Versions
* Hugo: **v0.125.4** (latest)
* Blowfish: **v2.66.0** (latest)

Fixing this one should probably be a _quickwin_ 🤔🤷

Thanks 🙇

**Comment by nunocoracao** [comment]
Will be fix in next release
