### ISSUE TITLE
Table of Contents not scrollable nor in sync with main section

### ISSUE THREAD

**Issue by Usual-Coder** [nunocoracao/blowfish#1455]
### Description
The _"smart Table of Contents"_ is not scrollable and not always kept in sync with the main section.

### How to reproduce
1. Browse a page with enough content to produce a _big_ ToC,
2. Or if you don't have a _very long post_, to simulate the problem, make your window a little smaller than the ToC height
3. The Table of Contents is not scrollable (you need to scroll the full page)

> https://blowfish.page/docs/configuration is a good enough example for this bug 

While -basically- you cannot _jump_ to the point you want (you'll have to scroll the full page down, until the point you're interested in), sometimes it makes it even more useless since the _smartToc_ is not in sync with the content (titles / _reachable anchors_, displayed in the main section, are not even shown in the ToC 🤷)

### Expected behavior
Scrollable ToC, really kept in sync with the content.

### _Screenshots_
As stated previously, your own website is sufficient to notice the main bug.

> Use the _dev tools_ of your preferred browser to simulate a _reasonable_ window size (like 1680x1050)

Additionally, to demonstrate the problem with _inaccessible anchors_ (while displayed in the main section, it doesn't show, aside, in the ToC), using the first post I'm working on, jump to the `#more` title/anchor : https://gitlab.pages.usualcoder.com/posts/containerizing-hugo-development/#more

> The `More...` is not showing (is not _in sync_) in the lateral ToC 🤷

### Technical context
Latest versions of everything (browsers, Hugo, Blowfish)

Thanks for considering fixing this 🙇

**Comment by nunocoracao** [comment]
Not able to reproduce... just tried with the next release of Blowfish and was not able to reproduce the problem in the Configuration page as you mentioned.

**Comment by Usual-Coder** [comment]
`More` not showing in the lateral ToC:
![Screenshot-01](https://github.com/nunocoracao/blowfish/assets/34403413/cf8684f0-5960-4286-a66c-672938fb0d02)

Obviously the anchor exists (or it wouldn't have been _reachable_ when the corresponding URL was entered) ... 
![Screenshot-02](https://github.com/nunocoracao/blowfish/assets/34403413/21af6e67-8dbd-4196-aa97-d0bd061195cb)

... but ... **since the lateral ToC is not scrollable or its _(sub)levels_ expandable ... some entries are not _accessible_** ... unless you scroll _the full page_ ... which annihilates the main purpose of the ToC 🤷

**Comment by Usual-Coder** [comment]
Btw, being Product Manager (at Docker or anywhere else), aka _"someone experienced in software development processes"_, your _temptation_ 😇 could be great to close issues as soon as possible (since it's a _KPI_ used in many places 🤐) but, **when in the _"unable to reproduce"_ situation**, giving the benefice of the doubt is probably not the worst thing to do ... at least for _a little while_ 🤷

Don't get me wrong, I don't pretend to be above making mistakes myself = determining what's a real bug is still your prerogative, of course ... but may I suggest you wait ... let's call it a "reasonable delay" to answer you ... or provide you additional information ?! Avoiding the need to create a new issue (since reopening issues doesn't seem allowed in your repository)

Just my take / 2 cents ... but hey ... as I said ... I'm a _nobody_, just the usual coder 😏

Thanks for your time and understanding 🙇
