### ISSUE TITLE
🎨 Gallery Images are not being optimized and have lower quality than originals

### ISSUE THREAD

**Issue by jcastro-design** [nunocoracao/blowfish#1459]
**Describe the bug**
I'm using the `gallery` shortcode on multiple pages in my website, and although the full images being used have good quality in their original size, when placed in a gallery they seem to be blurry and weirdly scaled. 

I have `disableImageOptimization = false` set in the config but looking at the urls for gallery images I can see they are not going through image optimization, contrary to what happens to all other images placed via the `figure` shortcode for example.

**To Reproduce**
1. Go to '`https://joaocastro.me/projects/digital-avatars-mobile-app/`' (for example);
2. Sroll down and click on any image on a gallery to zoom;
3. Right-click and open the original image in a new window to see the difference in quality;

**Expected behavior**
Ideally all images should all run through image optimization process, or even if this would to be disabled, the original image scalling in the gallery should not produce blurried and lower quality assets.

**Screenshots**
Blurry image in a gallery:
<img width="1213" alt="image" src="https://github.com/nunocoracao/blowfish/assets/84838794/ee6255ce-d7bb-460c-abc3-ab0d502b82f3">
Original image opened in a separate tab:
<img width="1214" alt="image" src="https://github.com/nunocoracao/blowfish/assets/84838794/3a83290c-7582-4fd9-b36d-d007e6e3b7d2">

**Tested locally with:**
hugo v0.125.7+extended
Blowfish v2.66.0

Am I missing something on my installation or should the `gallery` shortcode be used in other form?
Thanks in advance for any help.

**Comment by nunocoracao** [comment]
Which browser?
Please share the repo

**Comment by jcastro-design** [comment]
Thank you for your reply @nunocoracao !

This issue was currently detected on Safari 17.4 (19618.1.15.11.12). Have tested also on Firefox 125.0.3 and everything seems to be working ok (haven't been able to test on other browsers yet).

I'll be duplicating a repo to share with you here shortly, currently I'm hosting it on GitLab.

The issue can also be detected with Safari on your current demo site:
https://blowfish.page/docs/shortcodes/#gallery

Thank you again for your reply.

**Comment by nunocoracao** [comment]
Hello @jcastro-design sorry I won't have tie to look at this one any time soon. I've experienced the same problem and it seems to happen only in Safari. I do not have time to develop/maintain a browser-specific hack here.

**Comment by jcastro-design** [comment]
I understand @nunocoracao , thanks for the update. If somehow I'm able to stumble upon a possible fix I'll share it here.

**Comment by nunocoracao** [comment]
Will close the ticket since this seems to be on Safari side not the theme.

**Comment by danielskowronski** [comment]
While this is caused by quirk of Safari https://bugs.webkit.org/show_bug.cgi?id=27684, I'm not sure whether this is really a bug. It's triggered by the fact that Webkit first applies classical image scaling (width/height) and **then** performs 3D scaling (scale). 

In Blowfish, https://github.com/francoischalifour/medium-zoom is handling zooming and issue there is known for over 5 years - https://github.com/francoischalifour/medium-zoom/issues/151.

Switching to https://github.com/spinningarrow/zoom-vanilla.js fixes the issue. I had to set `disableImageZoom`, inject JS+CSS of new library and add `data-action="zoom"` into override of  `layouts/_default/_markup/render-image.html`.

@nunocoracao, would you consider changing zoom library?

**Comment by ZhenShuo2021** [comment]
@danielskowronski I have addressed this issue in #2159. Please update the theme and check if the problem persists. Thank you!

Additionally, a new option `disableImageOptimizationMD` has been added to control image optimization, with the default set to false.

**Comment by jcastro-design** [comment]
Thanks for your feedback @ZhenShuo2021 and @danielskowronski .

I've tested on a clean install of blowfish with the latest release and the issue still persists on gallery layouts.

<img width="252" alt="Image" src="https://github.com/user-attachments/assets/42e3ef7d-e9e0-4f0a-92d9-9ad174fd182f" />
