### ISSUE TITLE
defaultContentLanguage Value is set to non-en,In the en language the homepage does not display

### ISSUE THREAD

**Issue by sysiocn** [nunocoracao/blowfish#1468]
**Describe the bug**

**To Reproduce**

**Expected behavior**

1，When defaultContentLanguage is set to another language (non-en); switch to en language, the homepage content will not be displayed

**Screenshots**
![image](https://github.com/nunocoracao/blowfish/assets/169319943/4bef8b76-a77d-4b77-9cb1-a914b0ea8a60)
![image](https://github.com/nunocoracao/blowfish/assets/169319943/c7835aba-9585-4089-8318-75e8423749ca)
![image](https://github.com/nunocoracao/blowfish/assets/169319943/4b5e5eb1-f7d5-45b2-90bb-d17a8d6db307)

**Desktop (please complete the following information):**
OS：macos13.5.1
Browser：edge

**Hugo & Blowfish versions**
Which version of Hugo and Blowfish are you using?
hugo：0.125
blowfish：v2.67.0

**Additional context**

**Comment by nunocoracao** [comment]
That value is something provided by Hugo itself please check their website and documentation for further details on how to use it properly
