### ISSUE TITLE
✨ Add ability to modify article order in list page by weight

### ISSUE THREAD

**Issue by yahav2305** [nunocoracao/blowfish#1488]
**Is your feature request related to a problem? Please describe.**
I am trying to order articles in a list page in a costum order. From what I can see [here](https://github.com/nunocoracao/blowfish/blob/main/layouts/_default/list.html) the list layout sorts articles by date descending. That is problematic for me since I want my articles to be sorted in a specific order that I specify.

**Describe the solution you'd like**
I would like to be able to specify an article order method in a config file, ideally to be able to use the frontmatter property [weight](https://gohugo.io/getting-started/glossary/#weight) on each page to sort page order.

**Describe alternatives you've considered**
I considered creating an overwrite file in my repository for [the list file](https://github.com/nunocoracao/blowfish/blob/main/layouts/_default/list.html), but I don't have knowledge in writing layout files and I would like for this feature to be an on-off switch in a config file and for it to be easy just like any other feature in blowfish.
Additionally, in this solution if blowfish gets an update to the list file, I would not get it because I overwrite it which is problematic for any possible errors that may arise.

**Comment by nunocoracao** [comment]
This is a good one, definitely something that the actual blowfish site could use - aka I've been faking dates to get the order I want..

**Comment by mnjm** [comment]
Working on this [here](https://github.com/nunocoracao/blowfish/compare/main...mnjm:blowfish:order-by-weight)

 I'm considering opening a PR for this after testing it against the base and adding it to the exampleSite doc
