### ISSUE TITLE
ERROR render of "page" failed

### ISSUE THREAD

**Issue by paradox2k** [nunocoracao/blowfish#1499]
**Describe the bug**
After upgrade blowfish to the latest version, the error message occurred when I tried to build a site.

**To Reproduce**
Try to build a site as follow:

> hugo

**Expected behavior**
Building the site is success.

**Screenshots**
<img width="481" alt="image" src="https://github.com/nunocoracao/blowfish/assets/134837856/e4d0454a-d85e-4ed6-830f-6f796c87d712">

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2

**Hugo & Blowfish versions**
Hugo : 0.125.7
Blowfish: 2.68.0

**Additional context**
Detailed error messages are as follows:

hugo v0.125.7-b1d808bc373f53ad37c8966bb02a6aea095db5f8+extended windows/amd64 BuildDate=2024-05-08T14:46:24Z VendorInfo=gohugoio

ERROR render of "page" failed: "C:\blog\innofactory_blog\themes\blowfish\layouts\_default\single.html:52:13": execute of template failed: template: _default/single.html:52:13: executing "main" at <partial "author-extra.html" (dict "context" . "data" $authorData "link" $taxonomyLink)>: error calling partial: "C:\blog\innofactory_blog\themes\blowfish\layouts\partials\author-extra.html:14:40": execute of template failed: template: partials/author-extra.html:14:40: executing "partials/author-extra.html" at <$authorImage.Fill>: error calling Fill: error calling resources.GetRemote: Get "profile.png": unsupported protocol scheme ""
Total in 7106 ms
Error: error building site: render: failed to render pages: render of "page" failed: "C:\blog\innofactory_blog\themes\blowfish\layouts\_default\single.html:52:13": execute of template failed: template: _default/single.html:52:13: executing "main" at <partial "author-extra.html" (dict "context" . "data" $authorData "link" $taxonomyLink)>: error calling partial: "C:\blog\innofactory_blog\themes\blowfish\layouts\partials\author-extra.html:14:40": execute of template failed: template: partials/author-extra.html:14:40: executing "partials/author-extra.html" at <$authorImage.Fill>: error calling Fill: error calling resources.GetRemote: Get "profile.png": unsupported protocol scheme ""

**Comment by paradox2k** [comment]
This problem appears to occur when the "profile.png" file does not exist.

**Comment by wermos** [comment]
As you can see [here](https://github.com/nunocoracao/blowfish/compare/v2.67.0...nunocoracao:v2.68.0), the partial `author-extra.html` was not changed between version v2.67.0 and v2.68.0.

What version of Blowfish did you upgrade from? Is `profile.png` a local asset or are you getting it from a remote URL? Did you recently also upgrade Hugo versions?

**Comment by nazar-pc** [comment]
I have the same issue with author's image. I placed a file into `static/img/avatars/nazar-pc.jpg`, which opens fine through hugo's server. But when I specify `"image": "img/avatars/nazar-pc.jpg"` in author's JSON file I get this error.

Looks like it expects a remote URL for some reason because `https://` URL in the same place works :thinking:
