### ISSUE TITLE
An Issue about Copyright and License

### ISSUE THREAD

**Issue by eallion** [nunocoracao/blowfish#1509]
Can I port the style of Blowfish to Typora and publish it on theme.typora.io?

Thanks!

**Comment by nunocoracao** [comment]
Given enough time and money anything is possible :) 

I would say though that that's 80% of what a theme is though... so not sure about why you would do that...

This is, however, outside of the scope of this repo so I'll be closing this ticket. Feel free to open a discussion to see if someone in the community wants/can help.
