### ISSUE TITLE
🐛 copyright in footer no longer accepts markdown

### ISSUE THREAD

**Issue by fuse314** [nunocoracao/blowfish#1510]
**Describe the bug**
When using markdown in the "copyright" site param, it is no longer rendered as markdown link (for me, it contains a link...)

Probably caused by:
https://github.com/nunocoracao/blowfish/blame/976e6d1472dc787c15cb86b3150a0eb308206e12/layouts/partials/footer.html#L30

The line should probably be ` . | markdownify` instead of `. | emojify`

**To Reproduce**
1. add this line to the config: `copyright = "©️ 2024 by [**Author Name**](https://example.org/)"`
2. Create the page
3. The footer shows the markdown code instead of a link.

**Expected behavior**
Markdown in the copyright notice should be parsed correctly.

**Screenshots**
![image](https://github.com/nunocoracao/blowfish/assets/927896/235c8acf-e470-4734-9030-9923cbed5bef)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version: Latest

**Hugo & Blowfish versions**
Hugo: 0.125.4
Blowfish: latest from `main` branch

**Comment by wermos** [comment]
This was indeed a mistake that accidentally got in, as you can see [here](https://github.com/nunocoracao/blowfish/pull/1504#issuecomment-2143485350).

**Comment by nunocoracao** [comment]
Fixed in https://github.com/nunocoracao/blowfish/pull/1516
