### ISSUE TITLE
The article date displays a serious error

### ISSUE THREAD

**Issue by Arcelibs** [nunocoracao/blowfish#1524]
Hello, in my article, the date is shown as follows:
+++
title = 'Creating a Hugo Website!'
date = 2024-05-17T17:18:43+08:00
draft = false
+++

However, when rendered by Hugo, it appears as:
171718-05-17

Can someone tell me why this is happening and how to fix it? I live in Taipei, UTC+8.

![image](https://github.com/nunocoracao/blowfish/assets/49543451/493d48dc-689a-4d54-9c5b-f260d6bfc570)

**Comment by nunocoracao** [comment]
Hello @Arcelibs please try something like `2020-08-09`
Also, date rendering is not handled by the theme but by Hugo, feel free to check their docs and open a bug on that repo.
