### ISSUE TITLE
Typo in the Blowfish's documentation on Homepage Layout section

### ISSUE THREAD

**Issue by Zer0xxxx** [nunocoracao/blowfish#153]
Hello!

I just found a little _mistake_ on your documentation, about the _Homepage Layout_.

![typo](https://user-images.githubusercontent.com/36828641/197400457-16de831e-ceb7-483e-960c-2442e6188d52.png)

Just above the "Card Layout" section, the text is:
> To enable the profile layout, set homepage.layout = "profile" and homepage.homepageImage in the params.toml configuration file.

Instead of:
> To enable the card layout, set homepage.layout = "card" and {I dunno, lol}

Warm regards! :)

**Comment by nunocoracao** [comment]
Thanks @Zer0xxxx I'll fix it this week

**Comment by Zer0xxxx** [comment]
Oh, I found another one!

![Capture d’écran_2022-10-24_09-47-28](https://user-images.githubusercontent.com/36828641/197474349-8d4be4cb-2595-40e9-bed0-614c51916529.png)

_fucntion_ instead of _function_.

Sorry to be annoying.

**Comment by nunocoracao** [comment]
fixed in https://github.com/nunocoracao/blowfish/commit/4517ae0f0f2fb6e0a6d2070cad4514cbbac88dab
