### ISSUE TITLE
🚧 consider disabling analytics in local development environments

### ISSUE THREAD

**Issue by muncus** [nunocoracao/blowfish#1543]
**Is your feature request related to a problem? Please describe.**

I noticed recently that my Google analytics seem to include clicks from my local development environment. For example, I see analytics reported for articles not yet published.

**Describe the solution you'd like**
I've extended the analytics partial for my site with a small conditional like so:

```
{{ if hugo.IsProduction }}
 (current analytics partial content here)
{{ end}}
```
Something like this for either the `ga.html` partial, or the full `analytics.html` partial could solve this for others as well.

**Describe alternatives you've considered**

There's no harm in leaving this as it is now.

**Additional context**
I'm happy to put together a PR for this if there is general support.

**Comment by lambertwiddersinn** [comment]
Hugo can do this through config files. Under config create a production folder and there add all params that should be only active in production. In the _default folder remove these params. That way you split the configuration for development and production.

https://gohugo.io/getting-started/configuration/#configuration-directory

There's also an example for Google analytics on this doc page.

**Comment by nunocoracao** [comment]
I am closing this issue as the solution from @lambertwiddersinn seems to match the request
