### ISSUE TITLE
umaniAnalytics not working

### ISSUE THREAD

**Issue by xcelerent** [nunocoracao/blowfish#1562]
**Describe the bug**
Below is how I enabled the umamiAnalytics with the setting from `params.toml` file.
![](https://i.imgur.com/TUHudK5.png)

However, nothing is shown up on the umami website.

![](https://i.imgur.com/xoh44BQ.png)

Here is how I get the site id.

![](https://i.imgur.com/deVzlvN.png)

**Hugo & Blowfish versions**
Hugo version: v0.127.0
Blowfish version: 2.70.0

**Comment by ditwrd** [comment]
`domain` is used if you self hosted your Umami instance, in your case you are using umami.is cloud service, removing `domain` from the your config will fix it

Umami (and other analytics app) usually inject a script (usually a `.js`) on your website `<head>` block, where the script is retrieve from the analytics app. In the case of self host-able analytics apps, you retrieve the script directly from your analytics app domain (analytics.your-own-domain.com), while if you are using cloud service, you'll use the service domain (cloud-analytics.com)

**Comment by xcelerent** [comment]
It works now. Great thanks

**Comment by Pureball** [comment]
Hello - unfortunately I have the same issue.

I'm using the Umami Cloud version.

Here is my ```params.toml```:

```
[umamiAnalytics]
websiteid = "1256gbh4-23sx-4fg6-3ed9-4rfd409362gk"
# domain = "llama.yoursite.com"
# dataDomains = "yoursite.com,yoursite2.com"
# scriptName = ""
enableTrackEvent = true
```

I did check the blowfish documentation but still nothing is showing up in Umami Analytics.

I'm using Blowfish as submodule in my Repo - do I maybe have to add something to the ```layout/partials``` of my repo?
For example I can see in ```layouts/partials/analytics/umami.html``` in the Blowfish theme - do I have to add this to my ```layout/partials``` in my repo?
