### ISSUE TITLE
Turn off analytics in development mode to prevent unwanted tracking

### ISSUE THREAD

**Issue by ditwrd** [nunocoracao/blowfish#1567]
**Is your feature request related to a problem? Please describe.**
I've set up umami analytics (self hosted) on my website using the designated configuration in `params.toml`, and while checking locally I found that it triggered the analytics causing an inflation in the metrics

**Describe the solution you'd like**
Turn off analytics in development mode to prevent unwanted tracking

**Describe alternatives you've considered**
I work around this issue by reverting the change in `params.toml` and using `layouts/partials/extend-head.html` that contain this snippets
```html
{{ if hugo.IsProduction}}
<insert-script-here>
{{ end }}
``` 

**Additional context**
Minimal change on `layouts/partials/analytics/main.html` and docs should be enough, if you may I can open a PR to aid you with this issue

Thank you!

**Comment by mnjm** [comment]
There's already another open issue on this #1543.

A temp fix: move analytics related config from `config/_default` to `config/production` as suggested [here](https://github.com/nunocoracao/blowfish/issues/1543#issuecomment-2179945121)

**Comment by nunocoracao** [comment]
duplicates https://github.com/nunocoracao/blowfish/issues/1543
