### ISSUE TITLE
Mermaid rendering broken after update

### ISSUE THREAD

**Issue by DominikBritz** [nunocoracao/blowfish#1576]
**Describe the bug**
I have a mermaid flowchart on my site, which rendered flawlessly. I've updated blowfish from _2.5 something_ to _2.71.0_. After the update, the mermaid chart is gone but I see the mermaid code instead. Updated to _2.71.1_ but I see the same issue.

The website is hosted on [GitHub](https://github.com/DominikBritz/dominikbritz.com/tree/main/public) and served through Cloudflare.

**To Reproduce**
- Go to https://42884892.dominikbritz-com.pages.dev/posts/2024-01-22-laptop-home-server/#introducing-ansible and notice the mermaid code.
- This is with blowfish 2.7.1

**Expected behavior**
- Go to https://a612d22d.dominikbritz-com.pages.dev/posts/2024-01-22-laptop-home-server/#introducing-ansible and notice the mermaid chart rendering correctly
- This is with blowfish 2.5 something

**Screenshots**
Working
![image](https://github.com/nunocoracao/blowfish/assets/11243580/65f85aa9-e144-47e9-a365-be2b77d12e44)

Not working
![image](https://github.com/nunocoracao/blowfish/assets/11243580/f6bdc1fd-7cd8-4f6b-b548-9c886c60922e)

**Desktop (please complete the following information):**
 - OS: Windows, Android
 - Browser: Firefox, Edge
 - Version: latest

**Hugo & Blowfish versions**
Hugo: `hugo v0.127.0-74e0f3bd63c51f3c7a0f07a7c779eec9e922957e+extended windows/amd64 BuildDate=2024-06-05T10:27:59Z VendorInfo=gohugoio`
Blowfish: 2.71.1

**Additional context**

**Comment by nunocoracao** [comment]
Hello @DominikBritz , the feature is working just fine on the Blowfish website so I am closing this issue. 
http://localhost:1313/samples/diagrams-flowcharts/ 

I would check my Blowfish website repo for the page. 

Unfortunately, the repo you shared only shows the public files for the page. Not the theme nor the related content pages. This seems to be a problem generating the site not the theme itself. FYI, I've noticed multiple people having problems with Cloudflare depending on where they run Hugo and which version is being used.
