### ISSUE TITLE
🐛 Site Background is not showing on Articles

### ISSUE THREAD

**Issue by DarkXero-dev** [nunocoracao/blowfish#1579]
**Describe the bug**
I have set a default site wide background image, yet it will only show on home page. I dunno if it's a bug or am doing something wrong. I gave up after 3 hours of trying.

**To Reproduce**

Follow blowfish-tool to set up a background. Does not work for Articles. 

**Screenshots**
Check my site [here](https://xerolinux.xyz/)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser : Vivaldi
 - Version 6.8.3381.46 (Stable channel)

**Hugo & Blowfish versions**
- Hugo : v0.128.0+extended
- Blowfish : 2.71.1

**Comment by nunocoracao** [comment]
Hello @DarkXero-dev you just need to set the `defaultBackgroundImage` in the `params.toml` file (in /config/_default/). 

```toml
defaultBackgroundImage = "/img/background.svg"
```
