### ISSUE TITLE
Toggle option ON/OFF for automatic quotes characters on blockquotes

### ISSUE THREAD

**Issue by LeBlancLapin** [nunocoracao/blowfish#160]
Hello,

I would like to know if there is any way to disable the automatic `"` characters on the blockquotes, likely:
Get:
> Hello world

When I write:
`> Hello world`

Instead of : 
> "Hello world"

It would be maybe possible with some markdown attributes?
Like it is already done for adding the author's name with:

```md
> Don't communicate by sharing memory, share memory by communicating.<br>
> — <cite>Rob Pike[^1]</cite>
```

Maybe something like?

```md
> <rawblockquote>Don't communicate by sharing memory, share memory by communicating.</rawblockquote>
```

Regards.

**Comment by nunocoracao** [comment]
@LeBlancLapin thanks for your feedback. I'll need time to investigate this one.

**Comment by Zer0xxxx** [comment]
(Changed of account, sorry.)

Maybe something like: ```
> <q>This is a quote with `"` characters</q>
``` ?

**Comment by nunocoracao** [comment]
You can override those tailwind settings by configuring the typography module. Please check 
https://tailwindcss.com/docs/typography-plugin
