### ISSUE TITLE
Search function breaks when deploying a site via Vercel

### ISSUE THREAD

**Issue by lyfja** [nunocoracao/blowfish#1610]
**Describe the bug**
The search function does not work when a blowfish site is deployed through Vercel. By that I mean you receive no search results no matter what you type in.
Searching still works when you build the site locally, but the moment you deploy it through Vercel and then search for anything there, nothing shows up.

**To Reproduce**
1. Create a new blowfish site and build it locally
2. Try searching for something. Putting in a single letter like "s" for example should give you the premade tags, authors, etc. pages as a result.
3. Deploy the site through Vercel
4. Visit the deployed site and repeat step 2. This time, no search results show up.

Deploying the site on GitHub Pages _does_ make the search function work, so I think it's safe to assume that this is a Vercel problem.

**Screenshots**
This video compares a search on the same site, deployed on GitHub Pages vs. on Vercel:
[Bildschirmaufzeichnung vom 2024-07-11 14-48-36.webm](https://github.com/nunocoracao/blowfish/assets/45209212/6157a68a-d148-4049-ace1-d5eec89e300a)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 40
 - Browser: Firefox 128.0
 
**Hugo & Blowfish versions**
- Hugo: v0.128.2+extended
- Blowfish: v2.73.0

**Comment by nunocoracao** [comment]
Did you set the baseurl correctly?

**Comment by lyfja** [comment]
Thanks, I figured it out, Vercel defaults to "https://www.example.com" instead of "https://example.com".

Although with an older site I made with Blowfish, it didn't work until I updated the theme just now. Maybe there was a bug in the past, but now the issue is gone.
