### ISSUE TITLE
TOC doesn't move when scrolling.

### ISSUE THREAD

**Issue by Sitaye** [nunocoracao/blowfish#1624]
**Describe the bug**
I updated my theme submodule through `git submodule update --remote --merge` yesterday, and I found that after redeployment, the TOC in articles no longer moved and shifted up when I scrolled down.

**To Reproduce**
1. Update Hugo: download the latest binary file from [gohugoio/hugo](https://github.com/gohugoio/hugo/releases/tag/v0.129.0)
2. Create a new Hugo repository: `hugo new site test_bug`
3. Enter the repo and pull the theme: `git submodule add -b main https://github.com/nunocoracao/blowfish.git themes/blowfish`
4. Apply the theme as described in the [Blowfish](https://blowfish.page/docs/installation/#set-up-theme-configuration-files) documentation
5. Create a test markdown file: `hugo new posts/test.md`
6. Write some content and create multilevel headings
7. Scroll and see the error

**Expected behavior**
I expected the TOC to remain fixed as before.

**Screenshots**
[My Site] Before Update:
![image](https://github.com/user-attachments/assets/cbc06f16-558a-4e3f-b2a1-bb70461d027c)
[My Site] After Update:
![image](https://github.com/user-attachments/assets/2722b382-f8a7-4c10-8b4f-0f3bf9cfa125)
[Test] Clearly Seen:
![image](https://github.com/user-attachments/assets/10965cd3-bbf6-43f0-b86b-0add7aa99e43)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Browser: Chrome
 - Version: 126.0.6478.127

**Hugo & Blowfish versions**
- Hugo: v0.129.0
- Blowfish: v2.74.0

**Comment by mrtolkien** [comment]
Same issue. Tried rolling back hugo and blowfish but I can't seem to find a setup that works.

**Comment by ragibson** [comment]
This has actually started working for me again in v2.75.0

**Comment by Sitaye** [comment]
Yeah...it works. Looks like some bugs have actually been fixed.
