### ISSUE TITLE
[Request] Ability to configure RSS feed

### ISSUE THREAD

**Issue by DarkXero-dev** [nunocoracao/blowfish#1641]
**Is your feature request related to a problem? Please describe.**
I cannot find a way to configure RSS feed length. It just defaults to showing first sentence having to go to site to read entire article.

**Issues**
For now I have disabled RSS as for whatever reason I am getting errors in all Feed readers parsing it. That's why am requesting this.

**Describe the solution you'd like**
A way to enable both atom and rss2 feeds and configure length like if we need entire article to be shown or not

**Describe alternatives you've considered**
I use Hexo on another site/blog and it has a plugin that does exactly that.

**Comment by insidemordecai** [comment]
I also second the idea to have flexibility in configuration esp with the feed length. That is one issue I keep bumping into since I rely on RSS readers.

**Comment by insidemordecai** [comment]
@DarkXero-dev you can have a look at an RSS override i made for my own site: [rss.xml](https://github.com/insidemordecai/insidemordecai.com/blob/main/layouts/_default/rss.xml), maybe it might be helpful for you. it loads the full content and personally i have it set to show only articles in the `posts/` directory in the RSS feed.

**Comment by DarkXero-dev** [comment]
@insidemordecai 

I deleted mine can you remind me how to bring it back n use yours ?

**Comment by insidemordecai** [comment]
@DarkXero-dev sorry my blog is mostly text so i haven't played around with some of those shortcodes, i wouldn't be the right person to advise with that 

about also including posts under `news/`, you can modify the `where` filter in the RSS template from what i have replacing `posts` with `news` like this (first 12 lines) : 

```
{{- $pctx := . -}}
{{- if .IsHome -}}{{ $pctx = .Site }}{{- end -}}
{{- $pages := slice -}}
{{- if or $.IsHome $.IsSection -}}
{{- $pages = (where (where $pctx.RegularPages ".Section" "news") "Kind" "page")  -}}
{{- else -}}
{{- $pages = (where (where $pctx.Pages ".Section" "news") "Kind" "page")  -}}
{{- end -}}
{{- $limit := .Site.Config.Services.RSS.Limit -}}
{{- if ge $limit 1 -}}
{{- $pages = $pages | first $limit -}}
{{- end -}}
```

if you wanted to included multiple pages eg. `news` and `notes`, here's how it would look like (first 12 links again - i haven't tried it out but i believe it should work):

```
{{- $pctx := . -}}
{{- if .IsHome -}}{{ $pctx = .Site }}{{- end -}}
{{- $pages := slice -}}
{{- if or $.IsHome $.IsSection -}}
{{- $pages = (where (where $pctx.RegularPages ".Section" "in" (slice "news" "notes")) "Kind" "page")  -}}
{{- else -}}
{{- $pages = (where (where $pctx.Pages ".Section" "in" (slice "news" "notes")) "Kind" "page")  -}}
{{- end -}}
{{- $limit := .Site.Config.Services.RSS.Limit -}}
{{- if ge $limit 1 -}}
{{- $pages = $pages | first $limit -}}
{{- end -}}
```

**Comment by insidemordecai** [comment]
@DarkXero-dev just checked it out on my RSS reader and it's looking great, just those pesky shortcodes. i hope someone fixes it soon

**Comment by DarkXero-dev** [comment]
@insidemordecai Same. Blowfish is one of if not the best Hugo theme out there. Would be a real shame if they did not at least look into it. Heck there's a feature I requested months ago that they didn't even bother to look at so my hopes are really low..

**Comment by insidemordecai** [comment]
@DarkXero-dev I kinda understand Nuno, he's essentially a one man team with a full-time job so developing features might take some time and that would be if it is absolutely necessary and easy to maintain later on. 

What might help is if you can lay out how you think a feature should be implemented in detail and if it gathers interest in the community then surely someone will contribute. Heck if it's something you think you can create, you can contribute yourself, at least that's what I did recently.

**Comment by DarkXero-dev** [comment]
@insidemordecai 

I understand him too coz I am a one man ban maintaining a Linux Distro (Arch-Based) and 4 scripts. I am in the same situation except I am jobless lol. I do not do coding barely get Bash as it is.

**Comment by nunocoracao** [comment]
Thanks for raising this @DarkXero-dev. I don't plan to add support for this as it would require a new parameter in the configs - otherwise, it would be introducing a breaking change. I am avoiding this as much as I can given the huge size of available configurations in the theme already. @insidemordecai suggested the right solution an override for this specific use case. 

Happy to re-open the ticket later and support if someone wants to provide a PR.

**Comment by nunocoracao** [comment]
@DarkXero-dev also sorry for the lack of support, I do understand how frustrating it can be. As @insidemordecai mentioned I am the only maintainer for Blowfish, this is not my primary gig, and I make $0 from it. I know it doesn't solve your problem but hopefully it provides some context. Will take a look at your other ticket now.

**Comment by DarkXero-dev** [comment]
Oh no problem. Sorry is my post came through as if I was demanding. As you saw am in a similar situation as you. Solo maintener of a Linux Distro...
