### ISSUE TITLE
Blowfish is uncompatible with hugo stable version 0.130.0

### ISSUE THREAD

**Issue by dev-orphae** [nunocoracao/blowfish#1658]
**Describe the bug**
The blowfish module is uncompatible with the last update of hugo v0.130.0. The web development server won't start when creating a new project with it.

**To Reproduce**
1. Open a terminal
2. Launch the command `brew install hugo node`
3. Launch the command `npm i -g blowfish-tools`
4. Launch the command `blowfish-tools`
5. Scroll down to 'Setup a new website with Blowfish'
6. Press Enter
7. Enter an empty or non-existent directory name (e.g. '`./test/`')
8. Scroll down to 'Run a local server with Blowfish'
9. Press Enter
10. See error

**Expected behavior**
I expect to happen a webserver being run and accessible through http://localhost:1313 after pressing the last 'Enter' key.

**Screenshots**
```
WARN  Module "blowfish" is not compatible with this Hugo version: 0.87.0/0.128.2; run "hugo mod graph" for more information.
Watching for changes in /home/orphae/Code/web/orph.ae/test/{archetypes,assets,content,data,i18n,layouts,static,themes}
Watching for config changes in /home/orphae/Code/web/orph.ae/test/hugo.toml, /home/orphae/Code/web/orph.ae/test/config/_default, /home/orphae/Code/web/orph.ae/test/themes/blowfish/config.toml, /home/orphae/Code/web/orph.ae/test/themes/blowfish/config/_default
Start building sites … 
hugo v0.130.0+extended linux/amd64 BuildDate=2024-07-29T13:51:56Z VendorInfo=brew

ERROR open /home/orphae/Code/web/orph.ae/test/public/css/main.bundle.min.8ea60310059bae0843ca33ef1de0ed63f1367330a68d9b13d82d6c3bc474a4c1a7c705dba2592e367518d4eb2c0a82076592aeab874ff2e02034ddc7147c752f.css: file name too long
ERROR open /home/orphae/Code/web/orph.ae/test/public/js/appearance.min.516a16745bea5a9bd011138d254cc0fd3973cd55ce6e15f3dec763e7c7c2c7448f8fe7b54cca811cb821b0c7e12cd161caace1dd794ac3d34d40937cbcc9ee12.js: file name too long
Built in 92 ms
Error: error building site: open /home/orphae/Code/web/orph.ae/test/public/css/main.bundle.min.8ea60310059bae0843ca33ef1de0ed63f1367330a68d9b13d82d6c3bc474a4c1a7c705dba2592e367518d4eb2c0a82076592aeab874ff2e02034ddc7147c752f.css: file name too long
```

**Desktop (please complete the following information):**
 - OS: `Linux Mint Linux bazinga 5.15.0-117-generic #127-Ubuntu SMP Fri Jul 5 20:13:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Hugo & Blowfish versions**
`hugo v0.130.0+extended linux/amd64 BuildDate=2024-07-29T13:51:56Z VendorInfo=brew`
`hugo-blowfish-theme` version `2.74.0`

**Comment by ragibson** [comment]
You seem to be getting `file name too long` errors here. 

Do you happen to have home folder encryption enabled in your Linux Mint installation? That forces file length limits of ~140 characters, which is why it's recommended to do full disk encryption instead.

I ran into a similar issue in the past because LM defaults to the home-folder-only encryption for some reason.

**Comment by DarkXero-dev** [comment]
I get other errors
```
WARN  Module "blowfish" is not compatible with this Hugo version: 0.87.0/0.128.2; run "hugo mod graph" for more information.
WARN  deprecated: .Site.Author was deprecated in Hugo v0.124.0 and will be removed in a future release. Use taxonomies instead.
WARN  deprecated: data.GetJSON was deprecated in Hugo v0.123.0 and will be removed in a future release. use resources.Get or resources.GetRemote with transform.Unmarshal.
WARN  The author key in site configuration is deprecated. Use params.author.name instead.
^Chugo server --disableFastRender  14.09s user 0.84s system 22% cpu 1:05.44 total
➜ hs
WARN  Module "blowfish" is not compatible with this Hugo version: 0.87.0/0.128.2; run "hugo mod graph" for more information.
```

**Comment by ragibson** [comment]
The complaints about Hugo version compatibility are more like generic warnings that Blowfish hasn't been explicitly tested for those versions. I've tried a few builds and see no apparent incompatibilities with v0.130.0.

The deprecation warnings are tracked in a few other GitHub issues, but have not been addressed yet.

**Comment by DarkXero-dev** [comment]
@ragibson 

Ok thank you. What about .Author thing being deprecated ? I am also having major issues with RSS feed which I have posted about >> [**HERE**](https://github.com/nunocoracao/blowfish/issues/1641)

**Comment by DarkXero-dev** [comment]
@ragibson 

Ooops did not see it lol thanks again..

**Comment by wtchangdm** [comment]
Normally the supported hugo version is automatically bumped by github action like #1623. Although I am not sure it's being actually tested

**Comment by Ast3risk-ops** [comment]
> I see it over in https://github.com/nunocoracao/blowfish/issues/1645

OP of that issue here.

I noticed the warning but the build works fine on Hugo 130 (https://asterisk.lol is built with that version).

**Comment by Ast3risk-ops** [comment]
> Normally the supported hugo version is automatically bumped by github action like #1623. Although I am not sure it's being actually tested 

It's bumped to `dev` where it's then tested.

**Comment by ragibson** [comment]
Looks like this is now fixed in v2.75.0.

**Comment by 16bit-ykiko** [comment]
Docs [here](https://blowfish.page/docs/configuration/#author) seems to need to be updated. For lastest blowfish, not `author` but `params.author`.

**Comment by Ast3risk-ops** [comment]
> Docs [here](https://blowfish.page/docs/configuration/#author) seems to need to be updated. For lastest blowfish, not `author` but `params.author`.

#1708 fixes that.
