### ISSUE TITLE
I can't use ZenMode after publishing on Repo

### ISSUE THREAD

**Issue by DarkXero-dev** [nunocoracao/blowfish#1661]
Hello, 

I dunno if this is a bug per-se but for whatever reason ZenMode stops working after I publish site on Github. It works in preview but dies once published.  Clicking ZenMode button in the articles does nothing.

Here's my site
https://xerolinux.xyz

**Comment by wtchangdm** [comment]
You should try to disable rocket loader in cloudflare's config.

Even though this is documented under cloudflare pages' section, it really doesn't matter what your origin is as long as you have it enabled.
https://blowfish.page/docs/hosting-deployment/#cloudflare-pages

**Comment by DarkXero-dev** [comment]
@wtchangdm 

Thanks solved.. I should've read more...
