### ISSUE TITLE
Add webp image support 

### ISSUE THREAD

**Issue by infused-kim** [nunocoracao/blowfish#1673]
Hi,

I am wondering if you would be interested in a PR that adds webp image support to blowfish. 

It’s a next-gen image format that produces smaller file sizes and [is now supported by 96% of browsers](https://caniuse.com/webp). All other browsers can fall back to a regular jpg or png image. 

It’s also one of the [recommended suggestions by Google speed insights](https://developer.chrome.com/docs/lighthouse/performance/uses-webp-images/?utm_source=lighthouse&utm_medium=lr). 

Blowfish is already regarded as a very efficient and optimized theme that is built with best practices in mind and adding webp support would solidify that reputation even more. 

**My initial experience with it**

On my site I did an initial test of it. I added `<picture>` and `webp` support in `layouts/_default/_markup/render-image.html`.

This only applies to images added in the content and doesn’t work for all the other images, such as hero, author, etc. 

But the results are promising. Many of my images, especially the high resolution ones were reduced by 30-50%. 

The page insight score also went up. 

You can check [this post with many images as an example](https://kimhq.net/blog/ps2-mouse-driver-dev-journey/).

My rough first draw was this:
```diff
{{- $disableImageOptimization := .Page.Site.Params.disableImageOptimization | default false }}
{{- $url := urls.Parse .Destination }}
{{- $altText := .Text }}
{{- $caption := .Title }}
{{- if findRE "^https?" $url.Scheme }}
  <figure>
    <img class="my-0 rounded-md" loading="lazy" src="{{ $url.String }}" alt="{{ $altText }}" />
    {{ with $caption }}<figcaption>{{ . | markdownify }}</figcaption>{{ end }}
  </figure>
{{- else }}
  {{- $resource := "" }}
  {{- if $.Page.Resources.GetMatch ($url.String) }}
    {{- $resource = $.Page.Resources.GetMatch ($url.String) }}
  {{- else if resources.GetMatch ($url.String) }}
    {{- $resource = resources.Get ($url.String) }}
  {{- end }}
  {{- with $resource }}
    <figure>
      {{- if or $disableImageOptimization (eq .MediaType.SubType "svg")}}
      <img
        class="my-0 rounded-md"
        loading="lazy"
        src="{{ .RelPermalink }}"
        alt="{{ $altText }}"
      />
      {{- else }}
-      <img
-        class="my-0 rounded-md"
-        loading="lazy"
-        srcset="
-        {{ (.Resize "330x").RelPermalink }} 330w,
-        {{ (.Resize "660x").RelPermalink }} 660w,
-        {{ (.Resize "1024x").RelPermalink }} 1024w,
-        {{ (.Resize "1320x").RelPermalink }} 2x"
-        src="{{ (.Resize "660x").RelPermalink }}"
-        alt="{{ $altText }}"
-      />
+      {{ $widths := slice "330" "660" "1024" "1320" }}
+      {{ $img := . }}
+      <picture>
+        <source type="image/webp" srcset="
+        {{ range $i, $width := $widths }}
+          {{ if $i }},{{ end }}
+          {{ ($img.Resize (printf "%sx webp" $width)).RelPermalink }} {{ $width }}w
+        {{ end }}">
+
+        <source type="image/jpeg" srcset="
+        {{ range $i, $width := $widths }}
+          {{ if $i }},{{ end }}
+          {{ ($img.Resize (printf "%sx" $width)).RelPermalink }} {{ $width }}w
+        {{ end }}">
+
+        <img
+          class="my-0 rounded-md"
+          loading="lazy"
+          src="{{ ($img.Resize "660x").RelPermalink }}"
+          alt="{{ $altText }}"
+        />
+      </picture>
      {{- end }}
      {{ with $caption }}<figcaption>{{ . | markdownify }}</figcaption>{{ end }}
    </figure>
  {{- else }}
    <figure>
      <img class="my-0 rounded-md" loading="lazy" src="{{ $url.String }}" alt="{{ $altText }}" />
      {{ with $caption }}<figcaption>{{ . | markdownify }}</figcaption>{{ end }}
    </figure>
  {{- end }}
{{- end }}
```

## PR Implementation

If you are interested in adding this to blowfish, I would happy to submit a PR. 

My current idea is to add a new `img` shortcut that is very flexible. 

We can add a site setting to enable and disable webp images. 

And then the `layouts/_default/_markup/render-image.html` would call that shortcut. 

Then we can call the img shortcut from all the places in the theme that currently generate the img tag manually. 

What do you think of this? Please don’t hesitate if you have guidance on how you would like this implemented.

**Comment by ragibson** [comment]
WebP images are already supported in the image shortcodes in Blowfish -- do some of the shortcodes not work correctly with them?

**Comment by ragibson** [comment]
Actually, judging from your example web page, this patch actually breaks `.webp` support -- when clicked, images are meant to zoom to no larger than the source resolution (already working with `.webp` on the current Blowfish version), but this does not work correctly on your website anymore.

**Comment by infused-kim** [comment]
Yes, you can add webp images and display them, but then there is no fallback to show regular jpg or png on devices that don’t support it. 

Hugo can convert png and jpgs into webp and it’s possible to serve them as an option that browsers that support them use while providing older formats as a fallback using the picture element. 

Regarding the zoom, yes currently blowfish is using an old version of medium-zoom that’s not compatible with the picture. 

I actually started working on the implementation for my own use already. And can hopefully push a draft soon.

**Comment by ragibson** [comment]
Oh, interesting. I had figured that nobody would bother with a fallback
since Chrome, Firefox, Edge, Safari, and Opera have supported the format
for years.

I hadn't quite parsed the fact that your patch is converting to webp
automatically through Hugo. I've been batching the conversions externally.

**Comment by nunocoracao** [comment]
Thanks for raising this @infused-kim 
Not interested in supporting this fallback option since, as @ragibson already mentioned, most used browsers support the format.  Also it would increase code complexity that I would need to maintain.
