### ISSUE TITLE
✨ Update mobile menu logic to rely on JS

### ISSUE THREAD

**Issue by JVimes** [nunocoracao/blowfish#1695]
**Describe the bug**
The mobile menu opens when using browser Back button in some cases, which I found unexpected.

**To Reproduce**
1. Go to [blowfish.page](https://blowfish.page) on mobile
2. Open menu and tap a page link like Docs or Shortcodes
3. Tap browser back button

**Expected behavior**
I expected the menu to be closed when returning to previous page.
If this is a feature, is it configurable to disable?

**Desktop:**
 - OS: Android
 - Browser: Chrome
 - Version: 127

**Hugo & Blowfish versions**
Latest on blowfish.page.

**Comment by ragibson** [comment]
Replicated on mobile Firefox and all major desktop browsers (when dropdowns exist) as well.
