### ISSUE TITLE
Error building site: render of "404" failed -- WITH SOLUTION

### ISSUE THREAD

**Issue by guefra** [nunocoracao/blowfish#1697]
**Describe the bug**
When building a site with hugo and the blowfish theme, having just one markdown file (or more) and running `hugo` or `hugo server` without the `-D` flag, it spits out this error:

`Error: Error building site: render of "404" failed: "/var/www/guefra/themes/blowfish/layouts/_default/baseof.html:20:5": execute of template failed: template: 404.html:20:5: executing "404.html" at <partial $header .>: error calling partial: "/var/www/guefra/themes/blowfish/layouts/partials/header/basic.html:8:51": execute of template failed: template: partials/header/basic.html:8:51: executing "partials/header/basic.html" at <markdownify>: error calling markdownify: runtime error: invalid memory address or nil pointer dereference`

Why do I post this issue, as I fixed it? Because it took me too long to figure that out, as the error just doesn't give you a hint, why it doesn't work.

**To Reproduce**
1. Build a (simple) hugo website and install the blowfish theme
2. (Configure your site a little bit)
3. Create some articles/makrdown files (if it's _some-article.md_ or these __index.md_ files, it doesn't matter) and leave the `draft: true`/`draft = true` option
4. Run `hugo` or `hugo server`, then see the error

**Expected behavior**
Just an error, which tells you, that you have to use the `-D` flag for your hugo command or change every markdown file, so they aren't drafts.

**Fix**
Use the `hugo`/`hugo server` command with the `-D` flag or make every markdown file no draft

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 12.6 (bookworm)
 - Browser Brave 1.68.141
 - Idk, what you mean with version

**Hugo & Blowfish versions**
Hugo v0.111.3+extended | Blowfish 2.75.0

**Comment by ragibson** [comment]
I think this should occur any time there is no content to generate? If you're building a site that only has drafts and choosing to exclude all those pages, there's nothing to build.

I agree an error in this case is probably a Blowfish bug though. I wonder if the 404 page is assuming that certain pages will exist.

**Comment by nunocoracao** [comment]
Hey @guefra thanks for this, I agree unfortunately this is not something that Blowfish controls. Building the site is Hugo's responsibility so that log message would need to come from it. Feel free to open an issue on their repo.

**Comment by guefra** [comment]
Thanks you two (forgot to reply to Rian)! I'm new to hugo and just assumed it was Blowfish's "fault". I actually found a parameter where you can define if drafts should be buildable, I think in the params.toml (not sure, I can't check right now). I may open an issue at hugo because the error message could be made so much more helpful. Anyways, sorry for " accusing" you for the error 😀. Happy developing!
