### ISSUE TITLE
Code Block Copying Restricted Based on Content Overflow

### ISSUE THREAD

**Issue by axliupore** [nunocoracao/blowfish#1702]
**Describe the bug**
When attempting to copy code, if the content does not exceed the code area (i.e., there is no white line appearing below the code block), the code can be copied. However, if a white line appears below the code block, the code cannot be copied.

**To Reproduce**
1. Open a page containing code blocks.
2. Locate a code block whose content does not exceed the code area, meaning there is no white line below the code block.
3. Attempt to copy the content of this code block and confirm that it can be successfully copied.
4. Locate another code block whose content exceeds the code area, causing a white line to appear below the code block.
5. Attempt to copy the content of this code block and find that it cannot be copied.

**Expected behavior**
Regardless of whether the code block exceeds the code area or not, users should be able to copy the content of the code block.

**Screenshots**
Code can be copied.
<img width="654" alt="image" src="https://github.com/user-attachments/assets/f1d72408-07ce-42e7-adc3-530c634f421b">
Code cannot be copied.
<img width="653" alt="image" src="https://github.com/user-attachments/assets/6ef0a3c0-08a6-46e0-aacb-257bdd69d26d">

**Desktop (please complete the following information):**
 - OS: [mac 14.6.1]
 - Browser [chrome]

**Hugo & Blowfish versions**
Hugo = 0.87.0
Blowfish = 2.75.0

**Comment by ragibson** [comment]
I can't replicate this -- code copying seems to work fine when the width is overflowed.

![image](https://github.com/user-attachments/assets/d874204a-48ea-41c9-b2d2-86be1fc06c82)

**Comment by nunocoracao** [comment]
Also can't replicate, closing. @axliupore if you can provide more details or a live example I can try to have a look and re-opened
