### ISSUE TITLE
Article Section Appears Too Narrow on Large Screens

### ISSUE THREAD

**Issue by CyanStarNight** [nunocoracao/blowfish#1714]
I noticed that on large screens (e.g., resolutions around 2048x1156), the article section appears quite narrow, which affects the overall readability and layout aesthetics.
![image](https://github.com/user-attachments/assets/4cbce3cd-b89a-4cff-b6b7-b7c1ded4ea04)

**Questions:**

1. Could you please advise on how I can adjust the width of the article section to better fit larger screens?
2. Are there any plans to include additional parameters or media queries in the future to better handle various screen sizes, especially for large displays?

Thank you for your time and for the great work on this project. I look forward to your response and any suggestions you may have.

**Comment by nunocoracao** [comment]
This follows tailwind's max character per row setting to make it easier for people to read. Imagine having text across the display in a 4k monitor, it's not that friendly.
