### ISSUE TITLE
 Bug with related pages

### ISSUE THREAD

**Issue by Thanatermesis** [nunocoracao/blowfish#1731]
With the last update of Blowfish & Hugo (extended) versions, I had this error:

```text
Start building sites …
hugo v0.134.0-77df7bbbff8ce6b56ed693270088de973a87d5ce+extended linux/amd64 BuildDate=2024-09-03T09:54:22Z VendorInfo=gohugoio

ERROR render of "page" failed: "/elive-git/hugo-blog/themes/blowfish/layouts/_default/single.html:124:11": execute of template failed: template: _default/single.html:124:11: executing "main" at <partial "related.html" .>: error calling partial: "/elive-git/hugo-blog/themes/blowfish/layouts/partials/related.html:2:20": execute of template failed: template: partials/related.html:2:20: executing "partials/related.html" at <.Site.RegularPages.Related>: error calling Related: runtime error: invalid memory address or nil pointer dereference
Total in 235 ms
Error: error building site: render: failed to render pages: render of "page" failed: "/elive-git/hugo-blog/themes/blowfish/layouts/_default/single.html:124:11": execute of template failed: template: _default/single.html:124:11: executing "main" – RegularPages is nil; wrap it in if or with: {{ with partial "related.html" .>: error calling partial: "/elive-git/hugo-blog/themes/blowfish/layouts/partials/related.html:2:20": execute of template failed: template: partials/related.html:2:20: executing "partials/related.html" at <.Site.RegularPages }}{{ .Related }}{{ end }}
```

**Comment by Thanatermesis** [comment]
Actually the previous code should not be valid 🤔, the site builds but is not showing the "related" entries in the bottom of the articles

I have the relatedcontent enabled in my params.toml file, as:
```toml
  showRelatedContent = true
  relatedContentLimit = 3
```
which worked in the version 111.3 of hugo (from debian repos), version of blowfish was 2.71.0

**Comment by Thanatermesis** [comment]
Seems like changing this (default) **hugo.toml** configuration fixes the problem:

```diff
diff --git a/config/_default/hugo.toml b/config/_default/hugo.toml
index c617539..cff2c81 100644
--- a/config/_default/hugo.toml
+++ b/config/_default/hugo.toml
@@ -65,7 +65,7 @@ googleAnalytics = "G-9K109Z8ZWP"
     [[related.indices]]
       applyFilter = false
       name = 'fragmentrefs'
-      type = 'fragments'
+      # type = 'fragments'
       weight = 10
```

Not sure if is needed the "type" entry but commenting it builds the website again and the related posts shows up, maybe it should be removed from the default configurations provided too

**Comment by nunocoracao** [comment]
The last version of the theme is running in prod @ blowfish.page using the related feature... so no there isn't an issue with related article in the latest update - at least in the generic sense like this ticket suggests.

Closing this issue as it doesn't provide enough detail for anyone to reproduce. Please re-open a new one following the bug template.

**Comment by Thanatermesis** [comment]
In short, the last comment which mentions "type = fragments" seems like a default config from blowfish which with it like that it seemed to not work
