### ISSUE TITLE
Updated blowfish now leads to build errors. v2.77.1?

### ISSUE THREAD

**Issue by tetricky** [nunocoracao/blowfish#1734]
I had a working site. Updating blowfish to (I assume) v2.77.1, and to hugo v0.133.1 leads to template errors. The site wont build either in a local environment, nor in github actions. All fail with the same error.

```
ERROR Failed to publish Resource: open /src/mysite-blowfish/public: is a directory
octet-stream
.
.
.
octet-stream
ERROR render of "404" failed: "/src/mysite-blowfish/themes/blowfish/layouts/_default/baseof.html:20:5": execute of template failed: template: 404.html:20:5: executing "404.html" at <partial $header .>: error calling partial: "/src/mysite-blowfish/themes/blowfish/layouts/partials/header/basic.html:15:67": execute of template failed: template: partials/header/basic.html:15:67: executing "partials/header/basic.html" at <$logo.Width>: error calling Width: this method is only available for image resources
ERROR render of "taxonomy" failed: "/src/mysite-blowfish/themes/blowfish/layouts/_default/baseof.html:20:5": execute of template failed: template: _default/taxonomy.html:20:5: executing "_default/taxonomy.html" at <partial $header .>: error calling partial: "/src/mysite-blowfish/themes/blowfish/layouts/partials/header/basic.html:15:67": execute of template failed: template: partials/header/basic.html:15:67: executing "partials/header/basic.html" at <$logo.Width>: error calling Width: this method is only available for image resources
ERROR render of "section" failed: "/src/mysite-blowfish/themes/blowfish/layouts/_default/baseof.html:20:5": execute of template failed: template: _default/list.html:20:5: executing "_default/list.html" at <partial $header .>: error calling partial: "/src/mysite-blowfish/themes/blowfish/layouts/partials/header/basic.html:15:67": execute of template failed: template: partials/header/basic.html:15:67: executing "partials/header/basic.html" at <$logo.Width>: error calling Width: this method is only available for image resources
ERROR render of "page" failed: "/src/mysite-blowfish/themes/blowfish/layouts/_default/baseof.html:20:5": execute of template failed: template: _default/single.html:20:5: executing "_default/single.html" at <partial $header .>: error calling partial: "/src/mysite-blowfish/themes/blowfish/layouts/partials/header/basic.html:15:67": execute of template failed: template: partials/header/basic.html:15:67: executing "partials/header/basic.html" at <$logo.Width>: error calling Width: this method is only available for image resources
Total in 1741 ms
Error: error building site: render: failed to render pages: render of "home" failed: "/src/mysite-blowfish/themes/blowfish/layouts/_default/baseof.html:20:5": execute of template failed: template: index.html:20:5: executing "index.html" at <partial $header .>: error calling partial: "/src/mysite-blowfish/themes/blowfish/layouts/partials/header/basic.html:15:67": execute of template failed: template: partials/header/basic.html:15:67: executing "partials/header/basic.html" at <$logo.Width>: error calling Width: this method is only available for image resources

```

**To Reproduce**
1. Clone my repository
2. load blowfish with `git submodule update --init --recursive`
3. run blowfish-tools and select `Generate the static site with Hugo` or run `hugo build` or run a github action to build with v0.133.1
4. See error above

I was hoping for a clean build. The repository previously built under 0.128.2. Reverting hugo leads to the same error. I have not yet worked out how to revert to a previous blowfish submodule to test against that. (any help with this appreciated! - I don't really know what I'm doing with git)

This is true for hugo v0.133.1
 - in a podman container
 - using the latest blowfish-tools
 - running a github action for hugo build/deploy

All of which were working prior to upgrade to latest blowfish.

Blowfish was updated using blowfish tools, so I am not exactly sure how to check the version of that. (shows as blowfish@471704e in the repository)

**Comment by tetricky** [comment]
....creating a new site and building it, means that the current blowfish version, and hugo 0.131.1 do successfully build a site.

So I am closing this, because it's something in my files...not in blowfish.

If anyone has any pointers what to look for (I think I'm having a problem with images.....not sure that blowfish tools is creating the relative url locations) based on the errors, I'd appreciate it. Nevertheless. This is not a blowfish issue.

**Comment by nunocoracao** [comment]
@tetricky there was a breaking change in moving all author parameters to params.authors check if it's related to thst

**Comment by tetricky** [comment]
I believe it was.

If I alter those (author) settings with blowfish-tools, even the latest version, it produces the old form settings in config.

Doing it manually, avoids the error.
