### ISSUE TITLE
New list view - Cards

### ISSUE THREAD

**Issue by nunocoracao** [nunocoracao/blowfish#177]
**Is your feature request related to a problem? Please describe.**
Some users have very visual content (e.g. designers) and want a new way to display lists of contents

**Describe the solution you'd like**
Implement a card view for lists similar to themes like [dream](https://github.com/g1eny0ung/hugo-theme-dream). Implement it in a way that becomes the basis for implementing new list views in the future.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by spelucin** [comment]
I was thinking about this the other day. Would be a great implementation

**Comment by nunocoracao** [comment]
@spelucin created a branch if you want to contribute. This one might be tricky. Usually, themes don't supply many variants of UX in order to prevent code from becoming super complex so I need to consider how to avoid a spaghetti situation.
