### ISSUE TITLE
Adjustable textwidth

### ISSUE THREAD

**Issue by dbrg77** [nunocoracao/blowfish#18]
Hello,

Thanks for creating the awesome theme.

I have a feature request. Like discussed in the Discussion #10 , I think it would be great to provide a setting to change the width of the text area. Not really sure about the proper name of this, I'm using `latex` nomenclature `textwidth`, but maybe it should be called `content width`, `element width`?

The narrow `textwidth` like the `profile` style layout is good for listing and reading on the phone, but the wide `textwidth` similar to the `project` style layout is good for reading serious article and on desktop computer.

Thanks!

Regards,
Xi

**Comment by nunocoracao** [comment]
@dbrg77 after studying this a little bit I've decided to not move forward with it. There is no way to make this value something configurable by the user without sacrificing some of the design aspects of the theme. I feel that users which want to overwrite this can ultimately create custom HTML for their use-case. Sorry, it seemed simple the first time I looked into it.
