### ISSUE TITLE
Shortcodes and Tailwind

### ISSUE THREAD

**Issue by ChrisCochrun** [nunocoracao/blowfish#181]
I can't seem to find a way to include tailwind utility classes in my shortcodes. I've poked around in your theme and see it all setup, I suppose I'm just wondering, do things have to be built within your theme in order for tailwind classes to be picked up? So that would mean all shortcodes created from the consumer of the theme wouldn't be able to utilize tailwind classes.

**To Reproduce**
1. Install Hugo
2. Install blowfish
3. Make a shortcode
4. Try to apply shortcode with a tailwind css
5. nothing...

**Desktop (please complete the following information):**
 - OS: Nixos
 - Browser firefox

**Hugo & Blowfish versions**
Hugo v0.104.3
Blowfish v2.4.5

**Edit**
Awesome theme btw. This almost EXACTLY what I was looking for!

**Comment by ChrisCochrun** [comment]
Doh! I can't believe I didn't see this! 
https://nunocoracao.github.io/blowfish/docs/advanced-customisation/#building-the-theme-css-from-source

Clearly if I RTFM I'd know how to do what I want to do. Sorry if I wasted your time!

**Comment by nunocoracao** [comment]
No issues 👍
