### ISSUE TITLE
RSS support Follow 

### ISSUE THREAD

**Issue by Weaxs** [nunocoracao/blowfish#1817]
**Is your feature request related to a problem? Please describe.**
I want to support fead claim  in rss.xml for Follow.app
https://github.com/RSSNext/follow

**Describe the solution you'd like**
Add following id in RSS
![image](https://github.com/user-attachments/assets/4613d32a-76a9-4527-83d8-0cf2a4ce6fa0)

**Describe alternatives you've considered**

**Additional context**

**Comment by StandingPadAnimations** [comment]
You can just override the RSS template by copying `themes/blowfish/layouts/_default/rss.xml` to the `layouts` folder and add whatever ID needed, the theme itself doesn't need to be changed

**Comment by Weaxs** [comment]
> You can just override the RSS template by copying `themes/blowfish/layouts/_default/rss.xml` to the `layouts` folder and add whatever is needed, the theme itself doesn't need to be changed

I have done it  in my project, but I thought maybe more people who perfer RSS will need this ?  👀

[RSSNext/follow](https://github.com/RSSNext/follow) is already 15k star.
