### ISSUE TITLE
Make "Show More" in recent articles part of i18n dictionary

### ISSUE THREAD

**Issue by oleg-rom** [nunocoracao/blowfish#182]
Hi! I can't find where to translate "Show more" sentence? Which shortcode is used? I haven't found this string in any of the language files listed. Could you help please?

if I use this format, for instance:
```
- id: home
  translation: "Home"
```
then I get an error, and still can't translate "Show more" to my language.

**Comment by nunocoracao** [comment]
Show more is not part of the translations feature. Need to updated it. Will use this ticket to implement the change

**Comment by oleg-rom** [comment]
Thanks a lot!!!
