### ISSUE TITLE
update using git failed on Windows

### ISSUE THREAD

**Issue by xuchengpeng** [nunocoracao/blowfish#1842]
**Describe the bug**

When [updating blowfish with git](https://blowfish.page/docs/installation/#update-using-git): `git submodule update --remote --merge`，I get the error:

```
Updating f037da31..3a50c14d
error: invalid path 'exampleSite/content/users/Handbook on Teaching Empirical Software Engineering: Online Materials/feature.jpg'
error: invalid path 'exampleSite/content/users/Handbook on Teaching Empirical Software Engineering: Online Materials/index.it.md'
error: invalid path 'exampleSite/content/users/Handbook on Teaching Empirical Software Engineering: Online Materials/index.ja.md'
error: invalid path 'exampleSite/content/users/Handbook on Teaching Empirical Software Engineering: Online Materials/index.md'
error: invalid path 'exampleSite/content/users/Handbook on Teaching Empirical Software Engineering: Online Materials/index.zh-cn.md'
fatal: Unable to merge '3a50c14d2fac08ac58c728463b3098da81198428' in submodule path 'themes/blowfish'
```

**To Reproduce**

Run: `git submodule update --remote --merge`

**Expected behavior**

Update blow successfully.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Hugo & Blowfish versions**

hugo v0.138.0
blowfish v2.78.0
git version 2.47.0

**Comment by xuchengpeng** [comment]
OK, related PR here #1839

**Comment by RobDaPraia** [comment]
yes same problem here on windows


2024-11-18 19:42:18.429 [info] From https://github.com/nunocoracao/blowfish
 * branch              main       -> FETCH_HEAD
error: invalid path 'exampleSite/content/users/Handbook on Teaching Empirical Software Engineering: Online Materials/feature.jpg'
error: invalid path 'exampleSite/content/users/Handbook on Teaching Empirical Software Engineering: Online Materials/index.it.md'
error: invalid path 'exampleSite/content/users/Handbook on Teaching Empirical Software Engineering: Online Materials/index.ja.md'
error: invalid path 'exampleSite/content/users/Handbook on Teaching Empirical Software Engineering: Online Materials/index.md'
error: invalid path 'exampleSite/content/users/Handbook on Teaching Empirical Software Engineering: Online Materials/index.zh-cn.md'

**Comment by nunocoracao** [comment]
Fixing this in v2.80.0
