### ISSUE TITLE
⚡️Page level partialCached for extend-head.html

### ISSUE THREAD

**Issue by spelucin** [nunocoracao/blowfish#185]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement a dataLayer, so I can send data about article readership to Google Tag Manager, but since the extend-head.html partial is site cached, I can't use page level variables.

**Describe the solution you'd like**
Change the caching level to Page. This might impact performance, so maybe there is a better way to send page level parameters to the header.

**Describe alternatives you've considered**
A full Google Tag Manager integration would be great. It would be similar to the GA one, but sending a dataLayer object to GTM would be nice.

**Additional context**
I might be able to help with this one, I just didn't want to make a fork because I'm not sure what to consider while integrating GTM to this theme.

**Comment by nunocoracao** [comment]
Hello @spelucin I'll take a look but it will require some time. I've created a branch to test this feature. Feel free to open a PR to that branch if you want to we can then test the impacts of it and decide what needs to be changed. 
Also a read of https://gohugo.io/functions/partialcached/ might provide some context on how to extend the partialCached function VS having a simple partial command.

**Comment by nunocoracao** [comment]
if you plan to submit a PR please do so to `dev` branch

**Comment by nunocoracao** [comment]
@spelucin I won't have time to pick this up and no other user showed interest in this change. Closing the ticket for now. Feel free to re-open if you want to submit a PR
