### ISSUE TITLE
Blowfish fails to install as a Git Submodule: unable to checkout submodule 'themes/blowfish' and Hugo server not working.

### ISSUE THREAD

**Issue by pranavnasrani** [nunocoracao/blowfish#1856]
**Describe the bug**
While downloading blowfish according to installation guides, the blowfish download fails with fatal error 
`fatal: unable to checkout submodule 'themes/blowfish'`
All dependencies have been installed

/themes/blowfish empty along with all other folders.
While starting the server, nothing showed up with a Page Not Found error.

While testing site, error 

**To Reproduce**
1. Install Hugo; latest version from official release binaries
2. run `hugo newsite pranavblogs` to create a site
3. change directory into the new site: `cd pranavblogs`
4. run 'git init`
5. attempt to download and add the github submodule using command:
 `git submodule add -b main https://github.com/nunocoracao/blowfish.git themes/blowfish`
6. attempt to start server after replacing toml files using `hugo server -t blowfish`

**Expected behavior**
Successful clone from github, with no errors. Contents in the cloned folders. Base theme webpage loading as does with other themes such as Paige, Terminal, etc.

**Screenshots**
![image](https://github.com/user-attachments/assets/9161b433-d354-424f-89f9-b8fa823bdc64)
![image](https://github.com/user-attachments/assets/1da2905b-8e97-427e-9d65-458c38a0bcab)

The last line in this terminal snippet displays the error.
The Page not found error is also depicted.

Please do help with thise error as this theme is really cool. I am not aware if this a mistake on my part, and I would be very happy to get advice on how to do this right. have been trying for many days and hours.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 Home]
 - Browser [chrome]
 - Version [chrome - 131.0.6778.86; windows - 23h2 Build no. 22631.4541]

**Hugo & Blowfish versions**
Latest releases from respective websites. 
`hugo v0.139.2-770f548b47b39e6f0fd4da1cc80552024e5829e1 windows/amd64 BuildDate=2024-11-23T15:33:51Z VendorInfo=gohugoio`

**Additional context**
The /themes/blowfish folder is also empty. After downloading the recommended downloading toml files, the webpage still shows page not found. I have tested this with the terminal theme and other themes, and they work just fine.

**Comment by pranavnasrani** [comment]
EDIT: Tried the blowfish-tools (npx) as recommended on blowfish.page.
![image](https://github.com/user-attachments/assets/55a40c15-c640-4722-93d6-ec7ee2636cbe)
I think the same issue is being encountered. Even the blowfish tools use the same command to download and clone the theme, and since that fails, it isn't able to locate any required files (cloning fails), hence the whole command fails. This shows its not specific to the github submodules.

**Comment by nunocoracao** [comment]
Fixing this in v2.80.0

**Comment by pranavnasrani** [comment]
@schneekluth @nunocoracao Thank you! This really helps
