### ISSUE TITLE
Error when building site - 404/markdownify template errors.

### ISSUE THREAD

**Issue by emacsified** [nunocoracao/blowfish#219]
**Describe the bug**
The site runs okay in dev mode (`hugo server -D`), but when calling `hugo` or `hugo server`, gives an error relating to the 404 page

**To Reproduce**
1. With my existing code, call `hugo` or `hugo server` and the below error appears: (line breaks added by me for readability)
```
Start building sites … 
hugo v0.105.0+extended darwin/arm64 BuildDate=unknown
Error: Error building site: render of "404" failed: "/var/folders/2q/c514k34n4bd3c7kqj4jbd0kc0000gq/T/hugo_cache/modules/filecache/modules/pkg/mod/github.com/nunocoracao/blowfish/v2@v2.9.0/layouts/_default/baseof.html:31:9": 
execute of template failed: template: 404.html:31:9: executing "404.html" at <partial $header .>: 
error calling partial: "/var/folders/2q/c514k34n4bd3c7kqj4jbd0kc0000gq/T/hugo_cache/modules/filecache/modules/pkg/mod/github.com/nunocoracao/blowfish/v2@v2.9.0/layouts/partials/header/basic.html:20:125": 
execute of template failed: template: partials/header/basic.html:20:125: executing "partials/header/basic.html" at <markdownify>: 
error calling markdownify: runtime error: invalid memory address or nil pointer dereference
```

**Expected behavior**
The site should build or serve locally as normal.

**Screenshots**
See code snippet above.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6, `go version go1.18.3 darwin/amd64`, `hugo v0.105.0+extended darwin/arm64 BuildDate=unknown`
 - Browser: N/A - Terminal error, either locally or in CICD builds.
 - Version: - `go version go1.18.3 darwin/amd64`, 

**Hugo & Blowfish versions**
`hugo v0.105.0+extended darwin/arm64 BuildDate=unknown`, go.mod: `require github.com/nunocoracao/blowfish/v2 v2.9.0 // indirect`

**Additional context**
I can provide code snippets etc upon request.

**Comment by emacsified** [comment]
NB: this is a new hugo project created following the steps in the README, using go/hugo, not submodules.

**Comment by nunocoracao** [comment]
Hello @emacsified, just did a quick run-through of the Hugo installation with no issues. I am on the same version/system as you are. So the error doesn't seem to happen during a fresh installation. Could you provide a repo or something so that I can check the code?

**Comment by emacsified** [comment]
Thanks @nunocoracao , appreciate you helping out here :) 

There's a repo here - There's practically no content added, was just trying this out

https://gitlab.com/emaxxx/ashmcbri.de

**Comment by nunocoracao** [comment]
Hello @emacsified, I've cloned the repo and figured it out. Your front matter metadata in all .md files is wrong for what is expected of Hugo (this is not even related to the theme). Take a look at the docs and all examples in this repo and the other users with sites in production.

**Comment by emacsified** [comment]
Thankyou so much. I'm just a moron apparently.. It being accepted in `hugo server -D` is what confused me as I assumed it was consuming the front matter without issue.
Thankyou!

**Comment by emacsified** [comment]
@nunocoracao  Actually... Can you clarify what the issues are? My front matter is in TOML and should be fine from what I can see, though the examples you provide are in YAML, I'm not seeing exactly what's wrong with the frontmatter?

**Comment by emacsified** [comment]
Identified the issue - both my posts are marked as draft, so `hugo` and `hugo server` skip over them entirely and don't parse. The theme isn't set up to handle not having _any_ posts (inc a homepage _index.md when using the hero) so fails to render anything :) 

Undefined behaviour but this is theme-specific I think! :)

**Comment by emacsified** [comment]
Sorry - I think you're misunderstanding. Mark both of those posts as not being drafts, and the theme works fine. The exact same markdown is now working for me, with the posts _not_ being marked as drafts :)

**Comment by nunocoracao** [comment]
I figured it out... you cannot have an "empty" content folder apparently. If you mark all articles as drafts and try to render the site without the draft there will be an empty folder and I guess Hugo doesn't like it... Nothing to do with the theme. I ran into a similar problems with Taxonomies.
