### ISSUE TITLE
[issue build] fatal: could not read from remote repository.

### ISSUE THREAD

**Issue by miawithcode** [nunocoracao/blowfish#23]
Hi there,
couple of days ago, I use this wonderful theme installed using hugo module, and it works fine. I finished my website and had it deployed on GitHub Pages. Today when I try to update some content and run the command `hugo server` to see the changes, but it reports an error:

```
hugo: downloading modules …
go: github.com/nunocoracao/blowfish@v1.1.1: reading github.com/nunocoracao/blowfish/go.mod at revision v1.1.1: git ls-remote -q origin in /var/folders/cd/8tp492z54j9g131qntqk4d780000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/cache/vcs/416a66ef4f2f18f5dcdf86a4ba8bc9347aadb37895929ff96e119b02dcd2588d: exit status 128:
        fatal: 'origin' does not appear to be a git repository
        fatal: could not read from remote repository

        Please make sure you have the correct access rights and the repository exists
hugo: collected modules in 3305 ms
Error: failed to download modules: failed to execute 'go [mod download]': failed to execute binary "go" with args [mod download]: go: github.com/nunocoracao/blowfish@v1.1.1: reading github.com/nunocoracao/blowfish/go.mod at revision v1.1.1: git ls-remote -q origin in /var/folders/cd/8tp492z54j9g131qntqk4d780000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/cache/vcs/416a66ef4f2f18f5dcdf86a4ba8bc9347aadb37895929ff96e119b02dcd2588d: exit status 128:
        fatal: 'origin' does not appear to be a git repository
        fatal: could not read from remote repository

        Please make sure you have the correct access rights and the repository exists。
 *errors.errorString
``` 

It confused me cause `hugo server` works fine two days ago and I follow every step of installing using hugo in the [docs](https://nunocoracao.github.io/blowfish/docs/installation/#install-using-hugo). I wonder what's wrong.

**Comment by nunocoracao** [comment]
Hello @miawithcode may I ask you to try again and let me know if the problem persists? I tried to reproduce the problem on my end and everything seems to be working ok.

**Comment by miawithcode** [comment]
Hello @nunocoracao , I retry the command `hugo server` and I'm still getting the error. Then I create a whole new repository and try to redo the installation steps. This time it still reports the error `"fatal: could not read from remote repository" `, I can not successfully install the theme to a brand new project.

go version
`go version go1.19.1 darwin/arm64`

hugo version
`hugo v0.104.0+extended darwin/arm64 BuildDate=unknown`

opration system
`macOS Monterey 12.5 `

**Comment by miawithcode** [comment]
I fixed but still don't know what caused the issue. I delete the repository in my local machine and reclone the repository in my GitHub to local machine and there is no error reported.

I'll closed this issue.

Thank for your great work.
