### ISSUE TITLE
Buymeacoffee integration

### ISSUE THREAD

**Issue by nunocoracao** [nunocoracao/blowfish#236]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rpstreef** [comment]
it seems the coffee icon does not do the default left alignment or when the configuration is set to 'Left'

**Comment by nunocoracao** [comment]
@rpstreef thanks, could you open a separate ticket with details on the bug? thanks
