### ISSUE TITLE
Article view

### ISSUE THREAD

**Issue by jawaylog** [nunocoracao/blowfish#24]
Hello, thank you for making a beautiful theme. About the home page article view. After reading the document, it seems that it needs to be displayed and used with firebase project. But here in China, Google can't use it. Excuse me, is there any way to display the article view? Thank you.

![1664199196036](https://user-images.githubusercontent.com/87666210/192290254-88c0cf23-fff8-4ead-b8b0-03f99af7a849.jpg)

**Comment by nunocoracao** [comment]
Hello @jawaylog, you just need to drop a feature* image (jpg or png) under your article folder. You can check the source code for my homepage to see how I did it. I'll add details to the documentation on that. Will use this ticket to track that.

**Comment by jawaylog** [comment]
Thank you for your answer. It has been successful, which is great.
