### ISSUE TITLE
:sparkles: Empty `hero` div shown in lists/articles when the `heroStyle` is set to `background`

### ISSUE THREAD

**Issue by Scoty** [nunocoracao/blowfish#266]
**Describe the bug**
Empty `hero` div shown in lists/articles when the `heroStyle` is set to `background`

```
[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background
```  

**To Reproduce**
1. Go to https://nunocoracao.github.io/blowfish/
2. Click on Docs / Serries (any list view).
3. Empty `here` div is present, taking precious space.

**Expected behavior**
No empty `hero` div should be present when the `heroStyle` is set to `background`

**Screenshots**
<img width="592" alt="Screenshot 2022-11-20 at 4 39 37" src="https://user-images.githubusercontent.com/1080487/202880756-fee42ab4-80ee-4623-911b-d5347021e490.png">
<img width="1233" alt="Screenshot 2022-11-20 at 4 43 43" src="https://user-images.githubusercontent.com/1080487/202880757-44067937-468b-434a-b5c5-4f0566bfb196.png">
<img width="1733" alt="Screenshot 2022-11-20 at 4 47 50" src="https://user-images.githubusercontent.com/1080487/202880758-e92d2f4d-421c-4d92-ad04-8c4d9b76a44b.png">
<img width="1697" alt="Screenshot 2022-11-20 at 4 51 06" src="https://user-images.githubusercontent.com/1080487/202880759-70f8199d-1d92-4d68-84aa-d55d6ebd0028.png">

**Desktop (please complete the following information):**
 - OS: MacOS, iOS
 - Browser [chrome]
 - Version [107.xxxxxxx]

**Hugo & Blowfish versions**
Which version of Hugo and Blowfish are you using?
hugo v0.105.0+extended darwin/amd64
blowfish - latest as of 20 Nov 2022

**Additional context**
N/A

**Comment by nunocoracao** [comment]
This is intentional not a bug. Maybe it could be turned into a config?

**Comment by Scoty** [comment]
> 

Yeah a flag to turn it on/off would be perfect

**Comment by nunocoracao** [comment]
Need to consider thus plus some other issues with enhancements to the background logic... also don't want any break changes.

**Comment by nunocoracao** [comment]
Thanks @Scoty
