### ISSUE TITLE
✨ Support for "Iconify" Icons

### ISSUE THREAD

**Issue by AvinashReddy3108** [nunocoracao/blowfish#277]
**Is your feature request related to a problem? Please describe.**
- It's a bit of an annoyance when I have to add the SVG files of the required icons manually into the `assets`
- For some reason, the icons are floored to the bottom of the "container" rather than being centered in Firefox browser (it works fine in Chrome) [could be a separate issue, I think]

**Describe the solution you'd like**
Using the awesome [Iconify](https://iconify.design) framework to handle the icons bundling.

This not only solves the problem of manually adding SVG files (for 99% use cases), but also somehow renders the icons properly (proper alignment) in both Firefox and Chrome in my experience.

**Describe alternatives you've considered**
Unfortunately, N/A.

**Additional context**
This might be possible only as part of the "Advanced Customization" (where we re-compile the theme from source using NPM packages)

**Comment by nunocoracao** [comment]
Not convinced with this one given how iconify handles integrations. aka Might not be the best fit for static generation sites. I will give it a go and test how this could work. I might ask for help testing this @AvinashReddy3108 is that ok?

**Comment by AvinashReddy3108** [comment]
> Not convinced with this one given how iconify handles integrations. aka Might not be the best fit for static generation sites. I will give it a go and test how this could work. I might ask for help testing this @AvinashReddy3108 is that ok?

I'd be happy to be a tester.

**Comment by nunocoracao** [comment]
After reading Iconify documentation I don't think this serves the purpose of static-generated sites or that it would make blowfish easier to use. @AvinashReddy3108 if you get this integrated locally and want to submit a PR in the future happy to review it then.
