### ISSUE TITLE
Custom icon don't change whith Appearance

### ISSUE THREAD

**Issue by Weaxs** [nunocoracao/blowfish#293]
**Describe the bug**
I put some custom icons in asserts/icons folder, but the appearance is not adaptability, such as Screenshots.

**Screenshots**
In dark appearance:
<img width="176" alt="image" src="https://user-images.githubusercontent.com/20680212/206849764-304a26c7-673c-43b0-a9dd-8582976d95a6.png">
In light appearance:
<img width="177" alt="image" src="https://user-images.githubusercontent.com/20680212/206849788-1d2caa4f-dfe4-4b70-81ae-4404b363f14e.png">

**Hugo & Blowfish versions**
Hugo v0.107.0-2221b5b30a285d01220a26a82305906ad3291880+extended
Blowfish github.com/nunocoracao/blowfish/v2 v2.16.0

**Comment by nunocoracao** [comment]
Hello @Weaxs make sure to add the `fill` parameters with the value `currentColor` to the `path` tag in your custom icons. 

Example:
```svg
<path fill="currentColor" d="M318.7 268.7c-....
```

**Comment by Weaxs** [comment]
thanks !
