### ISSUE TITLE
✨Taxonomy add card view

### ISSUE THREAD

**Issue by nunocoracao** [nunocoracao/blowfish#314]

**Comment by nunocoracao** [comment]
Abandoned

**Comment by pfrogond** [comment]
Hi, thanks for this update (2.18), I do realy appreciate it, may I just ask why is this feature marked as abandoned? I would realy like it as it is disrupting the style of my page that taxonomy cant have the same appearance as list (cardView).

**Comment by nunocoracao** [comment]
I wanted to get the other ones out and didn't find a good solution for this one... if this is that important let's reopen it. Do you have a suggestion for it? Or could you submit a PR?

**Comment by pfrogond** [comment]
I don't have any code at hand, but the idea was to make the **taxonomy** page look like **list** and now also **term** pages (mainly enable cardView for which there is already an option, but no real code in the _taxonomy.html_). I can achieve this result by deleting the _taxonomy.html_ file in the _theme folder_, as than any **taxonomy** page just looks like **list** page, but than I cant use the _showTermCount_ option for **taxonomy** as it no longer exists.

**Comment by nunocoracao** [comment]
@pfrogond sorry but I don't have time for this one and I don't think it's a high priority one. If it gets more votes I'll reconsider. Also, if you want to submit a PR for it would be even better.

**Comment by nunocoracao** [comment]
Change of plans... done in https://github.com/nunocoracao/blowfish/pull/356
