### ISSUE TITLE
:sparkles: Adding TypeIt as shortcode

### ISSUE THREAD

**Issue by mztiq** [nunocoracao/blowfish#337]
**Describe the solution you'd like**
I'd like to have a simple way of using TypeIt.
There are other themes that implement TypeIt as Shortcode, such as [LoveIt](https://hugoloveit.com/theme-documentation-typeit-shortcode/), it would be great to have that implemented into Blowfish too.

**Describe alternatives you've considered**
I tried to integrate TypeIt by customizing a Partial but couldn't exactly figure out how (see [Link](https://loisvelasco.is-a.dev/) for reference).

**Comment by MilesPernicious** [comment]
The TypeIt JS library is rather complex, but it excels when you need to customize precise timing for each character.  That would be rather difficult to make a shortcode for and tbh, it is way overkill for what most people who want this effect need.

In fact, the shortcode that the themes such as "LoveIt" "LeaveIt" "DoIt" etc use only implement a very limited portion of the TypeItJS library. The effects used in the [source for the link you referenced](https://github.com/loiSvelasco/blog/blob/258a55a860c113c20e89b6ab56a549dbd4eb31cf/loisrantsblog/layouts/partials/home/profile.html#L29) wouldn't even be possible using the shortcodes from those themes.

If you're looking for a simple typewriter effect, I'd suggest something from one of the effects listed here: https://css-tricks.com/snippets/css/typewriter-effect/ and avoid typeitJS unless you truly need the complexity of it.

**Comment by nunocoracao** [comment]
Hello @mztiq, I agree with @MilesPernicious this one would be complex. My proposal, let's keep this ticket open to check if more people are interested in this and possibly discuss a solution for it. The custom implementation looks really good and it should be easy enough to pull off. I will propose a solution for a partial here when I have time. If one of you wants to propose it first happy to help with the implementation.

**Comment by mztiq** [comment]
That's fine with me, thanks @MilesPernicious and  @nunocoracao.

**Comment by nunocoracao** [comment]
change of plans... having a go at this... starting simple and we can evolve
