### ISSUE TITLE
🐛 `article.sharingLinks` option doesn't work

### ISSUE THREAD

**Issue by maciejopalinski** [nunocoracao/blowfish#361]
**Describe the bug**
`article.sharingLinks` option doesn't work

you can disable it by setting it to `false`, but changing items in the array doesn't change the displayed sharing links
they always stay like that, regardless of the contents of the `sharingLinks` array:

![image](https://user-images.githubusercontent.com/44976946/210155939-4fb3b365-3482-4208-b9f4-56a9f34dc2d3.png)

**To Reproduce**
- goto `config/_default/params.toml`
- in `[article]` section change to (for example): `sharingLinks = [ "linkedin", "twitter" ]`

**Expected behavior**
It shouldn't display links other than the ones provided.

**Hugo & Blowfish versions**
Hugo: `hugo v0.108.0+extended linux/amd64`
Blowfish: `v2.22.0 (commit 99cb56f9f5a53eaef9b9a1d46ea3115736f363f3)`

**Comment by nunocoracao** [comment]
Fixed in https://github.com/nunocoracao/blowfish/pull/366 merged to dev... will be available in the next release. 
Thanks @maciejopalinski
