### ISSUE TITLE
🐛 header broken without logo on mobile

### ISSUE THREAD

**Issue by maciejopalinski** [nunocoracao/blowfish#363]
**Describe the bug**
When `logo` is not defined, header looks weird on mobile.

![image](https://user-images.githubusercontent.com/44976946/210178268-29add82a-03bd-4907-8bed-a8676ea6680a.png)

**Expected behavior**
You should see something like this:
![image](https://user-images.githubusercontent.com/44976946/210178281-ac03bad4-7e02-4b2e-9537-155b206ce047.png)

**Hugo & Blowfish versions**
Hugo: `hugo v0.108.0+extended linux/amd64`
Blowfish: `v2.22.0 (commit 99cb56f9f5a53eaef9b9a1d46ea3115736f363f3)`

**Comment by nunocoracao** [comment]
Merged into dev will be available in the next release
