### ISSUE TITLE
:bug: Hero Layout - Bold text and header color is black

### ISSUE THREAD

**Issue by BrodyB** [nunocoracao/blowfish#365]
**Describe the bug**
When using the hero layout on a page, bold text and headers are colored black, whereas the normal text is all white. This makes headers difficult to read against dark backgrounds. This does not change whether in dark or light modes.

**To Reproduce**
1. Create a page using the "background" layout
2. Add a heading, normal text, and some bold text to the page's markdown content.
3. Observe the generated page
4. Switch the layout to use the "hero" layout
5. Observe that the bold text and header have switched from white to black

**Expected behavior**
Headers and bold text should be white to match normal body text.

**Screenshots**
![Screenshot 2023-01-01 at 12 31 37 PM](https://user-images.githubusercontent.com/2968043/210183988-63823f2a-d43c-41c7-ad38-00088678e609.png)

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.0.1
 - Browser Firefox 108.0.1, Safari 16.1

**Hugo & Blowfish versions**
 - Blowfish v2.22.0 [commit 99cb56f]
 - Hugo v0.109.0+extended

**Comment by nunocoracao** [comment]
@BrodyB can you share the repo with the code that gives you this behavior?

**Comment by BrodyB** [comment]
Sure thing! The layout in `params.toml` is set to "background" here, but if I switch it to "hero" I see the bug surface.

https://github.com/BrodyB/BrodySite

**Comment by nunocoracao** [comment]
@BrodyB repo doesn't exist

**Comment by BrodyB** [comment]
> @BrodyB getting a 404 with that link

Apologies! I didn't catch that it was set to private. Should work now!

**Comment by nunocoracao** [comment]
fixed in https://github.com/nunocoracao/blowfish/pull/385 will be available in the next release
