### ISSUE TITLE
💄 Summary is constrained to a specific width in list view

### ISSUE THREAD

**Issue by insidemordecai** [nunocoracao/blowfish#379]
I have tried out not using feature images and noticed that in lists (posts, recent articles...), the title can cover the entire card but the summary seems to be limited to a specific width. 

1. Create post with no feature image
2. Add a long summary or body text
3. View home page or blog/posts page

![image](https://user-images.githubusercontent.com/39312305/210521219-b8fb6353-6ab5-4064-bdf7-770e92709596.png)

This is fine if one makes use of feature images but it makes the list seem more left-aligned than one would like esp in the recent article section where other components of the home page are centred.

**Comment by insidemordecai** [comment]
Brain dump: 
Maybe the summary width could be adaptive or larger but that could make things too wide which might not look as good. So maybe  the entire card could have a narrower width but that could complicate things 

A possible solution would be having another list view similar to how the card view has `card view with full width` and `card view with constrained width`

**Comment by nunocoracao** [comment]
@insidemordecai not sure if that isn't too much configuration at this stage... would you be up to help with a PR?

**Comment by nunocoracao** [comment]
Added `list.constrainItemsWidth` will be available in the next release

**Comment by nunocoracao** [comment]
solved in https://github.com/nunocoracao/blowfish/pull/384

**Comment by insidemordecai** [comment]
The new width when using the `list.constrainitemsWidth` is actually a slight but pretty decent change. Thanks for the update.
