### ISSUE TITLE
Clarification on how to create custom color themes

### ISSUE THREAD

**Issue by mirceanton** [nunocoracao/blowfish#398]
**Is your feature request related to a problem? Please describe.**

I am trying to customize the color theme for [my website](https://mirceanton.com) but I am finding myself having a hard time figuring out which color is used where and how to create the shades for the transparency.

I am mostly going with trial and error at this point, changing a color and then looking for the elements that change.

**Describe the solution you'd like**

I would like some clarification as to which colors are used where and how could I generate the transparency shades.

**Describe alternatives you've considered**

???

**Additional context**

I've been wanting for a while to change the colors to a darker palette but I did not really like any of the built-in ones. I have implemented Giscus comments on my blog and I wanted to change the palette to make the iframe fit in better, so I am trying to implement like a "github-dark" theme or something.

Maybe it would be useful for others as well to have some more variety on the color schemes? Some of the more common ones, like Darcula, Github dark, Github light etc.

**Comment by nunocoracao** [comment]
Hey @mirceanton regarding what is used where, you can check the tailwind files, or other css files to get that info. There is basically three colora: neutral, primary, and secondary. That's it.

Regarding generating the variants, I had built a tool for that to help me generate the themes in blowfish...  https://github.com/nunocoracao/fugu 

The tool was for my personal use, so it has no docs. It's a one line command that gets 3 hex colora and generates a css. If you think it's useful I can try to wrap up the project. It should be good for your use-case.

**Comment by mirceanton** [comment]
I managed to create a color theme by tweaking your tool a bit, thank you! I also made a PR to add a quick-start guide showing a command example and the setup

**Comment by nunocoracao** [comment]
Thanks @mirceanton shall we bundle it with blowfish?

**Comment by mirceanton** [comment]
@nunocoracao Not sure what to say.

While I do think it can be useful to generate a starting point for a theme, I do think (and correct me if I am wrong) that most people use the theme as a submodule in the `themes/` directory.

That being said, if we add it to the repo and add a script to run it with `npm`, you won't be able to run it from the root of your website repo, which I think can get a bit confusing, especially for new users. I think it would be best to keep it as an external repo and just mention it in the docs.

**Comment by nunocoracao** [comment]
Makes sense. Let's keep them separated. I will consider mentioning the repo in Blowfish's docs.
