### ISSUE TITLE
Too much empty space when TOC is disabled

### ISSUE THREAD

**Issue by MilesPernicious** [nunocoracao/blowfish#401]
See screenshot:
![image](https://user-images.githubusercontent.com/30605984/211144138-d7837e19-e587-4eb5-8323-76b0458aee2f.png)

This can be solved by dropping the max-w-prose class when TOC is disabled.

![image](https://user-images.githubusercontent.com/30605984/211144415-830dd1ef-1248-4f88-93aa-abff6e843677.png)

Result:
![image](https://user-images.githubusercontent.com/30605984/211144340-2918abef-88aa-4666-8a67-300c512011e0.png)

**Comment by nunocoracao** [comment]
Hello @MilesPernicious I'll be closing this one. The theme works this way to improve readability. Having a full-width makes text harder to read. You can always override it using your own overlays or css.

**Comment by MilesPernicious** [comment]
I would argue that it's hard to read due to the alignment. Perhaps instead there can be a way to center the text within the flexbox so it doesn't look so jarring and still keeping the width

**Comment by nunocoracao** [comment]
I understand the advantage of Hugo and Blowfish is that every partial can be extended and overridden to each custom use case. For Blowfish, I implemented something like that a couple of versions ago and was not happy with the results. If you would like to understand more about the current implementation here are a couple of links:

https://github.com/tailwindlabs/tailwindcss/discussions/2495

https://tailwindcss.com/docs/max-width#reading-width
