### ISSUE TITLE
:sparkles: Page indicator in navigation bar

### ISSUE THREAD

**Issue by mirceanton** [nunocoracao/blowfish#412]
**Is your feature request related to a problem? Please describe.**
I find it counter intuitive that the navbar does not update based on the currently active page.

**Describe the solution you'd like**

I think it would be useful if the navbar element for the currently active page would be somehow highlighted, maybe by changing the font color to the accent color, or by increasing the font weight.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mirceanton** [comment]
I think the same thing is valid for the TOC in blog posts as well, but maybe that should be a different issue/feature request.

**Comment by nunocoracao** [comment]
@mirceanton please open a new ticket for the TOC change.

**Comment by mirceanton** [comment]
@nunocoracao #413 created

**Comment by nunocoracao** [comment]
@mirceanton thanks
