### ISSUE TITLE
:sparkles: Progress Indicator in TOC

### ISSUE THREAD

**Issue by mirceanton** [nunocoracao/blowfish#413]
Is your feature request related to a problem? Please describe.

I think it would be a nice addition to this theme if the TOC that is displayed on the side of posts would indicate the current section.

Describe the solution you'd like

Something similar to the way it is done in mkdocs, where the TOC is highlighting the current section should do the trick.

Describe alternatives you've considered
N/A

Additional context
N/A

**Comment by nunocoracao** [comment]
@mirceanton share the links to the example you mentioned

**Comment by mirceanton** [comment]
@nunocoracao one example would be here: https://yakworks.github.io/docmark/extensions/pymdown/
