### ISSUE TITLE
⏪️ revert image processing behaviour (.fill to .resize)

### ISSUE THREAD

**Issue by mirceanton** [nunocoracao/blowfish#418]
**Describe the bug**

On my [blog](https://mirceanton.com/posts), the featured images of blog posts seem to get cropped out of view:

**Expected behavior**

The image would be scaled to fit inside the viewport, maintaining the aspect ratio.

**Screenshots**

![image](https://user-images.githubusercontent.com/28601784/211419321-c7ecbde6-5711-4ede-a7ed-1ad163ed632c.png)

**Hugo & Blowfish versions**

Hugo version `0.107.0`
Blowfish version `2.24.0`

**Additional context**

If this is the actual expected behavior, maybe some guidelines on featured image sizing would be beneficial.

**Comment by nunocoracao** [comment]
Hey @mirceanton 

Can you check https://github.com/nunocoracao/blowfish/issues/336

It might help solve your problem...

Having said this I might consider going back to the resize VS fill... as the default as multiple users are having a hard trouble with this. And doesn't make much sense for the default to not be what most users expect/want. 

Let me know if the hack I suggested on that ticked is the outcome you are looking for.

**Comment by mirceanton** [comment]
@nunocoracao Thank you! It mostly fixed it. I copied the `article-link/` partials directory to my local partial layouts and made the modifications, as well as setting `imaging.anchor: 'Center'` in my `config.yaml` file.

However, this solution makes me a bit worried about breaking something in the future by having these layouts overridden like this (maybe a partial gets moved or renamed).

**Comment by nunocoracao** [comment]
Leave this open will need to work on this and revert the fill command to resize. Did you test if that has the intended outcome?

**Comment by mirceanton** [comment]
Yes, it fixed it.

This is the cardview layout on the home page:
![image](https://user-images.githubusercontent.com/28601784/211514537-68b87fdd-3bfc-41ce-85a6-d0872a0f5c98.png)

And this is the listview layout in the `/posts` page:
![image](https://user-images.githubusercontent.com/28601784/211514632-11fbd699-3f6d-41ec-b792-1b8ee01fc879.png)

**Comment by nunocoracao** [comment]
@mirceanton could you check if just adding 

```
[imaging]
  anchor = 'Center'
  ```

fixes the problem? aka without the overrides?

**Comment by mirceanton** [comment]
@nunocoracao it does not. I tried that before doing the overrides. It keeps the same "crop level", it's just that the image is now centered instead of showing only the left part of the cropped image.

**Comment by nunocoracao** [comment]
@mirceanton can you check if keeping the overrides and removing the

```
[imaging]
  anchor = 'Center'
```

fixes the problem?

**Comment by mirceanton** [comment]
@nunocoracao  here we have a comparison of the 4 scenarios:

1. No anchoring, no overrides

![image](https://user-images.githubusercontent.com/28601784/212196495-76d502ba-4e40-47ba-8442-9dc382e4562b.png)

2. Only `imaging.anchor = Center`

![image](https://user-images.githubusercontent.com/28601784/212196439-175ec2e2-b16a-4700-abef-8163fa8e3b37.png)

3. Only overrides

![image](https://user-images.githubusercontent.com/28601784/212196340-5ce2943a-e2a5-4b56-bfb6-00916ac5d9e2.png)

4. Overrides configured and `imaging.anchor = Center`

![image](https://user-images.githubusercontent.com/28601784/212196141-bbc43f32-8be4-417c-baac-8a2aa2cf3b88.png)

---

To my eyes, 3 and 4 look identical, so I would say that only doing the override is enough

**Comment by nunocoracao** [comment]
My thoughts... reverting the .fill to .resize should fix this.

Cc @chrisbanes will revert the fill to resize in next version FYI

**Comment by mirceanton** [comment]
Yea, I believe that `.Resize` produces a more sensible outcome that an end user might expect out of the box. I think that expecting the featured image of the blog to be resized in order to be shown properly in the card/list item is reasonable and implementing something different should require the user to override, and not the other way around.

But then again, these are only my thoughts and I am not the only user of this theme
