### ISSUE TITLE
:sparkles: Tags open in a new window

### ISSUE THREAD

**Issue by michaeldorner** [nunocoracao/blowfish#420]
**Describe the bug**
I am not sure if it's a bug or a feature (request). In other themes, tag links do not open in a new window. In this wonderful theme, they do. 

**To Reproduce**
Clicking on a tag opens a new window for the tag page.

**Expected behavior**
Clicking on a tag does not open a new window for the tag page.

**Desktop (please complete the following information):**
I assume all OS and browsers but tested with macOS and Chrome, Safari, Firefox

**Hugo & Blowfish versions**
Hugo v0.104.3, Blowfish v2.24.0

**Additional context**
Can we make it maybe configurable for supporting both behaviours?

**Comment by michaeldorner** [comment]
What about something like in `basic.html`

```
{{/* Output taxonomies */}}
{{ if .Params.showTaxonomies | default (.Site.Params.article.showTaxonomies | default false) }}
<div class="flex flex-row flex-wrap items-center" style="margin-top:1rem">
  {{ range $taxonomy, $terms := .Site.Taxonomies }}
  {{ if and (not (eq $taxonomy "authors")) (not (eq $taxonomy "series"))}}
  {{ if (gt (len ($context.GetTerms $taxonomy)) 0) }}
  {{ range $context.GetTerms $taxonomy }}
  <a href="{{ .RelPermalink }}">
    <span  class="mr-0">{{ partial "badge.html" .LinkTitle }}</span> 
  </a>
  &nbsp;  
  {{ end }}
  {{ end }}
  {{ end }}
  {{ end }}
</div>
{{ end }}

{{ end }}
```

**Comment by nunocoracao** [comment]
https://github.com/nunocoracao/blowfish/pull/435

**Comment by michaeldorner** [comment]
Thanks a lot!
