### ISSUE TITLE
🌟 Expanding the collection of shortcodes for the theme

### ISSUE THREAD

**Issue by mirceanton** [nunocoracao/blowfish#425]
**Is your feature request related to a problem? Please describe.**

When writing for my blog, there are a few shortcodes which I would have liked to have available, but aren't currently. These include:

- gallery: show all the pictures inside a given directory (with a regex filter for the name)
- carousel: image slider (same as gallery for images source)
- github repo: preview of a github repo with language and forks and stars details

**Describe the solution you'd like**

Create the mentioned shortcodes and add them to the theme.

**Describe alternatives you've considered**
N/A

**Additional context**

These are some features I'd be happy to implement myself and contribute to this amazing project, if there is an actual demand for it. I will try my best to implement them for my blog anyway, but if people agree that they would also like them, I may polish the code a bit more and do a PR here.

**Example Usage**:

- gallery

```
# To add all png images in a directory:

{{< gallery source="img/*.png" >}}

# To add all pngs that contain `gallery_` in the name:

{{< gallery source="img/gallery_*.png" >}}
```

- carousel
- 
```
# To add all png images in a directory:

{{< carousel source="img/*.png" >}}

# To add all pngs that contain `gallery_` in the name:

{{< carousel source="img/gallery_*.png" >}}
```

- github

```
{{< github user="mirceanton" repo="mirceanton.com" >}}

# or simply

{{< github url="https://github.com/mirceanton/mirceanton.com" >}}
```

**Reference links**:

- [gallery](https://github.com/Darthagnon/hugo-easy-gallery)

the downside for this one is that it requires us to put all images inside the `static/` directory instead of using page bundles

- [carousel](https://hugocodex.org/add-ons/slider-carousel/)
- [github repo](https://hugo-theme-luna.imiku.me/2022/05/02/shortcodes.html/#github-auto)

**Comment by nunocoracao** [comment]
This sounds really awesome @mirceanton can I ask you to break it down into three tickets? 
Also, would be able to provide any reference implementations or PRs for any of the above?

**Comment by mirceanton** [comment]
@nunocoracao I don't have them working the way I want them to yet. Once (if) I get it all sorted out, I will create individual issues and PRs for them!

I can't provide an estimated timeline as HTML, CSS & JS aren't exactly my specialty, so there will be a learning curve.

**Comment by nunocoracao** [comment]
Awesome thanks @mirceanton let's split the tickets because I don't mind picking some of them up if I have time. I can also do it if I have time, if tou can first I would be thankful.

**Comment by mirceanton** [comment]
Alright then! I'll create the tickets a bit later today.

**Comment by mirceanton** [comment]
@nunocoracao Closing this as individual tickets have been created per shortcode:

- #426 
- #427 
- #428

**Comment by nunocoracao** [comment]
cool thanks
