### ISSUE TITLE
🌟 Shortcode: Gallery

### ISSUE THREAD

**Issue by mirceanton** [nunocoracao/blowfish#428]
**Is your feature request related to a problem? Please describe.**

In my website, I need the ability to easily showcase multiple related images and I would like a better solution than to just use a bunch of `{{< figure ... >}}` shortcodes.

**Describe the solution you'd like**

A `{{< gallery ... >}}` shortcode that would match multiple images given a regex would be a nice solution for this.

Example/Expected usage:

```
# To add all png images in a directory:

{{< gallery source="img/*.png" >}}

# To add all pngs that contain `gallery_` in the name:

{{< gallery source="img/gallery_*.png" >}}
```

**Describe alternatives you've considered**

N/A

**Additional context**

Useful links:

- https://github.com/Darthagnon/hugo-easy-gallery: this repo implements something very similar, but requires us to put all images in `static/` instead of using page bundles

**Comment by nunocoracao** [comment]
Same as the other... array seems better... if you do folder,for example, it might be hard to sort the images. An array it's more verbose but more flexible and easier to implement.
