### ISSUE TITLE
TypeIt integration produces JS error

### ISSUE THREAD

**Issue by adir1** [nunocoracao/blowfish#437]
**Describe the bug**
Error in JS Console that stays consistently: "Uncaught ReferenceError: renderTypeItElements is not defined at HTMLScriptElement.onload" when TypeIt shortcode is used on page

**To Reproduce**
1. Have TypeIt shortcode on any post
2. Open Browser JS Console
3. See above error

**Expected behavior**
Not to have error

**Comment by nunocoracao** [comment]
Already fixed in https://github.com/nunocoracao/blowfish/pull/429

**Comment by nunocoracao** [comment]
Duplicate https://github.com/nunocoracao/blowfish/issues/416
