### ISSUE TITLE
✨ Shortcode: Timeline

### ISSUE THREAD

**Issue by mirceanton** [nunocoracao/blowfish#451]
**Is your feature request related to a problem? Please describe.**

A timeline style shortcode would be very useful when designing `About Me`/`Resume` pages to showcase past work experience.

**Describe the solution you'd like**

Some form of timeline shortcode to showcase events/points in time.

**Describe alternatives you've considered**

In my website, I did a quick and dirty workaround by leveraging the elements and shortcodes already provided by the theme:

![image](https://user-images.githubusercontent.com/28601784/212631991-6e8756b3-e9f1-4c27-8f5b-8b5431cb828a.png)

If this looks good enough/promising I could add my shortcode file in a PR and call this a day.

**Additional context**

Additional links/references:

- Maybe something like [this](https://www.w3schools.com/howto/howto_css_timeline.asp)?

**Comment by nunocoracao** [comment]
Don't really like the implementation. Need to consider this one more.

**Comment by mirceanton** [comment]
Maybe something more like [this](https://codepen.io/alvarotrigo/pen/ExwYyNW)?

![image](https://user-images.githubusercontent.com/28601784/213302077-7ae8407d-e745-4081-9b78-9dcb68fa69f4.png)

**Comment by nunocoracao** [comment]
Yup. Since I've added tailwind elements for the carousel I am wondering if we can leverage it more. This would be an example of that.

https://tailwind-elements.com/docs/standard/components/timeline/

**Comment by mirceanton** [comment]
The fact that the website doesn't seem to have a dark theme worries me :)))

But yea, I personally like the last 2 the most.

**Comment by nunocoracao** [comment]
We can adapt the classes being used, ezpz...

**Comment by mirceanton** [comment]
Let me know if there is anything I can help with!

**Comment by mirceanton** [comment]
I'll try to get to it this week! I'm a bit behind on Uni work so I'll try to squeeze it in maybe this weekend!

**Comment by nunocoracao** [comment]
Created branch for feature

**Comment by nunocoracao** [comment]
fixed in https://github.com/nunocoracao/blowfish/pull/478

**Comment by mirceanton** [comment]
Closing this as it was fixed in #478
