### ISSUE TITLE
:bug: "Alert" shortcode does not align images properly 

### ISSUE THREAD

**Issue by MichalBrylka** [nunocoracao/blowfish#452]
**Describe the bug**
An icon is not aligned vertically to middle in `alert` shortcode. This would make this type of note more visually pleasing 

**To Reproduce**
1. Go to https://nunocoracao.github.io/blowfish/docs/shortcodes/#alert
2. Check out an alert that reads "Warning! This action is destructive!"

**Expected behavior**
Icon is aligned to middle 

**Screenshots**
![image](https://user-images.githubusercontent.com/18634170/212719332-e70ffa69-61d3-4dc9-9d3c-037fb83f4d2a.png)

**Desktop (please complete the following information):**
 - OS: Windows, iOS
 - Browser: Edge, Opera, Chrome
 - Version: all in newest versions 

**Hugo & Blowfish versions**
Link provided is using the same versions that are used in Blowfish demo. I'm locally using newest Blowfish and Hugo:
`hugo v0.109.0-47b12b83e636224e5e601813ff3e6790c191e371+extended windows/amd64 BuildDate=2022-12-23T10:38:11Z VendorInfo=gohugoio`

**Comment by mirceanton** [comment]
I was also going to mention seeing this issue. I think it's as simple as adding the `flex items-center` classes to the `<span>` in the alert shortcode

**Comment by nunocoracao** [comment]
Fixed in https://github.com/nunocoracao/blowfish/pull/454
