### ISSUE TITLE
Heading tags have '#' placed at the end.

### ISSUE THREAD

**Issue by jwagriff** [nunocoracao/blowfish#453]
**Describe the bug**
Heading tags have '#' placed after them.

**To Reproduce**

Enter a heading into a blogpost with ##.

**Expected behavior**
An h2/h3 tag featuring the subsequent text is displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/111182358/212721242-639d355b-0706-47e0-a81d-ae5012e2d6ff.png)

**Hugo & Blowfish versions**
Which version of Hugo and Blowfish are you using?

Latest

**Additional context**

**Comment by nunocoracao** [comment]
Not a bug, it's a config which you can disable. 
Check `article.showHeadingAnchors` in https://blowfish.page/docs/configuration/#article
