### ISSUE TITLE
🐛 Typos in `List` shortcode documentation

### ISSUE THREAD

**Issue by mirceanton** [nunocoracao/blowfish#474]
**Describe the bug**

There seem to be a few mistakes in the documentation for the `list` shortcode.  
Firstly, the parameter table provides the same description for all params.  
Secondly, I believe the **Example #2** is also broken? Should `where` really be set to `Type`? I did not manage to get it working as intended.

**To Reproduce**

1. Go to the [docs page](https://blowfish.page/docs/shortcodes/#list)
2. Scroll down to the list section
3. See error

**Expected behavior**

A clearer set of instructions on how to use this particular shortcode. For example:
- Example 1: showing the latest `X` posts (ok as it is right now)
- Example 2: sorting by a single tag
- Example 3: sorting by multiple tags(?)
- Example 4: sorting by series (what I am trying to do).

**Screenshots**

![image](https://user-images.githubusercontent.com/28601784/213993335-5768ddd8-0666-40e2-bada-b178edac58c1.png)

**Comment by nunocoracao** [comment]
fixed in https://github.com/nunocoracao/blowfish/pull/476
