### ISSUE TITLE
✨ Customizable name for the `List` shortcode

### ISSUE THREAD

**Issue by mirceanton** [nunocoracao/blowfish#475]
**Is your feature request related to a problem? Please describe.**

Currently, the `list` shortcode only displays the text "Recent" as a title for the posts list. Ideally, I would like to rename it. For more context, I am trying to implement a projects section and in the page for a given project, I want to use the `list` shortcode to provide a list of all of the devlog blog posts I wrote about that project. I would like the title of the list to say something like "DevLogs" for this, as "Recent" makes little sense.

**Describe the solution you'd like**

Set a customizable list title, keeping the default as is. Something like:

```md
{{< list title="DevLogs" limit=10 where="Series" value="Devember 2022 >}}"
```

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by nunocoracao** [comment]
fixed in https://github.com/nunocoracao/blowfish/pull/477
