### ISSUE TITLE
.Path when the page is backed by a file is deprecated and will be removed in a future release.

### ISSUE THREAD

**Issue by miodzie** [nunocoracao/blowfish#48]
Hi, I saw there was another issue referencing this: #22 
It looks like the hugo version was upgraded, but the warning still remains.

I found a fix here that works: https://github.com/wowchemy/wowchemy-hugo-themes/issues/2592

I'll open a PR with this fix in a bit, I just have to edit two files. 
https://github.com/wowchemy/wowchemy-hugo-themes/issues/2592#issuecomment-1054575549

**Comment by miodzie** [comment]
PR opened #49

**Comment by nunocoracao** [comment]
Thanks @miodzie will review
