### ISSUE TITLE
:bug: `article.showEdit ` is `true` in config file when defaults should be `false`

### ISSUE THREAD

**Issue by skurger** [nunocoracao/blowfish#486]
**Describe the bug**

I noticed that the edit button is present on articles on my site even though I didn't enable this. [In the documentation for configuration](https://blowfish.page/docs/configuration/#article) it indicates that `article.showEdit` defaults to `false` however [in this code](https://github.com/nunocoracao/blowfish/blob/main/config/_default/params.toml#L59) I am seeing it set to `true`.

**To Reproduce**

Create a new project and create a post. View the post and the edit button should be present without any changes to configuration.

**Expected behavior**
I would expect the edit button not to be shown since it should be `false` by default.

**Comment by mirceanton** [comment]
@nunocoracao this was fixed in #490 . I think you can close this one
