### ISSUE TITLE
:bug: Github shortcode not processing `null` language entry

### ISSUE THREAD

**Issue by andres04x** [nunocoracao/blowfish#491]
Hello, when using the Github component with a repository that does not have any programming language, it is not displayed and results in an error.

**To Reproduce**
1. In an index.md add the component, for example with this repository:
	'{{< github repo="EbookFoundation/free-programming-books" >}}'
2. Run hugo server with: 'hugo server'
3.The error is reproduced.

**Expected behavior**
That the repository is displayed correctly as it appears in the documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/101137391/215237661-0d99665e-5332-45c2-98db-5438c66717fc.png)

![image](https://user-images.githubusercontent.com/101137391/215237668-9b6458e3-e08c-4eb4-ad19-a04ebd4c52b9.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Edge
 - Version 109.0.1518.61

**Hugo & Blowfish versions**
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168 linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio

Blowfish: v2.26.0

**Additional context**
It would be nice if any repository exceeds the amount of 1,000 it will be shown as 1k, 2000 = 2k and so on, both in stars and forks

**Comment by nunocoracao** [comment]
Investigation details:

- https://api.github.com/repos/EbookFoundation/free-programming-books shows language at null
- current json color converter at https://github.com/nunocoracao/blowfish/blob/main/data/githubColors.json doesn't include that value 
- code breaks in line 23 - https://github.com/nunocoracao/blowfish/blob/main/layouts/shortcodes/github.html - by calling index with `null`

**Comment by nunocoracao** [comment]
fixed in https://github.com/nunocoracao/blowfish/pull/503
