### ISSUE TITLE
✨ Add recommended posts based on content tags or keywords.

### ISSUE THREAD

**Issue by newbeelearn** [nunocoracao/blowfish#495]
**Is your feature request related to a problem? Please describe.**
After user completes reading posts , previous and next posts are recommended which may or may not be related to the current article better heuristic would be to recommend posts based on either tags or keywords. This would help in increasing the engagement with the site.

**Describe the solution you'd like**
Add recommendation parameter with recommendation heading, recommendation criteria and number of posts to be recommended. When this parameter is configured articles will be recommended with recommendation heading for e.g. "Related Articles", "You may also like" etc. Recommendation algorithm can be based on tags i.e. articles having same tags are recommended or keywords i.e. articles based on same keywords are recommended. Number of articles will determine how many articles need to be listed under the heading.

**Describe alternatives you've considered**

**Additional context**
Helps in discoverability for user and increases engagement for the siteowner

**Comment by nunocoracao** [comment]
Could this be a partial that tou manually place in your MD file to begin with? Or an addition to the list partial?

**Comment by newbeelearn** [comment]
placing it manually in md would put additional effort on user for redundant information as user has already put work in classifying the content with tags/keywords so it would be good if it is automatic. I just found out that hugo already provides related content https://gohugo.io/content-management/related/ so we need to utilize this feature in this theme.

**Comment by mirceanton** [comment]
I would like to chip in with my 2 cents on this one :D

There are a few aspects to discuss and quite a few ideas I have, so I will just lay them out as bullet points below:

- Placement of this "recommended section":
  - On mobile, I think it is best to place it at the bottom of the page, after the comment section, perhaps
  - On desktop, I think we can leverage the horizontal space we have and start using the space next to the article, so we could possible show them underneath the ToC (if space permits)

- Configurability and future-proofing:
  - If this is implemented as requested, I think that this could/should be implemented as a standalone shortcode and not baked in by default to the pages

- Additional notes:
  - I think the space to the right of the article (on desktop) or bottom of the page (mobile) should be extracted to a partial. This way, the default partial can have the ToC and/or recommendations baked in but we can also override it and add some more things there, should we need it. For example, I see it as a useful feature to be able to have a shortcode for adding google ads on my page, maybe on the right next to the ToC or something, as to not disrupt the reader too much (as opposed to in-article ads).
  - Implementing it like this also allows the user to manually provide a list of related articles (in case the recommendation engine is not implemented after all). I think that the ability to showcase some articles that I deem to be "interesting" for the reader is equally important. Maybe there is an article that does not share tags with the one currently being read, but I know that the reader might also like that one as it is somehow related. In that case, I can add it manually to be showcased

**Comment by nunocoracao** [comment]
@newbeelearn @mirceanton let me make a proposal for this in a specific feature branch and ask you guys to have a look

I like all ideas here, not sure if I'll be able to start with all of them

**Comment by nunocoracao** [comment]
Related to #619 
Will consider a holistic approach for both of them maybe

**Comment by nunocoracao** [comment]
Done, proud of this one. Will be available in the next release (out today probably)
