### ISSUE TITLE
✨ New header menu with base background color

### ISSUE THREAD

**Issue by tibeer** [nunocoracao/blowfish#512]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A parameter to disable the blur effect for the top menu bar.

**Describe alternatives you've considered**
Providing an own html template file (layouts/partials/header/*.html)

**Additional context**
It's not really required, since you can provide your own templates. But this might be wished by someone. Especially when you use no background image, the menu bar get's quite colorful if you scroll and have pictures blurred by the top menu bar.

**Comment by nunocoracao** [comment]
@tibeer this is already possible if you use the basic config. What exactly are we looking to achieve? Sorry didn't get it

**Comment by tibeer** [comment]
<img width="1423" alt="example" src="https://user-images.githubusercontent.com/39375770/217730740-404715f9-73a4-4d32-9942-3152a9097a73.png">
When scrolling on a page, the menu bar is blurry, so you can see the image colors that "scrolled behind" the menu bar. Would be nice to have the menu bar fix a fixed background color

**Comment by nunocoracao** [comment]
Ok so new header menu, fixed, with single color... ack?

**Comment by tibeer** [comment]
yes

**Comment by nunocoracao** [comment]
Solved in https://github.com/nunocoracao/blowfish/pull/544

**Comment by tibeer** [comment]
Awesome! Thanks a lot!
