### ISSUE TITLE
Authors view

### ISSUE THREAD

**Issue by tibeer** [nunocoracao/blowfish#513]
**Describe the bug**
I guess there is something wrong with the autogenerated authors view.

**To Reproduce**
1. Go to https://blowfish.page/authors/
2. Review if this is the intended display of the list of authors

**Expected behavior**
They are displayed vertical and the name should not be split in two lines I guess?

**Screenshots**
not needed, can be found online here: https://blowfish.page/authors/

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 109.0.5414.119

**Hugo & Blowfish versions**
Which version of Hugo and Blowfish are you using?
hugo v0.110.0+extended darwin/arm64 BuildDate=unknown
hugo main (https://github.com/nunocoracao/blowfish/commit/55f6cc8873bed9447801168c7ae11df89c34fd00)

**Additional context**
None

**Comment by nunocoracao** [comment]
Not this is the intended behavior. On mobile it displays it the way you mentioned. On larger screens it uses the same ui as tags.

**Comment by tibeer** [comment]
Thanks for clarifying!

**Comment by nunocoracao** [comment]
Feel free to submit a feature change if you want to. Was just clarifying that right this is the expected behavior.

**Comment by tibeer** [comment]
👍 thanks!
