### ISSUE TITLE
🔬 iOS "Notch" on Safari Ignores Theme Colors

### ISSUE THREAD

**Issue by Capprin** [nunocoracao/blowfish#519]
**Describe the bug**
On iOS, in Safari, the notch is a plain white, ignoring dark mode theme colors (or an image background). In landscape mode, _colors_ are respected, but background images do not extend to the edges of the screen.

**To Reproduce**
1. Go to https://blowfish.page on iPhone Safari
2. If in light mode, click moon icon
4. See white bar above theme (and light search bar)
5. In landscape mode, see correct color change but bad background image behavior

**Expected behavior**
Theme content smoothly interacts up to edges of available display; iOS search bar colors respect darkness

**Screenshots**
![bf_portrait](https://user-images.githubusercontent.com/1781067/218326245-7e1628b9-ae6a-4d05-9d96-300a3cc377c9.jpg)
![bf_landscape](https://user-images.githubusercontent.com/1781067/218326253-2c683c54-5998-4a33-916e-949fefbd92ee.png)

**Desktop**
 - OS: iOS 16.1.2
 - Browser: Safari 16

**Hugo & Blowfish versions**
Hugo v0.110.0, but this issue persists even on the public Blowfish site.
Checked out Blowfish main at [55f6cc](https://github.com/nunocoracao/blowfish/commit/55f6cc8873bed9447801168c7ae11df89c34fd00)

**Additional context**
This is a tricky issue to solve. The correct fix will probably be to expand background elements to the edges of iPhones with the relevant [meta tags](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html), and defining a safe region for content in the stylesheet. This is fine with images, but it probably won't fix the underlying coloring problem for other pages because apple appears to choose colors with the [theme-color meta tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color) before the stylesheets are loaded. That precludes the use of the theme colors defined in the blowfish stylesheets.

My own hotfix just manually updates the theme color metadata at build time using colors defined in the site parameters (ugly, I know). It's technically responsive, but I've had to turn off the "theme switch" button because it doesn't update the meta tag - that might be another thing that needs to happen.

This iPhone-specific issue is annoying to see and annoying to fix. I'm using my "bandaid" for now so I don't need to update the stylesheets or any of the javascript. If this is fixed correctly, it would be fantastic.

**Comment by nunocoracao** [comment]
Solved in https://github.com/nunocoracao/blowfish/pull/546
