### ISSUE TITLE
🐛 Carousel not working as intended

### ISSUE THREAD

**Issue by geometrikz** [nunocoracao/blowfish#574]
**Describe the bug**
The carousel displays the images sequentially instead of one image with a next/previous button.

**To Reproduce**
1. Go to https://blowfish.page/docs/shortcodes/#carousel

**Expected behavior**
Displays a carousel

**Screenshots**

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/33253415/223227916-67d92909-0342-4fe3-a75f-bfd04c156e28.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser [e.g. chrome, safari]: Chrome + Safari

**Hugo & Blowfish versions**
Which version of Hugo and Blowfish are you using?

Latest version (on github)

**Additional context**

**Comment by nunocoracao** [comment]
Fixed in https://github.com/nunocoracao/blowfish/pull/582
