### ISSUE TITLE
🐛 Gallery overlaps with text and itself

### ISSUE THREAD

**Issue by hagenest** [nunocoracao/blowfish#575]
**Describe the bug**
When trying to use the gallery shortcode the images are overlapping with the page source and sometimes even with themselves. The overlap with the text can somewhat be mitigated with more newlines in the markdown, but I don't know how to fix the two rows of images lying on top of each other.

**To Reproduce**
1. Use gallery shortcode in content
2. build site
3. Look at generated page

**Expected behavior**
The images being formatted correctly

**Screenshots**
![Page source](https://user-images.githubusercontent.com/53492173/223231371-b2ec990d-3637-4929-b070-99d946c4e600.png)
![Rendered page](https://user-images.githubusercontent.com/53492173/223231377-70e2fb96-e932-457f-b055-07a8bd4fbb57.png)

**Desktop (please complete the following information):**
 - OS: openSUSE MicroOS Desktop
 - Browser: Chromium & Firefox
 - Version: Firefox 110.1 Flatpak & Chromium 110 Flatpak 

**Hugo & Blowfish versions**
- Main branch blowfish
- Hugo v0.110.0

**Comment by nunocoracao** [comment]
@hagenest do images get displayed all on top of each other?

**Comment by hagenest** [comment]
@nunocoracao yes, the first row of images lies directly on top of the second row

**Comment by nunocoracao** [comment]
fixed in https://github.com/nunocoracao/blowfish/pull/583
