### ISSUE TITLE
:bug: HTML <mark> tags and inline code not displaying colors correctly

### ISSUE THREAD

**Issue by hongphuctran77** [nunocoracao/blowfish#586]
**Describe the bug**
HTML `<mark>` and inline code tags turned grey after the most recent update. This issue persists across multiple color schemes and is also present on the demo site.

**To Reproduce**
1. Use `<mark>` tag or inline code in markdown file
2. Serve it with 'hugo serve' or publish it
3. See error

**Expected behavior**
The text highlighted by `<mark>` should be colored according to the color scheme specified in 'params.toml'.

**Screenshots**
https://blowfish.page/samples/markdown/#other-elements--abbr-sub-sup-kbd-mark

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome, Edge, Firefox

**Hugo & Blowfish versions**
Blowfish version: Latest
Hugo version: v0.110.0

**Additional context**

**Comment by nunocoracao** [comment]
Thanks for raising this @hongphuctran77 I'll have a look
