### ISSUE TITLE
Code Copy not adding to clipboard

### ISSUE THREAD

**Issue by amino-8** [nunocoracao/blowfish#587]
**Describe the bug**
Code Copy button is not working when enableCodeCopy = true is set

**To Reproduce**
Create a page with a code block and try to copy the code with the code button. Nothing gets added to the clipboard

**Expected behavior**
Code block is added to the clipboard

**Desktop (please complete the following information):**
Using windows 11 on Chrome and Firefox. Hugo version is V111.2 and blowfish is latest pull as of today

I've tried to mess around with code.js, but I don't think that is the problem. I suspect it's to do with how the js is being referenced from head.html in partials but I'm not experienced enough to confirm

**Comment by nunocoracao** [comment]
Just tried it and it is working.

E.g. from the shortcode page in live website both in Safari and Chrome
{{< chart >}}
type: 'bar',
data: {
  labels: ['Tomato', 'Blueberry', 'Banana', 'Lime', 'Orange'],
  datasets: [{
    label: '# of votes',
    data: [12, 19, 3, 5, 3],
  }]
}
{{< /chart >}}

**Comment by amino-8** [comment]
I've just tried it again, and it appears to work. I'm sorry for wasting your time. I must have messed up something in my config

**Comment by nunocoracao** [comment]
Just used it for your site

pipeline {
    agent { label 'dockeragentdnid'}

    stages {
        stage('Clone repository') { 
            steps { 
                script{
                cleanWs()                    
                checkout scm
                }
            }
        }
        stage ('BuildJekyll') {
            steps {
                script {

                    sh 'docker run -i --rm -v <DOCKERPATH>/jenkinsagent/workspace/Gitea_CICD_omaraminme_main:/srv/jekyll jekyll/builder:latest jekyll build'
    
                }
            }
        }
        stage('BuildandDeploy') {
            steps {
                script{
                    app = docker.build("<CONTAINER_REPOSITORY_URL>/omaraminme")
                    docker.withRegistry('<CONTAINER_REPOSITORY_URL>', '<REGISTRY_PASSWORD>') {
                        app.push("${env.BUILD_NUMBER}")
                        app.push("latest")                 
                    }
                }
            }
        }
        stage('Test'){
            steps {
                script {
                    if (fileExists('_site/index.html')) {
                        echo "Jekyll Site Built"
                    }
                }
            }
        }
    }
    post {
        success {
            sh 'sshpass <SSH_CREDENTIALS> "cd <DOCKERPATH> && docker pull <CONTAINER_REPOSITORY_URL>/omaraminme && docker compose up -d omaraminme"'
            sh 'curl -s -X POST https://api.telegram.org/<TELEGRAM_SECRET>/sendMessage -d chat_id=<TELEGRAM_CHAT> -d text="omaraminme build success"'
            emailext to: "<EMAIL>",
            subject: "jenkins build:${currentBuild.currentResult}: ${env.JOB_NAME}",
            body: "Success!"
        }
        failure{
            sh 'curl -s -X POST https://api.telegram.org/<TELEGRAM_SECRET>/sendMessage -d chat_id=<TELEGRAM_CHAT> -d text="omaraminme build failed"'
            emailext to: "<EMAIL>",
            subject: "jenkins build:${currentBuild.currentResult}: ${env.JOB_NAME}",
            body: "${currentBuild.currentResult}: Job ${env.JOB_NAME}\nMore Info can be found here: ${env.BUILD_URL}"
        }        
        cleanup {
            /* clean up our workspace */
            deleteDir()
            /* clean up tmp directory */
            dir("${workspace}@tmp") {
                deleteDir()
            }
            /* clean up script directory */
            dir("${workspace}@script") {
                deleteDir()
            }
         }
    }
}
