### ISSUE TITLE
✨ Default featured image

### ISSUE THREAD

**Issue by amino-8** [nunocoracao/blowfish#589]
Is there a way to specify a default featured image for all posts that is then overridden if there is featured file in the post directory? The alternative I've been using is to copy the same image into post directories which seems to be a bit wasteful.

**Comment by martinvisser** [comment]
I would too appreciate something like this, although I would like to have the same background image everywhere. I only use the `featured.ext` for the cards/thumbnails.

In short this is what I added in `partials/hero/background.html` (added `useDefaultBackgroundImage`):
```
{{- $featured := resources.Get $.Site.Params.defaultBackgroundImage -}}
{{- $useDefaultBackgroundImage := $.Site.Params.useDefaultBackgroundImage | default false -}}
{{- if not $useDefaultBackgroundImage }}
{{- $images := .Resources.ByType "image" -}}
{{- $featured := $images.GetMatch "*background*" -}}
{{- if not $featured }}{{ $featured = $images.GetMatch "*feature*" }}{{ end -}}
{{- if not $featured }}{{ $featured = $images.GetMatch "{*cover*,*thumbnail*}" }}{{ end -}}
{{- if not $featured }}{{ with .Site.Params.defaultBackgroundImage }}{{ $featured = resources.Get . }}{{ end }}{{ end -}}
{{- end -}}
```

Don't know if that's the best solution, but it works for me at least.

**Comment by nunocoracao** [comment]
Probably it needs to be a config also. Some users might not want to have the same featured images and for the ones that do, they might want a different image than the site background.

**Comment by ModdyLP** [comment]
The featured image is also part of the meta data, e.g. for twitter. Do you think that this behavior makes sense for the meta image? Should we think at this part also about remote featured images? I mean Hugo provide the getRemote function. 
I only want to tell my ideas, if that is not in your mind, just ignore them.

**Comment by amino-8** [comment]
I would say that the default image should be used for twitter card and open graph as well (as that's the standard behavior for custom featured images). Especially if the default can be overridden on a per post basis by putting the featured.jpg in the post directory as normal.
I hadn't considered remote images but being able to use them does make sense for people wanting to host image files somewhere else to save on bandwidth.

________________________________

**Comment by nunocoracao** [comment]
Going with a more flexible solution of adding a param to specify a default feature image that will be used across the site. Similar to default backgrounds
