### ISSUE TITLE
Site doesn't build on latest update. 

### ISSUE THREAD

**Issue by Keiferadfr** [nunocoracao/blowfish#602]
**Describe the bug**
I updated to Hugo 0.111.3 and my site was building as expcted, even with the `Module "blowfish" is not compatible with this Hugo version; run "hugo mod graph" for more information.` message. 

I then updated the theme using the submodule method and now my site no longer builds with the following error:

`hugo v0.111.3+extended darwin/arm64 BuildDate=unknown
WARN 2023/03/13 14:13:31 .File.Path on zero object. Wrap it in if or with: {{ with .File }}{{ .Path }}{{ end }}
Error: Error building site: failed to render pages: render of "page" failed: "/Users/dan/Documents/blog/themes/blowfish/layouts/_default/baseof.html:9:4": execute of template failed: template: _default/single.html:9:4: executing "_default/single.html" at <partial "head.html" .>: error calling partial: "/Users/dan/Documents/blog/layouts/partials/head.html:114:5": execute of template failed: template: partials/head.html:114:5: executing "partials/head.html" at <partial "vendor.html" .>: error calling partial: "/Users/dan/Documents/blog/layouts/partials/vendor.html:9:38": execute of template failed: template: partials/vendor.html:9:38: executing "partials/vendor.html" at <resources>: wrong type for value; expected resources.ResourceTransformer; got resource.Resource`

**Expected behavior**
The site to build.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Hugo & Blowfish versions**
Hugo: 0.111.3
Blowfish: 2.31.1

**Additional context**

I was previously using v2.26.0 before updating to the latest.

**Comment by nunocoracao** [comment]
@Keiferadfr thanks for reaching out. Do you have a place where I can see the code?

**Comment by nunocoracao** [comment]
Also do tou have overrides? It seems so from the log message

**Comment by joush007** [comment]
I've got a similar problem with it not building but I've got different pointers and an error with rendering due to a concat error from `partials/head.html`

**Comment by nunocoracao** [comment]
@joush007 will take a look
@Keiferadfr closed the issues because I think the reason for this ticket was your overrides, can you ack? Otherwise need to re-open

**Comment by Keiferadfr** [comment]
> @joush007 will take a look @Keiferadfr closed the issues because I think the reason for this ticket was your overrides, can you ack? Otherwise need to re-open

@nunocoracao for some reason I had a lot of files in layout/partials which I didn't put there (sorry I don't know hugo well). It looks like it was just a copy of the theme one? Does hugo make a copy for some reason? 

Anyway I deleted all the files and it works fine now and my site works the same. 

Thank you.
