### ISSUE TITLE
site not found

### ISSUE THREAD

**Issue by ripplesding** [nunocoracao/blowfish#606]
**Describe the bug**
when I click [Theme documentation](https://nunocoracao.github.io/blowfish/docs/), this site shows 404

**To Reproduce**
1. Go to https://themes.gohugo.io/themes/blowfish/
2. Click on Theme documentation
3. See error

**Expected behavior**
show website

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome

**Comment by nunocoracao** [comment]
That is not controlled by this repo (unfortunately). 
Feel free to go https://github.com/gohugoio/hugoThemesSiteBuilder/issues/282 and upvote the issue

**Comment by nunocoracao** [comment]
thanks @ripplesding mitigated the issue by creating a redirect
