### ISSUE TITLE
CodeCopy don't work - button won't show

### ISSUE THREAD

**Issue by Arturitu12** [nunocoracao/blowfish#610]
**Describe the bug**
The copy button near code blocks don't show at all.

**To Reproduce**
1. Fresh install using git
2. Configure site
3. Set `enableCodeCopy = true` in params.toml
4. Set 
```
[highlight]
  noClasses = false
```
in markup.toml
5. Create a page with code block using 4 spaces or 3 backticks.

**Expected behavior**
Copy code button shows up and works

**Screenshots**
![image](https://user-images.githubusercontent.com/58103832/225125293-2c6b4bca-214b-4f0b-b529-2ee2ed9f79e2.png)
![image](https://user-images.githubusercontent.com/58103832/225125441-4a4d0cf1-4a18-4c8e-8804-7309231fb4a0.png)
![image](https://user-images.githubusercontent.com/58103832/225125568-219abced-0076-4817-9776-2ee07f4f3134.png)
![image](https://user-images.githubusercontent.com/58103832/225125925-d8559671-f6f8-4e76-b91e-15b5b9e9f568.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser OperaGX
 - Version LVL 4 (core: 95.0.4635.74)

**Hugo & Blowfish versions**
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended
blowfish:  latest from main branch on github

**Additional context**
Button won't show up regardless if its draft page or not, hugo server or generated public pages.

**Comment by nunocoracao** [comment]
Not able to reproduce. The blowfish website uses the same parameters and it works. I would advise you to take a look at
- https://blowfish.page/samples/markdown/ - for an example
- and https://github.com/nunocoracao/blowfish/blob/main/exampleSite/content/samples/markdown.md?plain=1 - in this repo to check how to implement that. 

crazy hint, try declaring a language, aka change your example to

```bash
ls /etc/netplan
```

**Comment by Arturitu12** [comment]
> Not able to reproduce. The blowfish website uses the same parameters and it works. I would advise you to take a look at
> 
> * https://blowfish.page/samples/markdown/ - for an example
> * and https://github.com/nunocoracao/blowfish/blob/main/exampleSite/content/samples/markdown.md?plain=1 - in this repo to check how to implement that.
> 
> crazy hint, try declaring a language, aka change your example to
> 
> ```shell
> ls /etc/netplan
> ```

thanks! language declaration worked :))
Sorry for your time
