### ISSUE TITLE
✨Tabs with recent and featured posts

### ISSUE THREAD

**Issue by LITUATUI** [nunocoracao/blowfish#619]
Tabs with recent and featured posts, like shown on [this](https://hbs-skeleton.netlify.app/) Hugo theme would be a great new feature to have.

The image below shows how the theme above looks like with the tabs.

![PushEVs-on-HBS](https://user-images.githubusercontent.com/49299328/226211522-641f9dca-1334-4000-a9ed-3747b9fcf852.jpg)

Recent and featured posts on a fixed sidebar are essential for news blogs.

With this feature I could finally convert [my Wordpress blog](https://pushevs.com/) to Hugo. I think that many people that are now using Wordpress feel the same.

Thanks!

**Comment by nunocoracao** [comment]
@LITUATUI two questions:
1. Is this something to enhance the current recent articles experiences in the main page or something that would live in ALL article pages? 
2. How do you currently mark which articles are featured in your solution?

**Comment by LITUATUI** [comment]
1. These tabs would be shown in every page of the website, not just the homepage.
2. On the [HBS theme](https://github.com/razonyang/hugo-theme-bootstrap), the featured posts are marked in the front matter.

Exemple of the front matter on one article that is both pinned (first article on homepage) and featured (shows on the sidebar):

```
---
title: Technologies that will make electric vehicles even better
author: Pedro Lima
type: post
featured: true
pinned: true
date: 2021-06-21T05:00:16+00:00
url: /2021/06/21/technologies-that-will-make-electric-vehicles-even-better/
images: [/images/posts/Electric-charge-road-sign.jpg]
featureImage: [/images/posts/Electric-charge-road-sign.jpg]
categories:
  - Evergreen
  - General
---
```

A fixed sidebar with tabs that show recent and popular/featured posts is very common in Wordpress themes. When more Hugo themes get this feature, more people will make the migration away from Wordpress.

**Comment by nunocoracao** [comment]
Not implementing this navigation as described here, going with a related approach described in https://github.com/nunocoracao/blowfish/issues/495
