### ISSUE TITLE
Last Updated updates on site changes not post changes

### ISSUE THREAD

**Issue by amino-8** [nunocoracao/blowfish#624]
The updated date on posts updates when site changes are made (not just post changes)
For example, I just updated my site to Hugo 111.3 and all my posts show today's date as last updated.

**Comment by nunocoracao** [comment]
I am pretty sure this is Hugo stuff not blowfish. But will need time to check.

**Comment by nunocoracao** [comment]
Can it be enabled by default in a theme?
