### ISSUE TITLE
🐞 Color scheme does not match settings When Cloudflare Page

### ISSUE THREAD

**Issue by vicevolf** [nunocoracao/blowfish#630]
**Describe the bug**
Color scheme does not match settings

**To Reproduce**
I set the color scheme as `colorScheme = "Slate"` 
https://github.com/0000cd/character-prompts/blob/main/config/_default/params.toml

It is correct when previewing locally.
But after the Cloudflare Page is deployed, the color scheme becomes the default.
https://character-prompts.pages.dev/

**Expected behavior**
I want the color scheme after deployment should be Slate

**Screenshots**
![图片](https://user-images.githubusercontent.com/47265026/227591495-7a6c9769-bccc-40d4-bc8b-191bdc5225fd.png)

![图片](https://user-images.githubusercontent.com/47265026/227591454-bf66b785-b4f3-43d9-826b-30e66caffaf9.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows11
 - Browser Firefox
 - Version 112.0b5

**Hugo & Blowfish versions**
v0.110.0 v2.31.2

**Additional context**

**Comment by nunocoracao** [comment]
try "slate"... next time search discussions first Cloudflare has some quirks with Hugo a couple of users already discussed some of this there
