### ISSUE TITLE
When I want to a gallery page to show all the images in posts, I get some  difficult

### ISSUE THREAD

**Issue by xixici** [nunocoracao/blowfish#634]
**Is your feature request related to a problem? Please describe.**
When I want to a gallery page to show all the images in posts, I get some  difficult

**Describe the solution you'd like**
I can not to solve it.

**Describe alternatives you've considered**
I want to a page to contain all images.

**Additional context**
This is my code 

```

{{< gallery >}}

{{ range .Site.Pages }}
  {{ if eq .Section "post" }}
    {{ range .Resources.Match "*.jpg" }}
      <img src="{{ .RelPermalink }}" alt="{{ .Title }}" width="100" height="100">
    {{ end }}
  {{ end }}
{{ end }}

{{< /gallery >}}


```
I am a starter of hugo and blowfish. thank your work for this.

**Comment by xixici** [comment]
Hugo can not show it correctly . It shows like the origin code.

**Comment by nunocoracao** [comment]
Shortcodes don't work like that. The inside of it is not meant to be go templating so this will not work. The reason for the shortcode not supporting this use-case is that every image requires a CSS class. This is the current implementation for gallery. If you want to have a go at implementing a variant of the gallery shortcode you can use overrides in your own code (check Hugo's docs) and you can leverage the code in the caroussel shortcode.
