### ISSUE TITLE
View and like counter not updating on page

### ISSUE THREAD

**Issue by zpervan** [nunocoracao/blowfish#637]
**Describe the bug**
Not sure if it's a bug, or if I am doing something wrong, but I have an issue in which the views and like counters are **not** updated on my blog page, even though new views and likes are visible inside my Firestore database (updated as expected). I have followed through the guide for the firebase integration but still no luck.

**Expected behavior**
View and like counters are properly updated in HTML

**Screenshots**
Web page
![image](https://user-images.githubusercontent.com/6945278/228172059-4180bd88-7f65-4031-9bf9-574ed62a26e1.png)

Firestore
![image](https://user-images.githubusercontent.com/6945278/228172231-855ad4da-8a33-4834-8ae1-b6f7d741b822.png)
![image](https://user-images.githubusercontent.com/6945278/228172428-fbcbc676-5b3c-480e-8652-ac5bf4200348.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 111.0.1661.54

**Hugo & Blowfish versions**
Which version of Hugo and Blowfish are you using? 
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192 windows/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio
Blowfish v2.31.3

**Comment by nunocoracao** [comment]
Hello @zpervan I could take a look but as this is working across several sites I don't think it's a bug at this stage. Closing the ticket. Feel free to use the thread to provide me a repo and the url for your site and I will happily take a look and see if I can find the issue. At the moment I think it might have something to do with the id param in those components or javascript misbehaving.

**Comment by nunocoracao** [comment]
Something I remembered after the previous post @zpervan , have you activated anonymous authentication in your firebase project?

**Comment by zpervan** [comment]
Yeah, everything is as you describe, still no luck. Atleast I can check the view count in Firebase 😀

Thanks for the suggestions and have a nice weekend.

**Comment by nunocoracao** [comment]
Can you share your repo and URL and I'll try to debug it for you?

**Comment by zpervan** [comment]
@nunocoracao Sure. I added you as a temporary collaborator to the project so check your notifications and invites. Thanks for the effort, appreciate it.

**Comment by nunocoracao** [comment]
Not forgotten, just didn't have time yet.

**Comment by nunocoracao** [comment]
@zpervan can I see a live version of the site?

**Comment by nunocoracao** [comment]
@zpervan I cloned the repo, turned the flags on and I am able to see the counters. 

<img width="846" alt="Screenshot 2023-04-04 at 23 03 56" src="https://user-images.githubusercontent.com/3803196/229932887-dbe259b8-bdaa-43f8-922b-5bcb6af7ad21.png">


<img width="1013" alt="Screenshot 2023-04-04 at 23 04 04" src="https://user-images.githubusercontent.com/3803196/229932900-22eaf27d-270e-4461-9afa-23fe7b6f9040.png">

Commited the change to the repo cheers

**Comment by zpervan** [comment]
@nunocoracao excellent. Interestingly, I turned on also the same flags but it would not move from 0. 

Thanks for the support!
