### ISSUE TITLE
Columns and Rows

### ISSUE THREAD

**Issue by Nydid** [nunocoracao/blowfish#638]
**Is your feature request related to a problem? Please describe.**
Currently, the Blowfish Hugo theme does not have a built-in feature for adding columns in the posts. This makes it difficult to display content in a more organized and visually appealing manner.

**Describe the solution you'd like**
I would like to see the Blowfish Hugo theme support the addition of columns in the posts. It would be great if the theme could allow the creation of customizable rows and columns. The user should be able to set the number of rows and columns and insert various types of content (such as images, text, and shortcodes) into the cells. This would make it easier to create visually appealing posts and improve the overall user experience.

**Describe alternatives you've considered**
One alternative solution could be to use layouts. However, I really like the Blowfish Hugo theme's design and would prefer to continue using it if possible.

**Additional context**
I believe that adding this feature would greatly enhance the user experience for those who use the Blowfish Hugo theme. Being able to create customizable rows and columns with different types of content would allow for more flexibility in post design and presentation.

**Comment by nunocoracao** [comment]
Hello @Nydid not doing this one in the theme sorry. 
You can use `html` in your markdown files plus a `custom.css` to achieve this customization. Let me know if you need help with it.

**Comment by Nydid** [comment]
> Hello @Nydid not doing this one in the theme sorry. You can use `html` in your markdown files plus a `custom.css` to achieve this customization. Let me know if you need help with it.

I understand, thank you for the response! How would I go about adding columns to, say, the simple.html that comes with the theme? Do I also have to edit the .css file that already exists or do I have to create a new one?

**Comment by nunocoracao** [comment]
There are several ways to override the theme. You can check the Hugo docs for that. My suggestion was simpler, you can just include your html code in the markdown page. If you need any extra css classes you can add then using a custom.css file supported in Blowfish.

**Comment by Nydid** [comment]
Ah! This is much easier than what I initially had in mind! Thanks a bunch!
