### ISSUE TITLE
✨ Add Gitlab repo / project shortcode

### ISSUE THREAD

**Issue by DiogoM1** [nunocoracao/blowfish#639]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use a shortcode, like the one available for github, to add / reference gitlab repositories.

**Describe the solution you'd like**
Add a gitlab repo based shortcode

**Describe alternatives you've considered**
Using simple links which leads to an inconsistency between Github / Gitlab project presentation.

**Additional context**
I built a small prototype locally and I took the following screenshot.
![image](https://user-images.githubusercontent.com/43378713/228395194-80f3fcce-e005-45c4-b760-6d7e83e7005b.png)

Unfortunately gitlab offers no information regarding programming languages used in a project within the REST API response body.

I would be willing to make a PR based on your feedback to add this functionality. It was pretty simple too.

**Comment by nunocoracao** [comment]
Thanks for https://github.com/nunocoracao/blowfish/pull/641 @DiogoM1 left a comment there regarding docs. Will test it in the dev branch
