### ISSUE TITLE
✨ Add embed-pdf / project shortcode

### ISSUE THREAD

**Issue by Weaxs** [nunocoracao/blowfish#652]
**Is your feature request related to a problem? Please describe.**
I want to be able to use shortcode for embed pdf

**Describe the solution you'd like**
Add  embed-pdf for shortcode 

**Describe alternatives you've considered**
Using pdfjs-dist and create embed-pdf.html for shortcode, I refer to [hugo-embed-pdf-shortcode](https://github.com/anvithks/hugo-embed-pdf-shortcode), and import  pdfjs-dist in package.json.

shortcode example:
> {{< embed-pdf url="./xx.pdf"  renderPageNum="2">}}

**Additional context**
I built a small prototype locally and I took the following screenshot.
![image](https://user-images.githubusercontent.com/20680212/230596623-cbcf9bd5-575f-40b4-a109-52c37ac04495.png)

I would be willing to make a PR based on your feedback to add this functionality.

**Comment by nunocoracao** [comment]
Sorry @Weaxs thanks for the effort. However, I am not accepting the PR for this just yet (heads-up will close it for now).
