### ISSUE TITLE
🎨 List hover styling too bright

### ISSUE THREAD

**Issue by JVimes** [nunocoracao/blowfish#663]
**Describe the bug**

The list hover styling seems too bright to me. I think it should be like the recent-articles section of the home page.

Here's an example:

https://user-images.githubusercontent.com/6148201/232179411-0c9a654c-4b40-490e-b880-d5245ae0f69c.mp4

**To Reproduce**

Add to `content/_index.md`:

```
{{< list limit=1 where="Title" value="Welcome to Blowfish" >}}
```

**Hugo & Blowfish versions**

Blowfish commit c627ebdfac71b69d77b00a17f97471685d19d91b
Hugo v0.111.2

**Comment by nunocoracao** [comment]
@JVimes thanks, will take care of it in the next release
