### ISSUE TITLE
Module "blowfish" is not compatible with this Hugo version

### ISSUE THREAD

**Issue by ssalinasfe** [nunocoracao/blowfish#664]
I just follow the readme.md instruction and when I run hugo I get this error

`WARN 2023/04/15 11:15:02 Module "blowfish" is not compatible with this Hugo version; run "hugo mod graph" for more information.
project blowfish
`

So I update this theme to the last version the **2.32.0** version, but I still get the error.

What Hugo version I need to use for this theme?

Also, in params.toml

`  #homepageImage = "IMAGE.jpg" # used in: hero, and card`

Where I have to store IMAGE.jpg?

**Comment by nunocoracao** [comment]
@ssalinasfe this is my bad
I didn't notice there was an update to Hugo and forgot to update the max version. Will release a patch in a couple of minutes

**Comment by nunocoracao** [comment]
@ssalinasfe scratch my previous comment. I checked and the last version of Hugo is v0.111.3 and Blowfish supports that. 
Can you clarify which version of Hugo are you using? 

Current configs are:
```
[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0 "
    max = "0.111.3"
```
