### ISSUE TITLE
Table of Contents not generated when using shortcode

### ISSUE THREAD

**Issue by dylantjb** [nunocoracao/blowfish#665]
**Describe the bug**
I am using a shortcode to pull my README.md down from projects and include it in an article. However, when I do this the table of contents will not generate. It only works when directly adding headings to the markdown file.

**To Reproduce**
Save this shortcode to `layouts/shortcodes/github-readme.html` and use it in an article with `{{< github-readme "user/repo" >}}`.
```
{{ $repo := .Get 0 }}

{{- $url := printf "https://api.github.com/repos/%s/readme" $repo -}}
{{- $response := getJSON $url -}}
{{- $content := base64Decode $response.content | markdownify -}}
{{ replaceRE `(?s)<h[1-2].*?>.*?</h[1-2]>` "" $content 1 | markdownify }}
```

**Expected behavior**
A table of contents being generated when I make `showTableOfContents = true` in `config/_default/params.toml`.

**Hugo & Blowfish versions**
Hugo: v0.111.3
Blowfish: v2.32.0

**Comment by nunocoracao** [comment]
Thanks for your feedback @dylantjb. I am closing this one because it's not related to Blowfish. Makes sense to me that the Hugo pipeline doesn't process this buy it's not something the theme can control.
