### ISSUE TITLE
Tailwind colours for shortcodes

### ISSUE THREAD

**Issue by DanWiseProgramming** [nunocoracao/blowfish#670]
Hi,

Apologies if this sounds like a noob question but I would really appreciate your assistance with the following problem I am facing:
How can I use Tailwind CSS classes like: `bg-yellow-100` (first table on [this page](https://tailwindcss.com/docs/background-color)) with this theme? I am creating new shortcodes and want to use colours not included in the Tailwind configuration JSON file there.

Do I need to override `tailwind.config.json` from the theme and if so, what is considered the best way to do so? After I override the file, do I need to add a new colour to the `theme.colors` object, like [this](https://tailwindcss.com/docs/background-color#using-custom-values)?

I already have the [CSS compilation set up](https://tailwindcss.com/docs/background-color) and when I use [arbitrary colour values](https://tailwindcss.com/docs/background-color#arbitrary-values) or already defined colours like `bg-primary-200/[.5]`, it works just fine. However, using `bg-yellow-100` does not work. I suspect that this is due to the colour not being defined in `theme.colors`.

Thank you.

**Comment by nunocoracao** [comment]
@DanWiseProgramming were you able to figure out a solution?

**Comment by DanWiseProgramming** [comment]
Hi @nunocoracao,
Thanks for following up!

I ended up using the already-provided colours with an arbitrary alpha value which worked out nicely in the end and is essentially what I wanted.

I am still curious as to the solution of the above query, though.

Thanks.

**Comment by nunocoracao** [comment]
@DanWiseProgramming ok awesome, tbh I would need to dig to get a solution. I would say this kind of customization would require overriding the CSS configs over the theme. Which is something I never did. Awesome it worked in the end.

**Comment by DanWiseProgramming** [comment]
@nunocoracao Yep I understand, thanks again 👍🏻

**Comment by toytag** [comment]
I also encountered a similar issue with custom bg color.

According to https://tailwindcss.com/docs/customizing-colors#disabling-a-default-color

you could do something like this in `tailwindcss.config.js`

```javascript
const colors = require('tailwindcss/colors')

module.exports = {
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      black: colors.black,
      white: colors.white,
      gray: colors.gray,
      emerald: colors.emerald,
      indigo: colors.indigo,
      yellow: colors.yellow,
    },
  },
}
```

then `bg-yellow-...` would be available again, so as other colors defined here.
