### ISSUE TITLE
Table of Contents on Mobile should be a dropdown

### ISSUE THREAD

**Issue by nunocoracao** [nunocoracao/blowfish#70]
**Is your feature request related to a problem? Please describe.**
Table of Contents on mobile take up a huge amount of space and ruin the UX of the page. This is especially true with large TOC.

**Describe the solution you'd like**
Table of content's should be a dropdown on mobile

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Viincentt** [comment]
I am trying to use blowfish to create a website for my restaurant. Is there a way to make the TOC sticky on mobile phone as well? I am thinking something like a left-right scrolling bar on top of the screen
