### ISSUE TITLE
🐛 Links become white on hover in light theme

### ISSUE THREAD

**Issue by dosoft** [nunocoracao/blowfish#703]
When I move my mouse over a link in the text on the website's light theme, the link color changes to white, making it difficult to read against the background. This happens consistently across all pages and text blocks on the website's light theme.

**Comment by nunocoracao** [comment]
Thanks @dosoft, confirmed should be an easy fix. Will pick it up when I have time. Marked as a `good first issue` to see if someone want to open a PR to fix.

**Comment by MOHDNEHALKHAN** [comment]
@dosoft Check my PR I changed the color

**Comment by nunocoracao** [comment]
@dosoft @MOHDNEHALKHAN sorry I closed the PR, it was not changing the right files. Please have a look at the docs on how to update the CSS values and generate the compiled CSS files.

**Comment by MOHDNEHALKHAN** [comment]
@nunocoracao Ok I will check it, as  I am a beginner I don't know much about how to contribute to a large project so if I understand it will definitely create a PR again
