### ISSUE TITLE
Remove inline script and inline style

### ISSUE THREAD

**Issue by d4rklynk** [nunocoracao/blowfish#705]
## Describe the bug
Hi, there's a lot of inline script and inline style, and they should be removed (at least inline script) to avoid XSS attacks. Inline style should be avoided as much as possible.

## Expected behavior
I'm not a dev so I only know thoerical solutions, like you should put the JS code and CSS code into appropriate files (JS and CSS files) instead doing it directly in the HTML file.

Here are some technniques that will help you :

- [Cross Site Scripting Prevention Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html)

- [JS tool](https://owasp.org/www-project-java-encoder/)

## Additional context
I know it's a lot of work, I'm fully aware of that, but before the project gets bigger and bigger, it would be awesome to fix these issues before.

In my field (sysadmin), we try to block as much as possible inline script and inline style with [Content Security Policies](https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html)(CSP) when hosting websites. You can check the link (about CSP) to see how we block these and how to fix them.

Thanks in advance for your time.

**Comment by nunocoracao** [comment]
Closing this as it's not a specific bug or enhancement
