### ISSUE TITLE
🐛 Carousel with Remote Images

### ISSUE THREAD

**Issue by ChrisRisner** [nunocoracao/blowfish#736]
Description:
I'm just getting started with the Hugo theme and I'd like to put a carousel on a page but reference images on a remote server by full URL. It seems to work fine with the Gallery Shortcode but I'm not getting it to work with the Carousel. 

**To Reproduce**
Create a page with a carousel similar to the below.  Note that the below uses several different methods of trying to set paths for images:
{{< carousel images="{featured.png, 'https://www.mywebsite.com/myimage.jpg', /img/logo2.png, /assets/img/myimage.jpeg, bop.jpeg}" >}}

**Expected behavior**
The Carousel loads with different pathing types working.

**Screenshots**
<img width="601" alt="image" src="https://github.com/nunocoracao/blowfish/assets/628920/5dc5faee-60aa-4dae-8dbd-57e64092b780">

**Hugo & Blowfish versions**
Hugo: v0.111.3
Blowfish: 2.33.0

**Additional context**
It may be that not all paths should work here but it seems like at least fully qualified URLs to images should work or guidance in the doc could be updated to indicate what does work.

**Comment by nunocoracao** [comment]
@ChrisRisner thanks for opening this one. Sorry for the late reply. I will try to have a look but this one might require some rework of the shortcode. If you have fixed it and want to submit a PR let me know.

**Comment by wolfspyre** [comment]
yeah. I found that as is, `carousel` will **ONLY** function with page resources.

`gallery` can be convinced to work with external images. but I've yet to identify a way to bribe carousel to do so.

**Comment by nunocoracao** [comment]
Thanks @aakashnand the other PR helped on this one
