### ISSUE TITLE
✨ New icons: graduation-cap, scale-balanced, etc

### ISSUE THREAD

**Issue by iunn-sh** [nunocoracao/blowfish#745]
Hi there, love this theme and actively using it. Thanks for developing this awesome Hugo theme.

I'd like to add a few icons, such as graduation-cap, scale-balanced, etc (from [FontAwesome](https://fontawesome.com/icons)). I understand I could just add them to my fork, but figure it might help others by adding icons to the theme itself.

I am more than happy to mimic [this PR](https://github.com/nunocoracao/blowfish/pull/684) to add icons to the theme. Is there anything else I should pay attention to before raising a PR?

**Comment by nunocoracao** [comment]
@iunn-sh thanks for that - it would be awesome. There's just three things
- add .svg to the folder in that PR
- add the line to the docs page with the icons
- make sure the svg file has the right fill tag (check the other svg files)

**Comment by nunocoracao** [comment]
@iunn-sh added the ones you mentioned. Feel free to open a PR to add more. You can follow this PR - https://github.com/nunocoracao/blowfish/pull/769 - as a guide to yours

**Comment by iunn-sh** [comment]
Wow thanks! You beat me to it LOL

I will follow that PR and add some more when need be.
