### ISSUE TITLE
🐛 Safari "sucks out" nav menu

### ISSUE THREAD

**Issue by Coronon** [nunocoracao/blowfish#775]
**Describe the bug**
When viewing a page on **mobile** Safari the opened navbar menu is positioned partly outside the viewport.
When trying Mac Safari everything works like a charm.

**To Reproduce**
Simply view a page in Safari.
This happens on all sub pages and with all configured layouts (I normally use `fixed`).

**Expected behavior**
I would like all the buttons to be clearly visible and clickable - just like on a computer

**Screenshots**
<details>
<summary>Large images</summary>

![IMG_1520](https://github.com/nunocoracao/blowfish/assets/33808743/f93c09c9-2d83-4d48-9b4c-2a2ec91954e1)
![Bildschirmfoto 2023-06-11 um 01 58 41](https://github.com/nunocoracao/blowfish/assets/33808743/4c6e2772-dae2-4b61-baf5-0baccfc6224a)
![Bildschirmfoto 2023-06-11 um 01 59 08](https://github.com/nunocoracao/blowfish/assets/33808743/266044ef-89fe-4419-af2b-132a146ac4f3)
</details>

**Desktop (please complete the following information):**
 - OS: iOS 16.4
 - Browser: Safari
 - Version: 16.4

**Hugo & Blowfish versions**
Hugo: hugo v0.111.1-39a4a3cf676533859217805c36181c7a3dfa321c+extended windows/amd64 BuildDate=2023-03-02T10:08:26Z VendorInfo=gohugoio
Blowfish: v2.30.0

**Additional context**
The problem seems to be caused by the `margin: auto` on `id="menu-wrapper"` in `layouts/partials/header/basic`.
If I remove the class everything seems to work as expected. `margin: auto` is interpreted as `margin: 0` by both Chrome and Firefox, but Safari seems to think that it is on to something ^^

**Comment by Coronon** [comment]
PS: A fix seems to be to simply change the `m-auto` ⇾ `m-0`.

I couldn't observe any side effects but am not sure where the actual difference is as Firefox and Chrome interpreted the `margin: auto` as `margin: 0` regardless.

**Comment by nunocoracao** [comment]
Hello @Coronon do you mind providing more tests regarding your fix? If you already found a solution I don't mind adding that myself to the code and testing the other browsers.

**Comment by Coronon** [comment]
Sure, I can test and submit a PR tomorrow (GMT+2) :)
