### ISSUE TITLE
🐛 Copyright only displays the year

### ISSUE THREAD

**Issue by vicevolf** [nunocoracao/blowfish#778]
**Describe the bug**
Copyright only displays the year. 
I installed the latest version of Hugo v0.113.0 and found that the theme errors when running. So I updated the theme using Git, and everything seemed to be fine. However, I noticed that the copyright at the bottom of the webpage only displays the year. I then checked the `languages.zh-CN.toml` file and found that the `copyright` setting does not work, while the `title` settings do work.

**To Reproduce**

**Expected behavior**
`copyright = "©{ year } #0000CD · [署名-非商业性使用 4.0 国际](https://creativecommons.org/licenses/by-nc/4.0/deed.zh)"`

**Screenshots**
![图片](https://github.com/nunocoracao/blowfish/assets/47265026/0a4730ca-1ef5-433f-a964-2cb6941831ca)

**Desktop (please complete the following information):**
 - OS: win11
 - Browser firefox
 - Version 115

**Hugo & Blowfish versions**
- Hugo v0.113.0
- Blowfish v2.35.1

**Additional context**

**Comment by vicevolf** [comment]
https://github.com/vicevolf/test223

https://test223.pages.dev  zh or en

**Comment by dky** [comment]
Hi, I think you can statically configure this via:

https://github.com/nunocoracao/blowfish/blob/main/config/_default/languages.en.toml#L14

**Comment by vicevolf** [comment]
> Hi, I think you can statically configure this via:
> 
> https://github.com/nunocoracao/blowfish/blob/main/config/_default/languages.en.toml#L14

I have set it before, but zh is invalid, only en is effective 🤔

https://github.com/vicevolf/test223/tree/main/config%2F_default

https://test223.pages.dev/

**Comment by nunocoracao** [comment]
@vicevolf can you try placing copyright within a params like this:
```
[params]
  copyright = "©{ year } #0000CD · [署名-非商业性使用 4.0 国际](https://creativecommons.org/licenses/by-nc/4.0/deed.zh)"
```

**Comment by nunocoracao** [comment]
@vicevolf have you tried the above?

**Comment by vicevolf** [comment]
> @vicevolf can you try placing copyright within a params like this:
> 
> ```
> [params]
>   copyright = "©{ year } #0000CD · [署名-非商业性使用 4.0 国际](https://creativecommons.org/licenses/by-nc/4.0/deed.zh)"
> ```

Which settings file should I insert? My computer is recycled, haven't tried it yet, sorry.

**Comment by nunocoracao** [comment]
The one specific to the main language you are using.

**Comment by vicevolf** [comment]
its work! https://github.com/vicevolf/test223/commit/41c2ccaa9d9aa2126b2c350b9d6deca8599a545c

**Comment by nunocoracao** [comment]
Closing the issue
