### ISSUE TITLE
"\:secret\:" is substituted inside markdown code section

### ISSUE THREAD

**Issue by ruzickap** [nunocoracao/blowfish#78]
**Describe the bug**

I'm using the following `yaml` code block in my post, but the `:secret:` is replaced by some icon:

```yaml
Resource:
- "arn:aws:secretsmanager:*:*:secret:*"
```

Rendered output by the Hugo + Blowfish:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/1434387/194390337-77d11af6-950b-468c-aa10-fe2c48774973.png">

### Expected behavior

Whatever is written inside markdown code pattern ("```") should never be replaced.

**Comment by nunocoracao** [comment]
Hello @ruzickap, this is Hugo's behavior, not something Blowfish controls (or even can control). I found [this issue](
https://github.com/gohugoio/hugo/issues/4978 ) opened in Hugo's repo maybe it provides more details on how to get around, or you can ask the team there to reopened it. Closing this one as it's out of scope of the theme to fix this behavior.
