### ISSUE TITLE
Module "blowfish" is not compatible with this Hugo version

### ISSUE THREAD

**Issue by freerbeing** [nunocoracao/blowfish#788]
### hugo server D
WARN  Module "blowfish" is not compatible with this Hugo version; run "hugo mod graph" for more information.

### hugo version
hugo v0.114.1

### grep version themes/blowfish/package.json
  "version": "2.35.1",

### git submodule
 aa03e677db8ae083906cffececb14ec1db4dc879 themes/blowfish (v2.35.1)

**Comment by nunocoracao** [comment]
Fixed in https://github.com/nunocoracao/blowfish/pull/789

**Comment by freerbeing** [comment]
Yep
All good
Many thanks
Blowfish is a beautiful piece of work
I appreciate your efforts
