### ISSUE TITLE
Recent posts do not display in homepage

### ISSUE THREAD

**Issue by freerbeing** [nunocoracao/blowfish#796]
Hey
The header "Recent" appears on the homepage
But no list of recent posts

(Top menu also not working yet - working on it - , but pages are accessible via "/posts" etc

  mainSections = ["posts"]
  showRecent = true
  showRecentItems = 6

Here is my repo:
https://github.com/freerbeing/peoplespoetry

Netlify deploy:
https://startling-bunny-d5adab.netlify.app/

**Comment by nunocoracao** [comment]
Your md files for articles should be index.md not _index.md
Please check both Blowfish docs and Hugo docs before opening issues - this is not a bug. If you need help please use the discussions section

**Comment by freerbeing** [comment]
Thanks, man, yes, thats sorted out both issues
