### ISSUE TITLE
FUNDING.yml

### ISSUE THREAD

**Issue by poolpOrg** [nunocoracao/blowfish#831]
**Is your feature request related to a problem? Please describe.**
I wish you had a FUNDING.yml so I could send you $$$ for a pizza and/or a beer

**Describe the solution you'd like**
Well, you could have a FUNDING.yml in your .github directory

**Describe alternatives you've considered**
Alternatively, you could tell me where to paypal you a pizza

**Additional context**
I've used hugo for my website for years now and juggled with themes.
Your theme is by far the best I've ever used.

**Comment by nunocoracao** [comment]
Thank you so much @poolpOrg :) there is a buy me a beer button in the repo and in the main page but I will create a funding.yml for sure

**Comment by nunocoracao** [comment]
Added

**Comment by nunocoracao** [comment]
@poolpOrg live :) thanks for the suggestion

**Comment by nunocoracao** [comment]
Thanks @poolpOrg for the pizza

**Comment by poolpOrg** [comment]
well deserved !
