### ISSUE TITLE
Articles page fails to display properly after deployed on GitHub Pages

### ISSUE THREAD

**Issue by iLucis** [nunocoracao/blowfish#845]
**Describe the bug**

The deployed GitHub Pages: ilucis.github.io (ilucis.com)

I have completed the configuration of this theme locally, and tested it using “hugo server” command go to localhost:1313. Everything appears to be functioning properly except for the custom menu(which has no posts exists) not displaying correctly on pages, but the primary menu "Writes", which has 3 posts, is working fine, and All other sections of the website preview are functioning as expected.

However, after pushing the contents of the "public" folder to GitHub Pages, I am encountering some issues. In addition to the menu pages problem mentioned above, **my custom menu “Writes” is no longer displaying correctly**, but the sub-menu “Notes” seems to be unaffected. 

**The most critical issue is that when I click on the titles of the three existing posts through the category (tag) pages or the “Notes” sub-menu, the individual post pages fail to load properly and display a “Page Not Found” error. Strangely, these issues do not occur during local testing.**

As a beginner, I am unsure of the reasons behind these discrepancies. I would greatly appreciate it if someone could enlighten me on this matter.

**Expected behavior**

I would like my article pages to be displayed correctly both now and in the future.

**Screenshots**

1. Here is an example of a local test article page:
<img width="1218" alt="本地文章页ok" src="https://github.com/nunocoracao/blowfish/assets/132722267/2d909bed-5f2c-4659-8266-bc19c52b31e3">

2. This is an example of a local test primary menu page:
<img width="1189" alt="本地一级菜单栏ok" src="https://github.com/nunocoracao/blowfish/assets/132722267/b8abbf00-4637-4b16-81dc-41ca371544d9">

3. This is an example of an article page after deploying to GitHub Pages:
<img width="1187" alt="githubpages文章页" src="https://github.com/nunocoracao/blowfish/assets/132722267/51f77d12-aea4-46f7-8f59-385a01f21bd3">

4. This is an example of a primary menu page after deploying to GitHub Pages:
<img width="1240" alt="github一级菜单" src="https://github.com/nunocoracao/blowfish/assets/132722267/c56d79f4-8089-4597-ac51-39505538c2bb">

**Desktop:** MACOS Latest Version
 
**Hugo & Blowfish versions:** Both Latest Version

**Comment by nunocoracao** [comment]
@iLucis this seems like a problem with your configurations. Do you mind clarifying the baseURL you configured (if any), the github URL and the domain configurations you are using?

**Comment by iLucis** [comment]
> @iLucis this seems like a problem with your configurations. Do you mind clarifying the baseURL you configured (if any), the github URL and the domain configurations you are using? 这似乎是您的配置的问题。你介意澄清一下你配置的baseURL（如果有的话），github URL和你正在使用的域配置吗？

Github URL: ilucis.github.io
baseURL: https://ilucis.com

I have successfully pointed my personal domain, ilucis.com, to my GitHub Page, ilucis.github.io. Now, I can access ilucis.github.io through ilucis.com without any issues. Therefore, in my configuration, I have set the 'baseURL' as 'https://ilucis.com'.
