### ISSUE TITLE
article text width

### ISSUE THREAD

**Issue by RKonstantinR** [nunocoracao/blowfish#847]
When opening the site on a computer, a large empty space is displayed between the text and the table of content. 

![изображение](https://github.com/nunocoracao/blowfish/assets/38781076/9326f993-9d5e-419e-b57f-f15fe607b51a)

Is there a way to fix this and increase the text width?

**I expect something like this:**
![изображение](https://github.com/nunocoracao/blowfish/assets/38781076/9d46dfa9-fa3c-4dc2-a6df-f39a8c22d19a)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Win
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] 115.0.2

**Comment by nunocoracao** [comment]
Hello @RKonstantinR you can override the tailwind `prose` class if you want to - check how to override theme definitions in Hugo's docs. From a Blowfish point of view this is not a bug, the `prose` class defines a maximum number of characters that make reading the text more comfortable for the user.
