### ISSUE TITLE
⚙️ Request: `users.json` adding field for `source`

### ISSUE THREAD

**Issue by jamesbraza** [nunocoracao/blowfish#850]
I am getting inspiration from the [Users](https://blowfish.page/users/) page, it's really useful!

When I find a site I like, my next step is to look at the source code.  However, the current Users page doesn't have the source code linked.  So I take the `url`, and attempt to see if it's open source on GitHub.

It would be cool if `users.json` had a `source` field that linked the repo, if the source code is publicly viewable somewhere.

```json
[
  {
    "title": "nunocoracao.com",
    "url": "https://nunocoracao.com",
    "source": "https://github.com/nunocoracao/nunocoracao.com",
    "tags": [
      "Personal site",
      "Theme author"
    ]
  },
]
```

**Comment by nunocoracao** [comment]
@jamesbraza that's a good idea, need to check how that will work though - the current implementation makes the card a link to the site need to figure out how to have two links in the website - or if this would info would just be available in the file

**Comment by nunocoracao** [comment]
Hello @jamesbraza added the param in the JSON file. Will not be displayed for now as I don't have a good solution for that part but the link of whoever fills it in will be in the JSON sile. 

check https://github.com/nunocoracao/blowfish/pull/1295/commits/893687d0d49e5acca3a6adc7a0cea0e218aff93a

**Comment by jamesbraza** [comment]
Thank you!
