### ISSUE TITLE
📖 Docs: using icons from public URLs

### ISSUE THREAD

**Issue by jamesbraza** [nunocoracao/blowfish#862]
The [icon shortcode docs](https://blowfish.page/docs/shortcodes/#icon) on icons provide info on how to have your own icon file located in `assets/icons`.

What about if the icon is available at a link, can we document how to reference an icon by URL only?  Also, are non-SVG extensions accepted?

Here is an example URL: https://tukuz.com/wp-content/uploads/2019/05/university-of-pittsburgh-logo-vector.png

---

Also, to help noobs, it could be good to add a sentence explaining what an icon partial is to the [icon partial docs](https://blowfish.page/docs/partials/#icon).

**Comment by nunocoracao** [comment]
Hello @jamesbraza - closing this one. Hugo provides the freedom for users to enhance their own deploys with custom icons. The theme offers a set of icons ready to use to make things easier. I doubt asking people to configure their icons via URL is a better/easier experience.

**Comment by jamesbraza** [comment]
Okay gotchu.  The universities I attended or employers I work(ed) at, their icons are not in the `blowfish` supported list.

I didn't want to copy their icons to my website, I would prefer to just link their public URL.  However, I agree it's simpler for `blowfish` to support just one workflow, local files.  Thanks!

**Comment by nunocoracao** [comment]
@jamesbraza depending on what you are trying to achieve there are ways to import directly a remote image - just not an icon. Also it is possible to add custom icons. Create a discussion thread if you have further questions. Happy to help you

**Comment by jamesbraza** [comment]
Alright, I made https://github.com/nunocoracao/blowfish/discussions/888, thank you any help!
