### ISSUE TITLE
⚙️  Request: `timeline` supporting `title` and 2+ `subheaders`

### ISSUE THREAD

**Issue by jamesbraza** [nunocoracao/blowfish#863]
I think the `timeline` shortcode is really nice addition, thank you for this.

I have two ideas to make it more feature complete:

1. Adding a title to the upper left corner of the timeline (what the timeline is)
    - `timelineItem` supports `header`, can `timeline` support it too?
2. Supporting 2+ `subheader`s, to symbolize changes within the same organization
    - Ex: going from bachelors to masters in same school
    - Ex: lateral transfers or promotions within same employer

To share an idea of what this could look like:

```markdown
{{< timeline header="Education" >}}

{{< timelineItem header="Blowfish University" subheader="Masters in ABC" badge="Graduating MM/YYYY" >}}
{{< /timelineItem >}}

{{< timelineItem header="Blowfish University" subheader="Bachelors in ABC" badge="Graduated MM/YYYY" >}}
{{< /timelineItem >}}

{{< /timelineItem >}}
```

**Comment by jamesbraza** [comment]
Note: 2+ subheaders can be recreated inside `timelineItem`'s body with `<h4>` but one loses the corresponding `badge`s aspect for date ranges

**Comment by nunocoracao** [comment]
All of this can be done already @jamesbraza doesn't need to be _baked_ into the shortcode - check https://blowfish.page/docs/shortcodes/#timeline

**Comment by jamesbraza** [comment]
Maybe I am missing something, but I have read through the docs and don't see something like this (e.g. promotion without changing company):

![screenshot of LinkedIn promotion](https://github.com/nunocoracao/blowfish/assets/8990777/3202e6b7-94fe-4949-b638-c58e06f8c1e8)

([image origin](https://qph.cf2.quoracdn.net/main-qimg-97b1313ed4f5f1250ff2133e533171e0))

This portion of the `timeline` shortcode docs only demonstrate restating the company's name (`header`):

<img src="https://github.com/nunocoracao/blowfish/assets/8990777/bbf18aa6-5994-4ab8-bf85-3d82e52869a8" alt="screenshot of timeline shortcode docs" width="300">

What I am looking for is a way to share 2+ `subheader`s under one `header`, like the LinkedIn screenshot above

**Comment by nunocoracao** [comment]
In the image you send there is only one timeline - the difference is whether or not the company icon gets displayed as a title in each entry - that is supported atm. Do you have a visual example of what you are trying to do?

**Comment by jamesbraza** [comment]
Yeah the visual example would be the LinkedIn screenshot above, with the promotion from SW engineer to Sr SW engineer:
- Company name and icon is only shown once
- Multiple subheaders for each position, with custom descriptions for each

This is the closest I can get with `timeline` shortcode:

```markdown
{{< timeline >}}

{{< timelineItem icon="google" header="Google" badge="date B - present" subheader="promoted title" >}}
I got promoted and did something
{{< /timelineItem >}}

{{< timelineItem badge="date A - date B" subheader="original title" >}}
I did something
{{< /timelineItem >}}

{{< /timeline >}}
```

<img src="https://github.com/nunocoracao/blowfish/assets/8990777/ba921153-8e4c-4ba8-afc4-f6a7979b5211" alt="screenshot of timeline above" width="400">

How can one do this better with the currently supported `timeline`?
