### ISSUE TITLE
⚙️ Hiding "AUTHOR" text with `showAuthor: true`

### ISSUE THREAD

**Issue by jamesbraza** [nunocoracao/blowfish#865]
I am making an "About" page similar to [Nuno's about page](https://nunocoracao.com/about/).  I have `showAuthor: true`, but don't want the small "AUTHOR" text above the name:

<img width="132" alt="image" src="https://github.com/nunocoracao/blowfish/assets/8990777/dfa96934-cdc1-4974-b8f6-75dafb5290f6">

As of Blowfish 2.38.3, there doesn't seem to be an [Article config option](https://blowfish.page/docs/configuration/#article) for this.

So, the feature request: a new string config option for this like `article.authorIntro`, defaulted to `"AUTHOR"`

**Comment by nunocoracao** [comment]
Hello @jamesbraza - also closing this one as I will not be doing it anytime soon. I don't see it as an improvement at this stage. You can leverage the md file to achieve the effects you want without requiring changes to the theme at this level. Alternatively, you can create a custom shortcode for this use-case and open a PR with it.

**Comment by jamesbraza** [comment]
Yeah it's a minor feature request for sure.

> You can leverage the md file to achieve the effects you want without requiring changes to the theme

If you wouldn't mind clarifying, what were you thinking here?  I am not following how to change just an article's Markdown to remove AUTHOR text

**Comment by nunocoracao** [comment]
you can override showAuthor using the frontmatter parameter in the md file - this will remove the author component. 
After you can either create a custom partial for the way you want to display an author in that page OR you can use HTML directly in the markdown file.

**Comment by jamesbraza** [comment]
I figured out that one can override `i18n/en.yaml` (outside of `blowfish` theme) to solve this:

```yaml
---
author:
  byline_title: ""
```
