### ISSUE TITLE
⚙️ `figure` shortcode supporting 2 images

### ISSUE THREAD

**Issue by jamesbraza** [nunocoracao/blowfish#867]
I have an `figure` shortcode that I would like to include two images (instead of just one), for comparison purposes.

I would like to raise a request for `figure` to support 2 images.  I supposed a more general feature is supporting 1+ images.

Alternate solutions:
- If `gallery` shortcode supported descriptions/alternate text
- If `carousel` shortcode supported 2 images in one pane

**Comment by nunocoracao** [comment]
Hello @jamesbraza, thanks for all the suggestions. Closing this one - you can use two `figure` shortcodes to get the same effect. No need to overcomplicate. Another solution would be to use HTML in the md file to achieve the effect you want. No need to change the shortcode.
