### ISSUE TITLE
🐛  parenthesis next to linked text adds extra space

### ISSUE THREAD

**Issue by jamesbraza** [nunocoracao/blowfish#878]
**Describe the bug**

When there's linked text next to a parenthesis, an extra space is rendered:

**To Reproduce**

```markdown
([hi][1])

([hi](https://example.com/))

[1]: https://example.com/
```

![screenshot of bug](https://github.com/nunocoracao/blowfish/assets/8990777/1c2f4b8c-956a-4732-94fa-e3ebfd50b4e7)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Monterey version 12.6
 - Browser [e.g. chrome, safari] Chome version 115.0.5790.114

**Hugo & Blowfish versions**

Hugo 116.1 and Blowfish v2.38.3

**Comment by nunocoracao** [comment]
This one should be fixed
