### ISSUE TITLE
📖 Docs: better document `markup.toml` and `Goldmark`

### ISSUE THREAD

**Issue by jamesbraza** [nunocoracao/blowfish#882]
## Background

Nuno's personal website has a [`markup.toml`](https://github.com/nunocoracao/nunocoracao.com/blob/f385e656f713f15537bce2e32346b1d7871191de/config/_default/markup.toml#L2) that begins like so:

```toml
# -- Markup --
# These settings are required for the theme to function.
```

https://blowfish.page/docs/configuration/#other-configuration-files mentions `markup.toml`, but doesn't really say what should be there.

https://github.com/nunocoracao/blowfish/discussions/881 is a discussion where HTML tables were enabled by including the below in `markup.toml`:

```toml
[goldmark]
[goldmark.renderer]
  unsafe = true
```

## Request

It would be nice to flesh out the docs on `markup.toml`, including talking about what it should look like, and valuable entries to add.

**Comment by nunocoracao** [comment]
Hello @jamesbraza thanks for the feedback. Goldmark is used by Hugo and these configurations affect all themes not just blowfish. Check more here - https://gohugo.io/getting-started/configuration-markup/ 

What else were you expecting the theme docs to contain?

**Comment by jamesbraza** [comment]
Oh yeah sorry, I can clarify and add a PR to fix when I understand.

Does `blowfish` actually require a `markup.toml` natively?  And if yes, does it require a specific subset of the options listed on the Hugo page?  I ask because it seems to have been working without any `markup.toml` at all for me.

However, your personal website states that it does matter, so I am wondering if there is some like basic boilerplate `markup.toml` we should document

**Comment by nunocoracao** [comment]
@jamesbraza as stated in the installation docs - https://blowfish.page/docs/installation/
That is one of the files that is required - yes. You can read more in the docs above about what those configs are driving. Removing config files shouldn't _break_ the theme, just make something not look/feel the way they should.

**Comment by jamesbraza** [comment]
So just to confirm, on initial getting started with `blowfish`, should `markup.toml` be added as an empty file?  Or should it contain some fields?  I can open a PR to add the details

**Comment by nunocoracao** [comment]
Hello @jamesbraza the docs for Blowfish include that info. Please read them before opening more threads or PRs.
