### ISSUE TITLE
🐛 Adding gallery shortcode to multiple timeline items breaks lay-out

### ISSUE THREAD

**Issue by EntroPiGames** [nunocoracao/blowfish#886]
**Describe the bug**

When using the timeline shortcode and adding multiple items with a gallery shortcode in each, only the gallery in the first timeline item has a correct lay-out.

**To Reproduce**

1. Add a timeline shortcode
2. Add 2 timeline item shortcodes
3. Add a gallery shortcode to each timeline item

**Expected behavior**

All galleries have the correct lay-out

**Screenshots**

![image](https://github.com/nunocoracao/blowfish/assets/45169553/05eb2c9b-476a-459d-b077-3aac68428f76)

Code used for screenshot:

```
{{< timeline >}}

{{< timelineItem icon="star" header="Item 1">}}
{{< gallery >}}  
	<img src="early-days/04.jpg" class="grid-w20"/>
  	<img src="early-days/05.jpg" class="grid-w20"/>
  	<img src="early-days/02.jpg" class="grid-w20"/>
  	<img src="early-days/03.jpg" class="grid-w20"/>
  	<img src="early-days/01.jpg" class="grid-w20"/>  
{{< /gallery >}}
{{< /timelineItem >}}

{{< timelineItem icon="star" header="Item 2">}}
{{< gallery >}}  
	<img src="early-days/04.jpg" class="grid-w20"/>
  	<img src="early-days/05.jpg" class="grid-w20"/>
  	<img src="early-days/02.jpg" class="grid-w20"/>
  	<img src="early-days/03.jpg" class="grid-w20"/>
  	<img src="early-days/01.jpg" class="grid-w20"/>  
{{< /gallery >}}
{{< /timelineItem >}}

{{< /timeline >}}
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 116.0.1

**Hugo & Blowfish versions**
- Hugo Version 0.116.1 
- Blowfish v2.38.3

**Comment by nunocoracao** [comment]
@EntroPiGames do you have a repo with the code that I can pull and test locally - just to avoid reproducing the setup

**Comment by EntroPiGames** [comment]
> @EntroPiGames do you have a repo with the code that I can pull and test locally - just to avoid reproducing the setup

It's a private repo, but I sent you an invite for access to it. 

The timeline is on the about me page.

**Comment by EntroPiGames** [comment]
BTW, I also noticed that if you put a gallery shortcode **before** the timeline, the lay-out of the gallery in first the timeline item is also broken.

Screenshot:

![image](https://github.com/nunocoracao/blowfish/assets/45169553/7c859321-2ce4-4e5c-8adc-351d19d2ae43)

Code: 

```
{{< gallery >}}  
	<img src="early-days/04.jpg" class="grid-w20"/>
  	<img src="early-days/05.jpg" class="grid-w20"/>
  	<img src="early-days/02.jpg" class="grid-w20"/>
  	<img src="early-days/03.jpg" class="grid-w20"/>
  	<img src="early-days/01.jpg" class="grid-w20"/>  
{{< /gallery >}}

{{< timeline >}}

{{< timelineItem icon="star" header="Item 1">}}
{{< gallery >}}  
	<img src="early-days/04.jpg" class="grid-w20"/>
  	<img src="early-days/05.jpg" class="grid-w20"/>
  	<img src="early-days/02.jpg" class="grid-w20"/>
  	<img src="early-days/03.jpg" class="grid-w20"/>
  	<img src="early-days/01.jpg" class="grid-w20"/>  
{{< /gallery >}}
{{< /timelineItem >}}

{{< /timeline >}}
```

**Comment by nunocoracao** [comment]
@EntroPiGames may I ask you for the invite again? I was out and the invite expired

**Comment by EntroPiGames** [comment]
> @EntroPiGames may I ask you for the invite again? I was out and the invite expired

Done

**Comment by nunocoracao** [comment]
Thanks @EntroPiGames - I have a fix ready

**Comment by nunocoracao** [comment]
Fixed in new release

**Comment by EntroPiGames** [comment]
Great, thanks for the quick fix!
