### ISSUE TITLE
🎨 New param to place author at the bottom of articles

### ISSUE THREAD

**Issue by linmasaki** [nunocoracao/blowfish#887]
I've noticed that the author's block is currently placed at the beginning of the article. I would like to have this block placed at the bottom of the article, just like before, but I couldn't find any parameter to adjust it. Please consider adding a new parameter to fulfil this requirement.

**Comment by jamesbraza** [comment]
This site https://code-chimp.com/ has the author at the bottom.  The source code is here: https://github.com/code-chimp/code-chimp.github.io

If anyone figures out how to enable this, I'd be interested to hear too!

**Comment by QiXiuYuano** [comment]
Copy the layouts/_default/single.html file under the theme file to layouts/_default in the root directory, and then copy the <header>
     <-----other content--->
     {{ if .Params.showAuthor | default (.Site.Params.article.showAuthor | default true) }}
     {{ $showAuthor = 1 }}
     {{ partial "author.html" . }}
     {{ end }}
     <-----other content--->
 </header>

Just move it under 
<footer>
   {{ if .Params.showAuthor | default (.Site.Params.article.showAuthor | default true) }}
     {{ $showAuthor = 1 }}
     {{ partial "author.html" . }}
     {{ end }}
   <-----other content--->
</footer>

In this way, the author information is placed at the bottom of the article

**Comment by insidemordecai** [comment]
> This site https://code-chimp.com/ has the author at the bottom. The source code is here: https://github.com/code-chimp/code-chimp.github.io
> 
> If anyone figures out how to enable this, I'd be interested to hear too!

Code Chimp is using an older version of Blowfish. Author used to be at the bottom but I believed it was changed just recently. @QiXiuYuano's workaround should work.

**Comment by linmasaki** [comment]
@QiXiuYuano TKS, I know and use this workaround now, but I want a parameter to control it.

**Comment by wolfspyre** [comment]
looking at the single template, I'd think what would make sense here would be to add a param along the lines of 'authorsInlineDisplayedOrder' (or something) with 'top' or 'bottom' as acceptable values (or something similar), and adjusting the `single.html` template to insert the author bits towards the top or the bottom depending on the value... but ¯\_(ツ)_/¯ prolly better ways to do it? @nunocoracao  you have any input/preference/thoughts here?

**Comment by nunocoracao** [comment]
Sounds like a fair ask. I personally prefer them towards the top. Is someone up for having a go at the PR? Will open a branch for this issue.
