### ISSUE TITLE
layouts/partials/analytics.html not working

### ISSUE THREAD

**Issue by bosth** [nunocoracao/blowfish#901]
**Describe the bug**
`layouts/partials/analytics.html` is no longer being included in output HTML starting with version v2.35.1.

**To Reproduce**
1. Add `layouts/partials/analytics.html`
2. Build
3. Inspect HTML
4. Contents of `layouts/partials/analytics.html` are not present

**Hugo & Blowfish versions**
 - Hugo version 0.116.1

**Additional context**
Downgrading to v2.35.0 fixes the issue. I haven't found any versions after this that works.

**Comment by nunocoracao** [comment]
@bosth are you overriding that file with your own?

**Comment by bosth** [comment]
@nunocoracao, yes I created my own, following the [Custom Analytics Documentation ](https://blowfish.page/docs/partials/#custom-analytics-providers).

The content is just some code between `<script>` tags.

**Comment by nunocoracao** [comment]
I made same changes to those files. Could you try the extend-header override instead? That will make sure the code is always loaded. At least until I take a look at this one.

**Comment by bosth** [comment]
Renaming `layouts/partials/analytics.html` to `layouts/partials/extend-head.html` worked with v2.38.3.
