### ISSUE TITLE
Expose more in parameter to analytics.html

### ISSUE THREAD

**Issue by bosth** [nunocoracao/blowfish#908]
**Is your feature request related to a problem? Please describe.**
I am trying to access the current page's URL in `layouts/partials/analytics.html`. For example, I want to make a request to `https://tracker.com/?url={{ $THIS_PAGE_URL }}`.

**Describe the solution you'd like**
Change `{{ partial "analytics.html" .Site }}` to `{{ partial "analytics.html" . }}` in `layouts/partials/head.html`, so that I can use `{{ .Permalink }}` in my `analytics.html` override. My observation is that `.Site` contains site-wide data but not page-specific data, such as the current URL.

**Describe alternatives you've considered**
I have an easy workaround right now, which is overriding `head.html` with the proposed change above.

**Additional context**
If there is another way to access the current page's URL in the current `analytics.html`, then that would be great, but I couldn't find a way.

**Comment by nunocoracao** [comment]
Hello @bosth, check the documentation for hot to add an extend-head override to your implementation. This will allow you to add extra code to the head section of your website.
