### ISSUE TITLE
smartTOCHideUnfocusedChildren does not hide children after leaving parent section when scrolling down.

### ISSUE THREAD

**Issue by qalldredge** [nunocoracao/blowfish#919]
**Describe the bug**
Per the documentation the smartTOCHideUnfocusedChildren parameter when set to true and smartTOC set to true is supposed to "hide deeper levels of the table when they are not in focus". However, when your TOC is long due to many headings and/or levels, when leaving the parent the children should be hidden but they stay shown.

**To Reproduce**
1. Create a article with a lot of headings and levels.
2. Scroll down until a parent level's children are shown.
3. Continue to scroll down until the next sibling of the parent is highlighted, here the children of the previous parent should be remain shown.

**Expected behavior**
The expected behavior does occur when scrolling back up. If you scroll up to the previous parent from one showing its children, the children become hidden. This should be the same behavior when continuing to scroll down. 

**Screenshots**
![image](https://github.com/nunocoracao/blowfish/assets/56141106/1fc35423-a868-4384-91c8-ee425befa2d3)
Scrolling down, Previous children still showing.

![image](https://github.com/nunocoracao/blowfish/assets/56141106/f0b926b9-a20d-48c1-b669-ab0f4eeca920)
Scroll back up, children are hidden.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 115.0.5790.171 (Official Build) (64-bit)

**Hugo & Blowfish versions**
hugo v0.116.1-3e1ea030a5897addaf9d113d0826709fe07f77c0 windows/amd64 BuildDate=2023-08-01T07:24:54Z VendorInfo=gohugoio

Blowfish ?? Started about a week ago, not sure where to find version info

**Additional context**

**Comment by qalldredge** [comment]
Pulled most recent version of Blowfish and it still has this issue. So it is still present in whatever the most recent version of Blowfish it is.

**Comment by nunocoracao** [comment]
It's not an issue. It's the intended behavior, once you show something hiding it again without scrolling back is confusing.

**Comment by qalldredge** [comment]
Okay. I guess if that is intended. I am not as familier with js. What would I have to change if I wanted this behavior for my own site?
