### ISSUE TITLE
Fails to install as Hugo module because of extra dot in latest release version v.2.41.0

### ISSUE THREAD

**Issue by WarFox** [nunocoracao/blowfish#952]
This is probably a minor correction to do in the git tag.

I was trying to update to the latest release version v2.41.0, when I noticed that there is an extra "." in the release tag

It should be `v2.41.0` and not `v.2.41.0`.

I got various errors when trying to upgrade to the latest version. Looks like the extra dot is causing version resolution issues for `hugo mod get -u` command.

Amazing theme by the way, thank you for open sourcing it

**Comment by nunocoracao** [comment]
Hello @WarFox thanks for raising this. I might need help here.
The tag in GH seems ok - check https://github.com/nunocoracao/blowfish/tree/v.2.41.0

I also updated all my sites plus blowfish examples without any issues.

**Comment by WarFox** [comment]
Thank for you looking into this @nunocoracao 

This is what I have in my `config/_default/module.toml` file
```toml
[[imports]]
path = "github.com/nunocoracao/blowfish/v2"
```

And this is what I have in my `go.mod` file
```
require github.com/nunocoracao/blowfish/v2 v2.40.1 // indirect
``` 
As you see it has the previous release version

The following command does not update the version in go.mod file
```
hugo mod get -u
```
I believe this command should upgrade to the new version. Is that correct?

When I update `go.mod` file, to an older version like the following
```
require github.com/nunocoracao/blowfish/v2 v2.40.0 // indirect
```
It works with the following output

```
hugo: downloading modules …
hugo: collected modules in 44159 ms
go: upgraded github.com/nunocoracao/blowfish/v2 v2.40.0 => v2.40.1
```

When I update `go.mod` file to v.2.41.0 like the following
```
require github.com/nunocoracao/blowfish/v2 v.2.41.0 // indirect
```

`go.mod` file gets updated to the following when I run `hugo mod get`
```
require github.com/nunocoracao/blowfish/v2 v2.40.2-0.20230912103457-6a83762f12c5 // indirect
```

I am noticing the same when I try the following command, i.e `go.mod` file content is same as above
```
hugo mod get github.com/nunocoracao/blowfish/v2@v.2.41.0
```

Is this the correct behaviour?

**Comment by nunocoracao** [comment]
Hello @WarFox are you on the latest version of Hugo?

**Comment by WarFox** [comment]
Yes, I am on the latest Hugo

I am assuming this is the correct version based on the following output for `hugo mod get github.com/nunocoracao/blowfish/v2@v.2.41.0`

```sh
> go: upgraded github.com/nunocoracao/blowfish/v2 v2.40.1 => v2.40.2-0.20230912103457-6a83762f12c5
```

I have gone ahead with the upgrade in my blog here https://github.com/WarFox/tech/pull/26/files

Let's close this issue.

For clarity these are some of my attempts to upgrade to the version and the errors I got as output.

The following command did not upgrade to v.2.41.0 automatically
```
hugo mod get -u
```

The following 2 commands outputed errors because the commands were wrong!

```
> hugo mod get nunocoracao/blowfish/v.2.41.0
go: nunocoracao/blowfish/v.2.41.0: malformed module path "nunocoracao/blowfish": missing dot in first path element
Error: failed to get ["-d" "nunocoracao/blowfish/v.2.41.0"]: failed to execute 'go [get -d nunocoracao/blowfish/v.2.41.0]': failed to execute binary "go" with args [get -d nunocoracao/blowfish/v.2.41.0]: go: nunocoracao/blowfish/v.2.41.0: malformed module path "nunocoracao/blowfish": missing dot in first path element
 *errors.errorString
```

```
❯ hugo mod get nunocoracao/blowfish/v2 v.2.41.0
go: malformed module path "nunocoracao/blowfish/v2": missing dot in first path element
go: unrecognized import path "v.2.41.0": https fetch: Get "https://v.2.41.0/?go-get=1": dial tcp: lookup v.2.41.0: no such host
Error: failed to get ["-d" "nunocoracao/blowfish/v2" "v.2.41.0"]: failed to execute 'go [get -d nunocoracao/blowfish/v2 v.2.41.0]': failed to execute binary "go" with args [get -d nunocoracao/blowfish/v2 v.2.41.0]: go: malformed module path "nunocoracao/blowfish/v2": missing dot in first path element
go: unrecognized import path "v.2.41.0": https fetch: Get "https://v.2.41.0/?go-get=1": dial tcp: lookup v.2.41.0: no such host
 *errors.errorString
```

The correct command should be
```
hugo mod get github.com/nunocoracao/blowfish/v2@v.2.41.0
```

**Comment by metcalfc** [comment]
I'm new to this theme but I've got a similar experience to @WarFox.  The new `.` in the release threw me as well and I'm coming from a fresh install instead of an update. If you follow the instructions in the theme docs from a scratch hugo site:

```modules.toml
[[imports]]
path = "github.com/nunocoracao/blowfish/v2"
```

And then run `hugo mod get -u`, you won't get the `v.2.41.0` version. You'll get:

```
module github.com/metcalfc/demo

go 1.21.1

require (
	github.com/nunocoracao/blowfish/v2 v2.40.1 // indirect

)
```

I'm not a go expert but my go experience from the Docker days tells me that go mod is super picky and that extra `.` is why that release isn't getting picked up.

I've tested with Hugo:
* `hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended darwin/arm64 BuildDate=2023-09-24T15:20:17Z VendorInfo=brew`
*  `hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended darwin/arm64 BuildDate=2023-08-31T11:23:51Z VendorInfo=gohugoio`
* `hugo v0.115.4-dc9524521270f81d1c038ebbb200f0cfa3427cc5+extended darwin/arm64 BuildDate=2023-07-20T06:49:57Z VendorInfo=gohugoio`

**Comment by nunocoracao** [comment]
Hey @WarFox @metcalfc - terribly sorry took me a while to understand this and actually "see" the .
I've re-created the release and removed the dotted tag from the list. Hopefully, other users will not run into the same issue. Again thanks for the help and sorry for taking me this long to figure it out.
