### ISSUE TITLE
Missing overflow-hidden in simple article link

### ISSUE THREAD

**Issue by JVimes** [nunocoracao/blowfish#958]
**Describe the bug**
 
The image corner goes out of bounds in simple article links:

![image](https://github.com/nunocoracao/blowfish/assets/6148201/ca73e537-92cd-439b-9086-c3c44aa8cfcb)

Seems fixed adding ` overflow-hidden` on line 5 of simple.html:

```html
{{ $articleClasses = delimit (slice $articleClasses "border border-neutral-200 dark:border-neutral-700 border-2 rounded-md backdrop-blur overflow-hidden") " " }}
```

**Comment by nunocoracao** [comment]
Thanks @JVimes merging the fix will be in next release
