### ISSUE TITLE
cut a new release which bumps tailwindcss typography to 0.5.10 for dt/dl support?

### ISSUE THREAD

**Issue by wolfspyre** [nunocoracao/blowfish#961]
**Is your feature request related to a problem? Please describe.**

tailwindcss's 0.5.10 update adds support for DT/DL element styling. 

**Describe the solution you'd like**
I use definition lists extensively, so this would be a welcome addition.

**Describe alternatives you've considered**
emboldening words and adding linebreaks ? 

**Additional context**

Is there a clear articulation of the manual build process someplace? I couldn't find one, but I could just be blind.

**Comment by nunocoracao** [comment]
Done :)

Dependabot apparently is broken need to sort that out. Thanks
