### ISSUE TITLE
Search Not Working: Fingerprint and SRI Issue

### ISSUE THREAD

**Issue by ennnbeee** [nunocoracao/blowfish#964]
**Describe the bug**
Search not working on hugo build hosted in GitHub pages, works without issue locally on Windows and macOS. Investigating and the main.bundle.min...js file is failing the fingerprint and integrity check:

Failed to find a valid digest in the 'integrity' attribute for resource 'https://memv.ennbee.uk/js/main.bundle.min.34dfb4e6b05b47b0a3599f50035f9bbb18c2d36a26aa4c0ea7acc4936489d4c2a55f65683d53e3c4215337e6a8c02e554881af2da86b5783c96837ae3d4e98f6.js' with computed SHA-512 integrity 'PdzwT1sNTDL3LnJtPBLuvM2MPJ+dqpoTQUgIiV3grh4c3d2mhJaA1b2W27YNCx4LJMKfXIPlYx5V5+a8AgFUkA=='. The resource has been blocked.

**Expected behavior**
I expect search to work and the js file not to fail the SRI check.

**Desktop**
 - OS: Windows
 - Browser: All
 - Version: All

**Hugo & Blowfish versions**
Hugo: hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended windows/amd64 BuildDate=2023-08-31T11:23:51Z VendorInfo=gohugoio
Blowfish: v.2.41.0

**Additional context**
Source: https://github.com/ennnbeee/ennnbeee.github.io
Site: https://memv.ennbee.uk/

**Comment by ennnbeee** [comment]
Update: I built a clean github pages site with hugo and blowfish from a macOS device, and search works without issue. Doing the same from a Windows device causes the same reported issue:

memv.ennbee.uk/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://memv.ennbee.uk/demo/js/main.bundle.min.8dab968b186edba56ec5ea26dd8cbda8b6f520a7a162eb84e347ab2cb5aa113977f25f3a7a45bdba33fd3d5f3d7cc8062b60a295406127534ed81061299078de.js' with computed SHA-512 integrity 'QeR09dZgUrMTwzuPVgCK+sSYAVt0ctDyq3jiLBh0Bf3/EltnNZczCeR0O2kkyoxXXbKX9GTELajjDvna7TsFDA=='. The resource has been blocked.

**Comment by ennnbeee** [comment]
Update: updating the same site, building and pushing from macOS resolves the issue with the search. I'd stick with macOS but I've issues with firebase likes as per https://github.com/nunocoracao/blowfish/pull/709

**Comment by ennnbeee** [comment]
OK, think I found the issue and it relates to the Line Feed and Carriage Return Line Feed between Windows and macOS, which explains why I was getting different outcomes between operating systems.

After I got my head around SRI, with the clue being that the hash generated is based on the data locally first, noticed the below when adding content to the github repo.

warning: in the working copy of 'docs/js/main.bundle.min.8dab968b186edba56ec5ea26dd8cbda8b6f520a7a162eb84e347ab2cb5aa113977f25f3a7a45bdba33fd3d5f3d7cc8062b60a295406127534ed81061299078de.js', LF will be replaced by CRLF the next time Git touches it

Which means that git is touching and thus changing the file, so that the original generated hash value in the html content will not match the calculated hash value.

Sorted this by updating the git config on Windows using 'git config --global core.autocrlf false', which has fixed the hash problems and now search is working again. Will stick with pushing content from Windows for now.

**Comment by EntroPiGames** [comment]
OMG, thanks for figuring this out!

My site worked fine locally, but rendered incorrectly when uploaded to my private server.

I was also building on Windows using the blowfish git submodule. Applying the git config and downloading and adding a blowfish release manually fixed it.
