### ISSUE TITLE
Issue: Unseparated Tags between Indonesian and English

### ISSUE THREAD

**Issue by adilhyz** [nunocoracao/blowfish#966]
### Problem Description

I have configured my site to support two languages, Bahasa Indonesia and English. I am using Blowfish theme, and I observe that the tags are not properly separated between the two languages.

### Environment

- Hugo version: hugo v0.118.2+extended linux/amd64 BuildDate=unknown
- Operating System: Arch Linux
- Web Browser: Google Chrome Version 117.0.5938.92 (Official Build) (64-bit)

### Reproduction Steps

1. I created posts in Bahasa Indonesia and English with different tags.
2. I navigated to the Indonesian tag page.
3. I see that English tags also appear here, they shouldn't.

### My Expectation

I expected that tags in Bahasa Indonesia and English would be completely separate. When I visit a tag page in one language, I only want to see tags relevant to that language.

### Additional Information

- I checked the Language configuration and content directory structure, and everything was set correctly.
- I didn't encounter this issue in any other theme I used before.

### Directory structure 

> /myproject
> ├── content
> │   ├── _index.md
> │   ├── post
> │   │   ├── post-1.md (Bahasa Indonesia)
> │   │   ├── post-2.md (Bahasa Indonesia)
> │   ├── tags (Tag Bahasa Indonesia)
> │   │   ├── tag-1.md
> │   │   ├── tag-2.md
> │   ├── categories (Kategori Bahasa Indonesia)
> │   │   ├── category-1.md
> │   │   ├── category-2.md
> │   ├── en
> │   │   ├── post
> │   │   │   ├── post-1.md (English)
> │   │   │   ├── post-2.md (English)
> │   │   ├── tags (English Tags)
> │   │   │   ├── tag-1.md
> │   │   │   ├── tag-2.md 
> │   │   ├── categories (English Categories)
> │   │   │   ├── category-1.md
> │   │   │   ├── category-2.md

### Screen Record

https://github.com/nunocoracao/blowfish/assets/100203867/35f62ada-1a0e-45dd-945e-f64e6e52f55d

Any reply would be greatly appreciated...

Thank you.

**Comment by nunocoracao** [comment]
Hello @adilhyz not sure I can help much here. Even though our docs explain how to use i18n the core feature comes from Hugo. Did you check their documentation to see if they explain how to split tags per language?

**Comment by adilhyz** [comment]
> Hello @adilhyz not sure I can help much here. Even though our docs explain how to use i18n the core feature comes from Hugo. Did you check their documentation to see if they explain how to split tags per language?

Yes, thank you for your previous answer and very helpful. this is what I know at this time, that all tags and categories per language can be separated provided that the two different languages are allocated in different folders.

### Structure

content/
├── en/
│ ├posts
│ ├── **.md
│ ├── **.md
│ └── ...
└── id/
│ ├posts
│ ├── **.md
│ ├── **.md
│ └── ...

#### I have added a path directory to each language in

the file [`languages.en.toml`](https://github.com/nunocoracao/blowfish/blob/main/config/_default/languages.en.toml)
```sh
contentDir="content/en"
```
and `languages.id.toml`
```sh
contentDir="content/id"
```
