### ISSUE TITLE
Page level front matter parameters not in scope of head extension

### ISSUE THREAD

**Issue by robbienohra** [nunocoracao/blowfish#967]
**Describe the bug**

I have a custom KaTeX partial I'm adding (to support inline math using a single `$` delimiter).

So within `extend-head.html` I have the following:

```
{{ if eq .Params.article.math }}{{ partial "katex.html" . }}{{ end }}
```

Where `katex.html` looks like this:

```html
<!--https://cdnjs.com/libraries/KaTeX-->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/katex.min.css"
	integrity="sha512-7nTa5CnxbzfQgjQrNmHXB7bxGTUVO/DcYX6rpgt06MkzM0rVXP3EYCv/Ojxg5H0dKbY7llbbYaqgfZjnGOAWGA=="
	crossorigin="anonymous" referrerpolicy="no-referrer" />

<script defer src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/katex.min.js"
	integrity="sha512-aoZChv+8imY/U1O7KIHXvO87EOzCuKO0GhFtpD6G2Cyjo/xPeTgdf3/bchB10iB+AojMTDkMHDPLKNxPJVqDcw=="
	crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script defer src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.8/contrib/auto-render.min.js"
	onload="renderMathInElement(document.body);"
	integrity="sha512-iWiuBS5nt6r60fCz26Nd0Zqe0nbk1ZTIQbl3Kv7kYsX+yKMUFHzjaH2+AnM6vp2Xs+gNmaBAVWJjSmuPw76Efg=="
	crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
            delimiters: [
                {left: "$$", right: "$$", display: true},
                {left: "$", right: "$", display: false}
            ]
        });
    });
</script>
```

However, it looks like the page level value of `.Params.article.math` is not being registered. If I set a global `math` param as true in `config/_default/params.toml` and modify the reference to `.Params.math` then it takes effect. Am I missing something?

**To Reproduce**
1. Add the above modifications and add a test LaTeX block with a frontmatter property `math` set to true
2. Note that equations are not rendered

**Expected behavior**
Expect page-level frontmatter to be accessible within `extend-head.html`

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.5
 - Browser Chrome 116.0.5845.187 

**Hugo & Blowfish versions**
hugo v0.118.2 
Blowfish v.2.41.0

**Additional context**

**Comment by nunocoracao** [comment]
This `.Params.article.math` means that the value comes from the `params.toml` file within an `article` section, something like:

```
[article]
    math = true
```

Not really sure what you are trying to achieve otherwise - but this is a Hugo topic not specific to Blowfish. Closing the issue

**Comment by robbienohra** [comment]
🤔 

> This .Params.article.math means that the value comes from the params.toml file within an article section, something like

Right I understand this, my point was that the framework doesn't seem to be allowing me to _override_ the default value indicated in `params.toml` via frontmatter values specified in the markdown post itself. If I compare this to paper-mod for example, in a head extension, the value consumed there honour the front-matter overrides (I may have `math: false` in the markdown post and `math = true` in the default params or vice versa).

In this case somehow it seems like the value is being intercepted ie the frontmatter value is not honoured in the head extension. Hopefully that's a little more clear?

**Comment by robbienohra** [comment]
Is there a different reference path I should be following to pull the front-matter value as opposed to the value specified in the params file?

**Comment by robbienohra** [comment]
PS I am seeing the front-matter overrides being honoured for flags that are part of the framework eg `showComments` — this is what led me to suspect that perhaps _custom_ params are not propagating through because of the implementation.
