### ISSUE TITLE
Problem with favicon and CodeCopy function

### ISSUE THREAD

**Issue by JustinType** [nunocoracao/blowfish#983]
### Discussed in https://github.com/nunocoracao/blowfish/discussions/982

<div type='discussions-op-text'>

<sup>Originally posted by **JustinType** October  3, 2023</sup>
Hello I struggle with 2 problems for hours and don't figure out what to do, if someone can help me I would be glad :

- I followed the documentation and replaced all the .png files in /static/ but the favicon doesn't change and keep the blowfish's logo : 
![image](https://github.com/nunocoracao/blowfish/assets/55751991/71f9603f-334c-4d85-ab5c-4c7acb02394c)
(I verified that all the .png files have the good dimensions)

- Also in /config/_default/params.toml I put the parameter "enableCodeCopy" as true, the copy button in the code blocks appears but doesn't work : 
![code_copy_problem](https://github.com/nunocoracao/blowfish/assets/55751991/28dd1807-6a74-4d71-a25f-127334abeab0)
(I verified that the parameter "hightlight.noClasses" in /config/_default/markup.toml is set as false)</div>

**Comment by ShuaibinLi** [comment]
same problem, have you solved the favicon problem?

**Comment by nunocoracao** [comment]
If you are using chrome try open the debug mode and enter the mode where you can test different screen sizes. That should for e the caches to update.

**Comment by OxNinja** [comment]
# Favicons

Is the path on your screenshot equivalent to the `/static/` of your blog? Or is it the `/static/` of the theme? (Which might be something like `my-blog/themes/blowfish/static/` or so on your machine)

Also, maybe this is a cache issue? Reload the page and force to clear the cache.

Hope I can help.

# Code copy

I have the same issue: the button appears on code blocks but clicking it does not feed the clipboard (Firefox if this can help)

**Comment by nunocoracao** [comment]
@JustinType were you able to fix the issue?

**Comment by hcgaron** [comment]
@nunocoracao I was having this issue as well, but clearing the cache (simply opening dev tools network tab and having `disable cache` selected was sufficient) fixed it. I can confirm it is working by placing the correctly named files (generated with `favicon.io`) into a `/static` folder at the root of the site.

**Comment by nunocoracao** [comment]
Thanks @hcgaron
