### ISSUE TITLE
Error when building a website with a theme

### ISSUE THREAD

**Issue by majsterkovic** [nunocoracao/blowfish#984]
**Describe the bug**
```
> hugo
Total in 2 ms
Error: failed to create config from result: failed to decode "": 1 error(s) decoding:

* 'Theme[0]' expected type 'string', got unconvertible type 'maps.Params', value: 'map[_merge:none author:map[_merge:none homepage:https://nunocoracao.com/ name:Nuno Coracao] demosite:https://blowfish.page/ description:A powerful, lightweight theme for Hugo built with Tailwind CSS. features:[syntax highlighting dark mode emoji firebase views] homepage:https://github.com/nunocoracao/blowfish/ license:MIT licenselink:https://github.com/nunocoracao/blowfish/blob/main/LICENSE name:Blowfish original:map[_merge:none author:James Panther homepage:https://jamespanther.com/ repo:https://github.com/jpanther/congo] tags:[blog minimal responsive dark mode dark light tailwind personal]]'
```

**To Reproduce**
1. Go to 'mywebsite'
2. Type command `hugo`

**Expected behavior**
Website is built with theme.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Hugo & Blowfish versions**
hugo 0.119.0
blowfish 2.41.1

**Additional context**
In root directory is 'hugo.toml', not 'config.toml'.

```
config/_default/
├─ config.toml
├─ languages.en.toml
├─ markup.toml
├─ menus.en.toml
├─ module.toml  # if you installed using Hugo Modules
└─ params.toml
```

The initial folder does not contain all the files you indicate in the documentation.

**Comment by OxNinja** [comment]
What is the content of your config? `hugo.toml`

**Comment by nunocoracao** [comment]
@majsterkovic are you still experiencing the issue?

**Comment by majsterkovic** [comment]
> @majsterkovic are you still experiencing the issue?

I have given up using it.

> What is the content of your config? `hugo.toml`

I am not able to deliver it after such a long time.
