### ISSUE TITLE
Long tables, formulas, code blocks, etc. break website width / overall site scrolling

### ISSUE THREAD

**Issue by ragibson** [nunocoracao/blowfish#990]
**Describe the bug**
Long (width-wise) elements in an article break the overall style of the site, especially on mobile.

**To Reproduce**
1. Set up the website from scratch.
```bash
$ hugo new site test-site-20231005
$ cd test-site-20231005/
$ git init
$ git submodule add -b main https://github.com/nunocoracao/blowfish.git themes/blowfish
# set up the basic configuration from the documentation
```
2. Create a post with this content and note that the table extends out of the viewport width on mobile (left-most screenshot below).
```markdown
+++
title = 'Test Post'
+++

| Table LongHeader 1 | Table LongHeader 2 | Table LongHeader 3 | Table LongHeader 4 |
|--------------------|--------------------|--------------------|--------------------|
| content 1          | content 2          | content 3          | content 4          |
```
3. Create a post with this content and note that the equation extends out of the viewport on mobile and breaks out of the website width compared to the header (middle screenshot below).
```markdown
+++
title = 'Test Post'
+++

{{< katex >}}

$$
\int_2^3 \exp(10^x) \, dx = \left[ \frac{10^x}{\ln(x)} \right]_2^3 = \frac{10^2}{\ln(2)} - \frac{10^1}{\ln(1)} \approx 765.97
$$
```
4. Create a post with this content and note that the long inline code block extends out of the viewport on mobile and breaks out of the website width compared to the header (right-most screenshot below).
```markdown
+++
title = 'Test Post'
+++

Some long sentence referring to a very long bit of encoded data, say `gIkEdOl6WqnbMRhEsezBB8STzq0oTf9gOK1aqqf9fKKEysdkmymzsz3SXl02Y809`, before continuing onwards.
```

**Expected behavior**
The long article content either gets a scrollbar or broken onto multiple lines.

**Screenshots**

![image](https://github.com/nunocoracao/blowfish/assets/14023456/66656b26-b551-4564-8539-c9e2619972cf)

**Desktop (please complete the following information):**
 - OS: Linux Mint, Windows 10, iOS, and Android
 - Browser Chrome and Firefox

**Hugo & Blowfish versions**
Which version of Hugo and Blowfish are you using?

hugo v0.119.0 and the Blowfish repository from today, though the issue has persisted for a few months, at least.

**Comment by nunocoracao** [comment]
should be fixed
