### ISSUE TITLE
Change flags to language names

### ISSUE THREAD

**Issue by AndresCasado** [nunocoracao/blowfish#992]
**Is your feature request related to a problem? Please describe.**
Flags do not represent languages. For example, Spanish is spoken in a lot of different countries, and there are more than one language in Spain (there are 6 recognized by the law)

**Describe the solution you'd like**
Change the flag emojis of the language selector to the names of the languages in their native name

**Additional context**
https://www.flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/

**Comment by sgtsquiggs** [comment]
This can be modified by editing the yaml files in `themes/blowfish/i18n/` -  they're emojis by default.

**Comment by nunocoracao** [comment]
You can override how these appear on your site easily. Using @sgtsquiggs or modifying your configurations check doc websites and Hugo's documentation for more details. Re-open this ticket if you need further help.
